"""a8_downstream — pm-onethird's request: a DISJOINT check of the two downstream witnesses.

pm-onethird, mail 2026-08-07 21:12:

    "TWO LIVE RESULTS RAN THEIR OWN INDEPENDENT WITNESSES THROUGH IT ... They were
     produced by different polecats with different methods and they look independent.
     THEY SHARE ONE UNAUDITED TOOL.  Two witnesses through one instrument is one witness
     wearing a larger number. ... Report SEPARATELY: (1) is the tool correct, and (2) do
     the two downstream witnesses survive an independent check."

**(1) is answered in `a6_instrument.py`, not here.**  This script answers **(2) only**, and
the two must not be conflated: a sound tool does not make a witness right, and a right
witness does not make the tool sound.

What is disjoint, and what is not
---------------------------------
The MEASURES are taken from mg-131e and mg-00a1 as INPUT DATA -- that is the object under
test and there is no way to test it without reading it.  Everything that CHECKS them is
`liba41b7`, written from the definitions, sharing no line with `lp200d.measure_report`:

    mass, E[inv], per-pair flip probability, the 1/3 cap, comparable pairs at flip 0,
    per-slot symmetry J_k(x,y) = J_k(y,x) on incomparable pairs, transitive closure.

mg-131e's witnesses are literal in its `d3_refutation.py` and are copied here as data.
mg-00a1's are generated by its own `lib00a1.witness`, extracted from `bb0d7e9` (which was
NOT on main when this audit ran); its generator is the object under test, so importing it
to GENERATE is correct -- nothing of it is in the verification path.

CIRCULARITY GUARD.  Nothing here is evidence about mg-200d, and mg-200d's soundness is not
evidence about any of these witnesses.  Note also, for the record, that a41b7 reached
E[inv] = 11/6 at n = 6 by its OWN exhaustive LP (`a3b_level.py`, |I| = 6) BEFORE reading
mg-131e's witness at all.

usage: python3 a8_downstream.py
"""
import os
import subprocess
import sys
import tempfile
from fractions import Fraction as F

import liba41b7 as L

ok = 0
bad = []


def check(name, cond, detail=""):
    global ok
    if cond:
        ok += 1
    else:
        bad.append((name, detail))
    print("    %s  %s%s" % ("PASS" if cond else "FAIL", name, "" if cond else "   %s" % detail))


def closure(n, C):
    C = set(C)
    changed = True
    while changed:
        changed = False
        for (a, b) in list(C):
            for (c, d) in list(C):
                if b == c and (a, d) not in C:
                    C.add((a, d)); changed = True
    return frozenset(C)


def verify(n, I, mu, label, expect=None):
    """MY checker.  Returns E[inv].  Shares no line with lp200d.measure_report."""
    I = set(tuple(p) for p in I)
    C = set(p for p in L.pairs(n) if p not in I)
    rep = L.report_atoms(n, mu)
    print("  %s   n=%d  atoms=%d  |I|=%d" % (label, n, len(mu), len(I)))
    check("%s n=%d mass is exactly 1" % (label, n), rep["mass"] == 1, str(rep["mass"]))
    check("%s n=%d no negative atom" % (label, n), all(w > 0 for w in mu.values()))
    check("%s n=%d every flip <= 1/3" % (label, n),
          all(v <= F(1, 3) for v in rep["flips"].values()),
          "max %s" % max(rep["flips"].values()))
    cflip = [p for p in C if rep["flips"][p] != 0]
    check("%s n=%d comparable pairs all at flip 0" % (label, n), cflip == [], str(cflip[:4]))
    viol = [z for z in rep["slot_violations"] if (z[1], z[2]) in I]
    check("%s n=%d per-slot symmetry holds on every incomparable pair" % (label, n),
          viol == [], str(viol[:3]))
    check("%s n=%d the comparable set is transitively closed (a real poset)" % (label, n),
          closure(n, C) == frozenset(C))
    if expect is not None:
        check("%s n=%d E[inv] = %s as claimed" % (label, n, expect), rep["einv"] == expect,
              "mine %s claimed %s" % (rep["einv"], expect))
    print("      -> MY E[inv] = %-10s  eps_spec = %-10s   (n-1)/3 = %-8s  %s"
          % (rep["einv"], L.eps_spec(n, rep["einv"]), F(n - 1, 3),
             "BEATS (n-1)/3" if rep["einv"] > F(n - 1, 3) else "does not beat (n-1)/3"))
    return rep["einv"]


# --------------------------------------------------------------------- mg-131e
# Copied verbatim as DATA from code/dual_certificate_131e/d3_refutation.py.
# The second element of each entry is the set of chords BEYOND the consecutive pairs,
# so I = consecutive pairs + chords.
E131 = {
    6: ([(1, 4)], F(11, 6), {
        (0, 1, 2, 3, 5, 4): F(1, 6), (0, 1, 3, 2, 5, 4): F(1, 6),
        (0, 2, 1, 4, 3, 5): F(1, 6), (0, 2, 4, 1, 3, 5): F(1, 6),
        (1, 0, 2, 3, 4, 5): F(1, 6), (1, 0, 3, 2, 4, 5): F(1, 6)}),
    7: ([(1, 4), (2, 5)], F(20, 9), {
        (0, 1, 2, 3, 4, 5, 6): F(1, 9), (0, 1, 2, 4, 3, 5, 6): F(1, 9),
        (0, 1, 3, 5, 2, 4, 6): F(1, 9), (0, 2, 1, 3, 5, 4, 6): F(1, 9),
        (0, 2, 1, 4, 3, 6, 5): F(1, 9), (0, 2, 4, 1, 3, 6, 5): F(1, 9),
        (1, 0, 2, 3, 4, 6, 5): F(1, 9), (1, 0, 3, 2, 4, 5, 6): F(1, 9),
        (1, 0, 3, 2, 5, 4, 6): F(1, 9)}),
    8: ([(1, 4), (3, 6)], F(8, 3), {
        (0, 1, 2, 3, 5, 4, 7, 6): F(1, 6), (0, 1, 3, 2, 5, 4, 6, 7): F(1, 6),
        (0, 2, 1, 4, 3, 6, 5, 7): F(1, 6), (0, 2, 4, 1, 6, 3, 5, 7): F(1, 6),
        (1, 0, 2, 3, 4, 5, 7, 6): F(1, 6), (1, 0, 3, 2, 4, 5, 6, 7): F(1, 6)}),
    9: ([(1, 4), (2, 5), (3, 6), (4, 7)], F(28, 9), {
        (0, 1, 2, 3, 4, 5, 6, 8, 7): F(1, 9), (0, 1, 2, 4, 3, 5, 7, 6, 8): F(1, 9),
        (0, 1, 3, 5, 2, 7, 4, 6, 8): F(1, 9), (0, 2, 1, 3, 5, 4, 7, 6, 8): F(1, 9),
        (0, 2, 1, 4, 3, 6, 5, 8, 7): F(1, 9), (0, 2, 4, 1, 6, 3, 5, 8, 7): F(1, 9),
        (1, 0, 2, 3, 4, 6, 5, 7, 8): F(1, 9), (1, 0, 3, 2, 4, 5, 6, 7, 8): F(1, 9),
        (1, 0, 3, 2, 5, 4, 6, 7, 8): F(1, 9)}),
    10: ([(1, 4), (3, 6), (5, 8)], F(7, 2), {
        (0, 1, 2, 3, 5, 4, 7, 6, 9, 8): F(1, 6), (0, 1, 3, 2, 5, 4, 6, 7, 9, 8): F(1, 6),
        (0, 2, 1, 4, 3, 6, 5, 8, 7, 9): F(1, 6), (0, 2, 4, 1, 6, 3, 8, 5, 7, 9): F(1, 6),
        (1, 0, 2, 3, 4, 5, 7, 6, 8, 9): F(1, 6), (1, 0, 3, 2, 4, 5, 6, 7, 8, 9): F(1, 6)}),
}

print("=" * 78)
print("(2a) mg-131e's witnesses, checked by a41b7's own code")
print("=" * 78)
for n in sorted(E131):
    chords, claimed, mu = E131[n]
    I = set((i, i + 1) for i in range(n - 1)) | set(chords)
    verify(n, I, mu, "mg-131e", expect=claimed)

print()
print("=" * 78)
print("(2b) mg-00a1's staircase family, checked by a41b7's own code")
print("=" * 78)
tmp = tempfile.mkdtemp(prefix="a41b7-00a1-")
try:
    src = subprocess.run(["git", "show", "bb0d7e9:code/growth_rate_00a1/lib00a1.py"],
                         capture_output=True, text=True)
    if src.returncode != 0:
        print("  bb0d7e9 not reachable in this clone -- mg-00a1 arm SKIPPED, and that is")
        print("  reported as SKIPPED rather than as a pass.")
    else:
        open(os.path.join(tmp, "lib00a1.py"), "w").write(src.stdout)
        sys.path.insert(0, tmp)
        sys.path.insert(0, os.path.abspath("../perslot_symmetry_200d"))
        import lib00a1 as G   # GENERATOR ONLY -- object under test, not in the check path
        # DEFECT OF MINE, KEPT.  This first used  n(n+5)/36  at EVERY n, which is the
        # form printed in mg-00a1's s1_witness.py banner and in its table's column header.
        # Its `witness_target` is PARITY-SPLIT:  n(n+5)/36 for even n, (n-1)(n+4)/36 for
        # odd n.  My control then FAILED on all ten odd n against a CORRECT witness, and
        # would have been a false finding against a LIVE result had I reported it.  Both
        # branches of the closed form are quadratic, so nothing of mg-00a1's verdict turns
        # on it; what turns on it is that I nearly filed the error I was sent to look for.
        print("  claimed closed form: n(n+5)/36 for even n, (n-1)(n+4)/36 for odd n")
        for n in range(4, 25):
            I = G.staircase_I(n)
            mu = {tuple(p): F(w) for p, w in G.witness(n).items()}
            tgt = F(n * (n + 5), 36) if n % 2 == 0 else F((n - 1) * (n + 4), 36)
            v = verify(n, I, mu, "mg-00a1", expect=tgt)
            check("mg-00a1 n=%d |I| is quadratic (m(m+1)/2 = %d)"
                  % (n, (n // 2) * (n // 2 + 1) // 2),
                  len(I) == (n // 2) * (n // 2 + 1) // 2, str(len(I)))
            sys.stdout.flush()
finally:
    pass

print()
print("=" * 78)
print("SUMMARY -- and these are TWO claims, not one")
print("=" * 78)
print("  (1) is lp200d.measure_report a correct tool?      -> answered in a6_instrument.py")
print("  (2) do the downstream witnesses survive a41b7's")
print("      independent checker?                          -> PASS %d   FAIL %d" % (ok, len(bad)))
for nm, d in bad:
    print("        FAILED: %s  %s" % (nm, d))
sys.exit(1 if bad else 0)
