"""j1_attribution.py -- EVERY ATTRIBUTION THE APPARATUS MAKES, RE-DERIVED HERE.

mg-321d's G-2 was an apparatus built to establish provenance getting provenance
wrong about ITSELF: g4_fleet.py said ed9cde4 had touched c1_branching.py, and
ed9cde4 never touched it.  mg-7e58 repaired it.

The only audit of that repair worth making is the one that does not read g4's
answer and check it against g4.  So:

  (i)   the ground truth is derived HERE, by two routes that share no code with
        g4 -- `git log <range> -- <path>` per member, and `git show --name-only`
        per commit -- and the two must AGREE with each other before either is
        used.  If they disagree, that is a SELF-ERROR and nothing downstream is
        scored.
  (ii)  g1 and g4 are run live and EVERY attribution they print is extracted
        and compared against the ground truth, one row at a time, each scored
        AGREES / WRONG COMMIT / UNVERIFIABLE.  Nothing is taken on totals.
  (iii) the claim "it is derived from the history rather than written" is then
        tested by CHANGING THE HISTORY: three clones, in each of which a new
        commit lands, and g4's attribution must follow with no other edit.  A
        derivation regenerated by hand is not one.
  (iv)  and the things the apparatus asserts about ITSELF that nobody has
        checked: that its range endpoints resolve, that its ticket->commit step
        is unambiguous, that the mg-58da half of the summary is cross-checked
        against a named revision the way the mg-13b2 half is, and that its
        REPORTED-not-concluded file shas are true.

Exit 0 iff SELF-ERRORS == 0 and FINDINGS == 0.
"""

import os
import re
import sys

import lib957f as L

R = L.Report("j1", "the attributions g1 and g4 print (one finding each), the "
                   "two-route agreement of the ground truth, the 3 history "
                   "clones, and the 4 self-assertions in (iv)")

L.banner("J1", "EVERY ATTRIBUTION, RE-DERIVED FROM git log IN THIS SCRIPT")

HEAD = L.head_rev()
RANGE = "%s..%s" % (L.REV_A218, HEAD)
MEMBERS = [L.A218_DIR + "/" + f for f in L.FIVE]
KERN = L.A218_DIR + "/kern_a218.py"

# ---------------------------------------------------------------------------
L.rule("(i) THE GROUND TRUTH, DERIVED TWICE, BEFORE ANYTHING IS READ FROM g4")
print("""   Route one asks the LOG about a path.  Route two asks a COMMIT what it
   did.  They are different questions with the same answer, and the answer is
   only used if both give it.  Neither shares a line with g4_fleet.py.""")
print()
print("   range: %s..%s" % (L.REV_A218[:8], HEAD[:8]))
print("     left  endpoint %s  %s" % (L.REV_A218[:8], L.subject(L.REV_A218)[:44]))
print("     right endpoint %s  %s" % (HEAD[:8], L.subject(HEAD)[:44]))
print()


def ground_truth(repo=L.REPO, head=None):
    """(member -> [commits], commit -> [members]).  Route one, cross-checked
    against route two.  Returns (per_member, per_commit, disagreements)."""
    hd = head or L.head_rev(repo=repo)
    rng = "%s..%s" % (L.REV_A218, hd)
    per_member = {}
    for f in L.FIVE:
        per_member[f] = L.log_paths(rng, L.A218_DIR + "/" + f, repo=repo)
    # route two: every commit in the range that touched the directory, asked
    # what IT touched
    dir_commits = L.log_paths(rng, L.A218_DIR, repo=repo)
    per_commit = {}
    for h in dir_commits:
        hit = [f for f in L.FIVE
               if (L.A218_DIR + "/" + f) in L.show_names(h, repo=repo)]
        if hit:
            per_commit[h] = sorted(hit)
    # the two must agree
    bad = []
    for f in L.FIVE:
        one = sorted(per_member[f])
        two = sorted(h for h, fs in per_commit.items() if f in fs)
        if one != two:
            bad.append((f, [x[:8] for x in one], [x[:8] for x in two]))
    return per_member, per_commit, bad


PER_MEMBER, PER_COMMIT, ROUTE_BAD = ground_truth()
print("   route one -- git log <range> -- <path>, per member:")
for f in L.FIVE:
    print("     %-22s %s" % (f, ", ".join(h[:8] for h in PER_MEMBER[f])
                             or "NONE"))
print()
print("   route two -- git show --name-only, per commit touching the directory:")
for h in PER_COMMIT:
    print("     %-8s  %s" % (h[:8], ", ".join(PER_COMMIT[h])))
print()
if ROUTE_BAD:
    for f, one, two in ROUTE_BAD:
        R.selferr("this script's two routes disagree about %s: log says %s, "
                  "--name-only says %s; nothing below is scored" % (f, one, two))
    print("   THE TWO ROUTES DISAGREE.  Nothing below is scored.")
else:
    print("   THE TWO ROUTES AGREE at %d of %d members.  This is the ground "
          "truth used below." % (len(L.FIVE), len(L.FIVE)))
print()
print("   and the kernel the five share, for the same range:")
KERN_COMMITS = L.log_paths(RANGE, KERN)
print("     %-22s %s" % ("kern_a218.py",
                         ", ".join(h[:8] for h in KERN_COMMITS) or "NONE"))
TARGET_COMMITS = L.log_paths(RANGE, L.TARGET_REL)
print("     %-22s %s" % ("out_t1_tl.txt",
                         ", ".join(h[:8] for h in TARGET_COMMITS) or "NONE"))
print()

# ---------------------------------------------------------------------------
L.rule("(ii) g4 AND g1, RUN LIVE -- AND EVERY ATTRIBUTION THEY PRINT, SCORED")

print("   running code/branching_audit_58da/g4_fleet.py in place ...")
g4_out, g4_rc = L.run_script(L.S58DA_DIR, "g4_fleet.py")
print("   running code/branching_audit_58da/g1_provenance.py in place ...")
g1_out, g1_rc = L.run_script(L.S58DA_DIR, "g1_provenance.py")
g4_s, g4_f = L.totals_of(g4_out)
g1_s, g1_f = L.totals_of(g1_out)
print("     g4  exit %d  SELF %s  FINDINGS %s" % (g4_rc, g4_s, g4_f))
print("     g1  exit %d  SELF %s  FINDINGS %s" % (g1_rc, g1_s, g1_f))
if g4_s is None or g1_s is None:
    R.selferr("could not read the totals out of g1's or g4's stdout; the "
              "attributions below are scored but the totals are not")
print()


def short(hs):
    return sorted(h[:8] for h in hs)


# --- the extractor.  Every claim of the form "X was touched by Y" ------------
def g4_member_rows(out):
    """member -> the commit prefixes its own sha row names."""
    rows = {}
    for line in out.splitlines():
        tok = line.split()
        if len(tok) >= 2 and tok[0] in L.FIVE:
            if tok[1] == "CHANGED" and line.count("(") >= 1:
                inner = line.split("(", 1)[1].split(")", 1)[0]
                rows[tok[0]] = sorted(x.strip() for x in inner.split(",")
                                      if x.strip())
            elif tok[1] == "same":
                rows[tok[0]] = []
    return rows


def g4_commit_rows(out):
    """commit prefix -> (ticket, [members]) from the ATTRIBUTION block."""
    rows, cur = {}, None
    inblock = False
    for line in out.splitlines():
        if "ATTRIBUTION, INVERTED FROM THE SAME git log CALLS" in line:
            inblock = True
            continue
        if inblock and line.startswith("---"):
            break
        if not inblock:
            continue
        s = line.strip()
        if s.startswith("touches:") and cur is not None:
            body = s.split("touches:", 1)[1].strip()
            rows[cur] = (rows[cur][0],
                         [] if body == "none"
                         else sorted(x.strip() for x in body.split(",")))
            cur = None
            continue
        tok = s.split()
        if len(tok) >= 2 and (len(tok[0]) == 8 or tok[0] == "(none)"):
            cur = tok[0]
            rows[cur] = (tok[1], None)
    return rows


def g4_summary(out):
    """the three 'of the five, touched by …' lines -> (label, n, [members])."""
    got = []
    for line in out.splitlines():
        if "of the five, touched by" not in line:
            continue
        label, tail = line.split("touched by", 1)[1].split(":", 1)
        n = int(tail.strip().split("--")[0].strip())
        body = tail.split("--", 1)[1].strip()
        got.append((label.strip(), n,
                    [] if body == "none"
                    else sorted(x.strip() for x in body.split(","))))
    return got


def g1_touch_rows(out):
    """file -> [commit prefixes] from g1 (ii)'s 'commits touching each part'."""
    rows = {}
    for line in out.splitlines():
        s = line.strip()
        if not s.startswith(("c1_branching.py", "kern_a218.py",
                             "out_t1_tl.txt")):
            continue
        if "(" not in s or ")" not in s:
            continue
        name = s.split()[0]
        tail = s.split(")", 1)[1].strip()
        rows[name] = [] if tail == "NONE" else sorted(x.strip()
                                                      for x in tail.split(","))
    return rows


def g1_sha_rows(out):
    """file -> 'SAME' | 'CHANGED' from g1 (ii)'s REPORTED sha table."""
    rows = {}
    for line in out.splitlines():
        tok = line.split()
        if len(tok) == 5 and tok[0] in ("c1_branching.py", "kern_a218.py") \
                and tok[4] in ("SAME", "CHANGED") and tok[2] == "...":
            rows[tok[0]] = tok[4]
    return rows


MROWS = g4_member_rows(g4_out)
CROWS = g4_commit_rows(g4_out)
SUMS = g4_summary(g4_out)
G1T = g1_touch_rows(g1_out)
G1S = g1_sha_rows(g1_out)

AGREE, WRONG, UNVERIF = [], [], []


def score(where, claim, verdict, why):
    """One attribution, scored.  UNVERIFIABLE is its own answer and is never
    silently folded into AGREES -- an attribution this script could not read is
    a fact about this script and appears as its own row."""
    {"AGREES": AGREE, "WRONG COMMIT": WRONG,
     "UNVERIFIABLE": UNVERIF}[verdict].append((where, claim))
    print("     %-46s %-14s %s" % (claim[:46], verdict, why[:60]))
    if verdict == "WRONG COMMIT":
        R.finding("%s attributes %s -- %s" % (where, claim, why))
    if verdict == "UNVERIFIABLE":
        R.selferr("%s: this script could not extract %r to score it (%s)"
                  % (where, claim, why))


print("   ATTRIBUTION                                    VERDICT        why")
print("   " + "-" * 68)

# --- g4's five member rows --------------------------------------------------
for f in L.FIVE:
    truth = short(PER_MEMBER[f])
    claim = "g4 row: %s <- %s" % (f, ", ".join(MROWS.get(f, [])) or "nothing")
    if f not in MROWS:
        score("g4 (ii) member row", claim, "UNVERIFIABLE", "row not found")
    elif sorted(MROWS[f]) == truth:
        score("g4 (ii) member row", claim, "AGREES",
              "git log here: %s" % (", ".join(truth) or "nothing"))
    else:
        score("g4 (ii) member row", claim, "WRONG COMMIT",
              "git log here says %s" % (", ".join(truth) or "nothing"))

# --- g4's per-commit rows ---------------------------------------------------
for h, members in PER_COMMIT.items():
    key = h[:8]
    claim = "g4 row: %s -> %s" % (key, ", ".join(members))
    if key not in CROWS:
        score("g4 (ii) commit row", claim, "UNVERIFIABLE",
              "no row for this commit")
    elif CROWS[key][1] == members:
        score("g4 (ii) commit row", claim, "AGREES",
              "--name-only here: %s" % ", ".join(members))
    else:
        score("g4 (ii) commit row", claim, "WRONG COMMIT",
              "--name-only here: %s" % ", ".join(members))
for key in CROWS:
    if key == "(none)":
        continue
    if key not in [h[:8] for h in PER_COMMIT]:
        score("g4 (ii) commit row", "g4 row: %s -> %s" % (key, CROWS[key][1]),
              "WRONG COMMIT", "no commit in the range touched any of the five "
                              "at this sha")

# --- g4's per-commit TICKET labels ------------------------------------------
for h in PER_COMMIT:
    key = h[:8]
    if key not in CROWS:
        continue
    subj = L.subject(h).rstrip()
    m = re.search(r"\(mg-([0-9a-f]{4})\)$", subj)
    want = "mg-" + m.group(1) if m else "?"
    claim = "g4 label: %s is %s" % (key, CROWS[key][0])
    if CROWS[key][0] == want:
        score("g4 (ii) ticket label", claim, "AGREES",
              "its own subject ends %r" % subj.rstrip()[-10:])
    else:
        score("g4 (ii) ticket label", claim, "WRONG COMMIT",
              "its own subject ends %r" % subj.rstrip()[-10:])

# --- g4's three summary lines -----------------------------------------------
truth_13b2 = sorted(f for f in L.FIVE
                    if L.resolve(L.REV_13B2) in PER_MEMBER[f])
truth_58da = sorted(f for f in L.FIVE
                    if L.resolve(L.REV_58DA) in PER_MEMBER[f])
dirty = sorted(f for f in L.FIVE
               if (L.A218_DIR + "/" + f) in L.dirty_paths())
want_sum = {"mg-13b2": truth_13b2, "mg-58da": truth_58da,
            "uncommitted": dirty}
for label, n, members in SUMS:
    key = ("mg-13b2" if "mg-13b2" in label else
           "mg-58da" if "mg-58da" in label else
           "uncommitted" if "uncommitted" in label else None)
    claim = "g4 summary: %s -> %d (%s)" % (label[:22], n,
                                           ", ".join(members) or "none")
    if key is None:
        score("g4 (ii) summary", claim, "UNVERIFIABLE", "unrecognised label")
    elif members == want_sum[key] and n == len(want_sum[key]):
        score("g4 (ii) summary", claim, "AGREES",
              "derived here: %s" % (", ".join(want_sum[key]) or "none"))
    else:
        score("g4 (ii) summary", claim, "WRONG COMMIT",
              "derived here: %s" % (", ".join(want_sum[key]) or "none"))

# --- g1's three read-path rows and its two REPORTED sha rows ----------------
for name, rel in [("c1_branching.py", L.A218_DIR + "/c1_branching.py"),
                  ("kern_a218.py", KERN),
                  ("out_t1_tl.txt", L.TARGET_REL)]:
    truth = short(L.log_paths(RANGE, rel))
    claim = "g1 row: %s <- %s" % (name, ", ".join(G1T.get(name, [])) or "NONE")
    if name not in G1T:
        score("g1 (ii) read-path row", claim, "UNVERIFIABLE", "row not found")
    elif sorted(G1T[name]) == truth:
        score("g1 (ii) read-path row", claim, "AGREES",
              "git log here: %s" % (", ".join(truth) or "NONE"))
    else:
        score("g1 (ii) read-path row", claim, "WRONG COMMIT",
              "git log here: %s" % (", ".join(truth) or "NONE"))

for name, rel in [("c1_branching.py", L.A218_DIR + "/c1_branching.py"),
                  ("kern_a218.py", KERN)]:
    moved = L.sha(L.git_show(L.REV_A218, rel)) != L.sha(L.git_show(HEAD, rel))
    want = "CHANGED" if moved else "SAME"
    claim = "g1 sha row: %s is %s" % (name, G1S.get(name, "?"))
    if name not in G1S:
        score("g1 (ii) sha row", claim, "UNVERIFIABLE", "row not found")
    else:
        score("g1 (ii) sha row", claim,
              "AGREES" if G1S[name] == want else "WRONG COMMIT",
              "sha256 at both revisions here: %s" % want)

print()
print("   ATTRIBUTIONS SCORED: %d.  Population: g4's %d member rows, its %d "
      "per-commit rows and %d ticket labels, its %d summary lines, g1's %d "
      "read-path rows and %d REPORTED sha rows -- every claim of the form "
      "'X was touched by Y' either script prints."
      % (len(AGREE) + len(WRONG) + len(UNVERIF), len(L.FIVE), len(PER_COMMIT),
         len(PER_COMMIT), len(SUMS), 3, 2))
print("     AGREES       : %d" % len(AGREE))
print("     WRONG COMMIT : %d" % len(WRONG))
print("     UNVERIFIABLE : %d" % len(UNVERIF))
print()

# ---------------------------------------------------------------------------
L.rule("(iii) IS IT DERIVED?  TESTED BY CHANGING THE HISTORY, NOT BY READING")
print("""   "Derived from git log" is a claim about what happens when the log
   changes.  A derivation regenerated by hand is not one.  So three clones,
   each with ONE new commit landing and NO other edit, and in each g4's
   attribution must follow.  Two of the three move it; the third must not.""")
print()

CLONES = [
    ("a commit touching c3_withdrawal.py, which nothing in the range touched",
     L.A218_DIR + "/c3_withdrawal.py",
     "probe: touch c3_withdrawal.py (mg-957f)", "c3_withdrawal.py", True),
    ("a SECOND commit touching c1_branching.py, which 673b4c0 already touched",
     L.A218_DIR + "/c1_branching.py",
     "probe: touch c1_branching.py again (mg-957f)", "c1_branching.py", True),
    ("a commit touching NOTHING among the five -- the NULL PROBE",
     L.S321D_DIR + "/README.md",
     "probe: touch a file outside the five (mg-957f)", None, False),
]

print("   clone                                          member      g4 follows")
followed = 0
for why, path, msg, member, must_move in CLONES:
    def _mut(tree, _p=path):
        with open(os.path.join(tree, _p), "a") as fh:
            fh.write("\n# mg-957f history probe\n")

    tmp, tree = L.clone(mutate=_mut, message=msg)
    try:
        chead = L.head_rev(repo=tree)
        tm, tc, tbad = ground_truth(repo=tree, head=chead)
        if tbad:
            R.selferr("in the clone %r this script's own two routes disagree; "
                      "the clone is not scored" % why)
            continue
        out, _rc = L.run_script(L.S58DA_DIR, "g4_fleet.py", repo=tree)
        rows = g4_member_rows(out)
        crows = g4_commit_rows(out)
        ok = all(sorted(rows.get(f, ["?"])) == short(tm[f]) for f in L.FIVE)
        ok = ok and all(crows.get(h[:8], (None, None))[1] == tc[h]
                        for h in tc)
        newrow = chead[:8] in crows
        moved = (member is not None
                 and chead[:8] in short(tm[member])
                 and chead[:8] in rows.get(member, []))
        print("     %-46s %-11s %s"
              % (why[:46], member or "(none)",
                 "YES" if ok else "NO"))
        print("       new commit %s appears as its own row: %s; %s"
              % (chead[:8], "yes" if newrow else "no",
                 ("%s now names it: %s" % (member, "yes" if moved else "NO"))
                 if member else "no member row moved, as predicted"))
        good = ok and (newrow == must_move) and (moved == must_move)
        if member is None:
            # the null probe: no member row may have moved at all
            good = ok and not newrow and all(
                sorted(rows.get(f, ["?"])) == short(PER_MEMBER[f])
                for f in L.FIVE)
        followed += bool(good)
        R.check(good,
                "g4's attribution did not follow the history in the clone "
                "with %s: rows=%s, new commit row present=%s (expected %s)"
                % (why, {f: rows.get(f) for f in L.FIVE}, newrow, must_move))
    finally:
        L.destroy(tmp)
print()
print("   clones in which the attribution followed the history: %d of %d"
      % (followed, len(CLONES)))
print("   population: the 3 clones above -- two in which a member's attribution")
print("   MUST move and one in which nothing among the five may move.")
print()

# ---------------------------------------------------------------------------
L.rule("(iv) WHAT ELSE THE APPARATUS ASSERTS ABOUT ITSELF, AND NOBODY CHECKED")
print("""   The repair's own k1 checks the map.  These are the four claims the
   apparatus makes about its OWN machinery, which its instrument does not put
   a gate on.""")
print()

# S1 -- both endpoints resolve, and the left one is not merely a string
try:
    left = L.resolve(L.REV_A218)
    print("   S1  the range's left endpoint resolves          : %s  ok"
          % left[:8])
    R.check(left == L.REV_A218,
            "lib58da's REV_A218 is not a full resolved sha")
except Exception as e:                                        # noqa: BLE001
    R.finding("lib58da's REV_A218 does not name a commit in this repo (%s)" % e)

# S2 -- ticket -> commit is unambiguous IN RANGE
ids = {}
for h in PER_COMMIT:
    s = L.subject(h)
    tag = s.rstrip()[-9:] if s.rstrip().endswith(")") else "?"
    ids.setdefault(tag, []).append(h[:8])
dupes = {k: v for k, v in ids.items() if len(v) > 1 and k != "?"}
print("   S2  in-range commits carrying the same (mg-id)  : %s  %s"
      % (dupes or "none", "ok" if not dupes else "AMBIGUOUS"))
R.check(not dupes, "two commits in the audited range carry the same mg-id, so "
                   "g4's ticket -> commit step is ambiguous: %s" % dupes)

# S3 -- the mg-58da half of the summary is NOT cross-checked against a named
#       revision the way the mg-13b2 half is.  Measured, not argued.
src = L.read_worktree(L.S58DA_DIR + "/g4_fleet.py")
has_13b2_gate = "L.REV_13B2[:8]" in src
has_58da_gate = "REV_58DA" in src
print("   S3  summary rows cross-checked against a named revision:")
print("         mg-13b2 half : %s" % ("yes" if has_13b2_gate else "no"))
print("         mg-58da half : %s" % ("yes" if has_58da_gate else "no"))
print("       lib58da names REV_58DA at all           : %s"
      % ("yes" if "REV_58DA" in L.read_worktree(L.S58DA_DIR + "/lib58da.py")
         else "no"))
print("       -- REPORTED.  It is an asymmetry, not a wrong attribution: the")
print("       mg-58da row's MEMBER list still comes from git log and is scored")
print("       in (ii).  Only the ticket -> commit step for that row rests on a")
print("       subject alone, and S2 shows the subjects are unambiguous here.")

# S4 -- the file shas g1 REPORTS are true, and are genuinely not concluded from
print("   S4  g1's file-sha rows are reported and not concluded from:")
n_find_mentioning_sha = len([x for x in L.findings_of(g1_out)
                             if "sha" in x.lower() and "changed between" in x])
print("         g1 findings of the old file-sha form            : %d"
      % n_find_mentioning_sha)
R.check(n_find_mentioning_sha == 0,
        "g1 still books a file-sha difference as a finding")
print()

sys.exit(R.emit())
