#!/usr/bin/env python3
"""mg-30bd — THE CLASSIFIER FOR VERDICT-STALENESS, AND THE TOKEN SET IS THE INSTRUMENT.

WHY THIS EXISTS.  `code/asof_census_20ee` measures a population defined by `path:NNN`
ADDRESSES into files the instrument does not own.  mg-20ee said in as many words that "the
verdicts are not affected ... this must not be reported as a correctness defect", and that
sentence is TRUE OF THE POPULATION THAT CENSUS MEASURES AND FALSE OF THE CORPUS.  A
transcript can drift in its VERDICTS without any address moving, and such a transcript is
invisible to an address classifier BY CONSTRUCTION — it is not looking for that.

`code/species_extent_audit_6cb9` is the existence proof and it was found BY ACCIDENT, by
p6e4f, while pinning something else: its committed `out_a1_bothways.txt` says
`A1 TOTAL BAD: 1` with a `*** MISSED ***` row and two `*** EXTENT WIDER ***` rows; the same
script at HEAD today says `A1 TOTAL BAD: 0` and those rows are gone.  6cb9 is NOT among
mg-20ee's 44 candidates, so it sits outside the corrected population of 32 entirely.

A stale ADDRESS relocates a reader wrongly.  A stale VERDICT says the corpus measured
something it no longer measures — and it reads as a finding.  This module measures the
second class.  IT REPAIRS NOTHING: a verdict that has moved is a finding about the corpus and
needs an owner per instance, not a batch repair.

------------------------------------------------------------------------------------------
THE CLASSIFICATION, IN ORDER.  Each step is a REFINEMENT of the one before, and the first
two are BORROWED rather than re-spelled, because a second definition of "benign" is a second
place for the definition to drift.

  0  IDENTICAL          the committed bytes and the regenerated bytes are equal.
  1  BENIGN/f771        `lib_f771.verdict_for` says NOISE — i.e. the difference is entirely
                        inside mg-f771's declared N1 (an absolute path to a checkout of this
                        repository) and N2 (decimal seconds), under N3's prefix rule.  This
                        is the TIMING family and the CHECKOUT-PATH family, and it is the
                        gate's own definition, imported and not re-implemented.
  2  BENIGN/address     under A1 (a `file.ext:NNN` or `dir/file:NNN` line address) and A2
                        (a git sha, an ISO date, a clock time) the two texts become
                        equivalent.  This is mg-c824/mg-20ee's ADDRESS family and the
                        AS-OF-BLOCK family.
  3  VERDICT-STALE      the two texts differ in their VERDICT LINES (below).  THE HEADLINE.
  4  NON-VERDICT        they differ, but not in any verdict line.  Corpus-size counts land
                        here, and so does everything else this instrument has no name for.

WHY CORPUS-SIZE IS NOT MASKED, THOUGH THE TICKET NAMES IT A BENIGN FAMILY.  Masking it means
masking INTEGERS, and `A1 TOTAL BAD: 1 -> 0` is an integer.  A mask wide enough to eat
"530 markdown file(s) -> 531" and narrow enough to spare "TOTAL BAD: 1 -> 0" is a mask about
nouns, i.e. a list of the corpus nouns somebody has already looked at — mg-f771's own
warning about a wider normaliser being "an unfalsifiable escape hatch" applies exactly.  So
corpus-size is NOT proven benign here; it falls into bucket 4 and is COUNTED there.  Nothing
in the headline depends on that choice, because the headline is defined by MOVEMENT IN
VERDICT LINES and not by what is left over.

------------------------------------------------------------------------------------------
THE TOKEN SET.  `TOKENS` below is the instrument and it must be quotable, so it is a
hand-typed literal and not a regex over "words that look like verdicts".  A line is a
VERDICT LINE iff, after normalisation, it contains at least one token as a whole word.

Each token is ALL-CAPS.  That is a rule and not an accident: this corpus writes its graded
outcomes in capitals (`*** MISSED ***`, `VERDICT: RED`, `TOTAL BAD: 1`, `CAUGHT`, `HELD`)
and writes its prose in sentence case, so the case requirement is most of the selectivity.
The tokens were chosen by reading the ALL-CAPS frequency table over all 1051 tracked
transcripts at HEAD (the derivation is in README §2) and keeping the words that name a
GRADED OUTCOME or LABEL ONE, then dropping the ones that are only ever prose emphasis
(`THE`, `AND`, `NOT`, `THIS`, `EVERY`, ...).

WHAT THE CHOICE COSTS, STATED RATHER THAN DISCOVERED:
  * OVER-INCLUSION.  A corpus-size count that happens to sit on a line carrying a token
    ("PASS -- 530 file(s)") is graded VERDICT-STALE by this instrument.  That is why the
    verdict-stale bucket is SPLIT into TOKEN-MOVE (a token appeared, vanished or changed)
    and NUMBER-ON-A-VERDICT-LINE (the tokens are the same multiset and a number under one
    moved).  Both are reported; only the first is the strong claim.
  * UNDER-INCLUSION.  A verdict stated in a word not on the list, or in lower case, is
    invisible here.  That is a blind spot of the TOKEN SET, and it is distinct from the
    blind spot of the METHOD (README §5).
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

# mg-f771's normaliser is IMPORTED, not copied.  Its N1/N2/N3 are the gate's own definition
# of "not a function of repo state", and this instrument's bucket 1 must be that definition
# rather than a second one that can drift away from it.
sys.path.insert(0, os.path.join(ROOT, "code", "gate_fixed_point_f771"))
import lib_f771                                                    # noqa: E402


# ======================================================================================
# A1/A2 — the ADDRESS and AS-OF-BLOCK masks.  Applied ONLY after mg-f771 has already said
# DISAGREES, so they can never make the gate's own verdict looser than the gate's.
# ======================================================================================

# A1.  A LINE ADDRESS, and the thing in front of the colon must LOOK LIKE A PATH — it must
# carry a dot-extension or a slash.  `build.sh:342`, `STATE.md:210`, `code/a/b.py:17` are
# addresses; `TOTAL BAD:1` is not, and world W12 holds that boundary.  The first version of
# this regex was `(?<=[\w./-]):\d+\b`, which ate the second one.
ADDRESS = re.compile(r"\b((?:[\w.-]*/)*[\w-]+\.[A-Za-z][\w]{0,5}|(?:[\w.-]+/)+[\w.-]+):\d+\b")

# A2.  The as-of block: a git sha, an ISO date, a clock time.  A sha is 7-40 hex characters
# as a whole word; the length floor is 7 because this repo quotes short shas.
SHA = re.compile(r"\b[0-9a-f]{7,40}\b")
DATE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
CLOCK = re.compile(r"\b\d{1,2}:\d{2}(?::\d{2})?\b")


def mask_address_and_asof(text):
    """A1 + A2.  Pure string -> string."""
    text = ADDRESS.sub(lambda m: m.group(1) + ":<L>", text)
    text = DATE.sub("<date>", text)
    text = CLOCK.sub("<clock>", text)
    text = SHA.sub("<sha>", text)
    return text


# THE ONE THAT FAILED, KEPT RATHER THAN DELETED.  This was the first `ADDRESS`, and it eats
# `TOTAL BAD:1` — i.e. it turns the exact number this ticket is about into a benign address
# move.  `selftest_30bd.py` re-runs the classification under it every time the suite runs, so
# the failure is a measurement on the record and not a sentence in a README.
NAIVE_ADDRESS = re.compile(r"(?<=[\w./-]):\d+\b")


def naive_mask(text):
    """A1 as first written, with A2 unchanged, for the selftest's demonstration only."""
    text = NAIVE_ADDRESS.sub(":<L>", text)
    text = DATE.sub("<date>", text)
    text = CLOCK.sub("<clock>", text)
    text = SHA.sub("<sha>", text)
    return text


# ======================================================================================
# THE TOKEN SET
# ======================================================================================

TOKENS = (
    # graded outcomes
    "AGREES", "BAD", "BROKEN", "CAUGHT", "CLEAN", "CONFIRMED", "DIFFER", "DIFFERS",
    "DISAGREES", "FAIL", "FAILED", "FAILS", "FALSE", "FIRED", "FIRES", "GREEN", "HELD",
    "HIT", "HOLDS", "LAUNDERED", "MISS", "MISSED", "MISSING", "NARROWER", "NOISE",
    "OVERSTATES", "PASS", "PASSED", "RED", "REFUSED", "REFUTED", "REPRODUCES", "SILENT",
    "SLACK", "TRUE", "UNDERSTATES", "UNFALSIFIABLE", "UNMEASURED", "WIDER", "WRONG",
    # the labels a graded outcome is written under
    "FINDING", "FINDINGS", "VERDICT", "VERDICTS",
)

TOKEN_RE = re.compile(r"\b(?:%s)\b" % "|".join(sorted(TOKENS, key=len, reverse=True)))


def verdict_tokens(line):
    """The tokens on one line, in order of appearance (a list, so repeats count)."""
    return TOKEN_RE.findall(line)


def is_verdict_line(line):
    return bool(TOKEN_RE.search(line))


def canonical(text, mask=None):
    """N1+N2 (mg-f771) then A1+A2.  The text every comparison below is made on.

    `mask` is a parameter for ONE reason: `selftest_30bd.py` re-runs the classification under
    the ADDRESS REGEX THAT FAILED, so that failure stays on the record as a run rather than
    as a sentence in a README.  Nothing else passes it.
    """
    return (mask or mask_address_and_asof)(lib_f771.normalise(text))


def verdict_lines(text):
    """The canonical lines that carry at least one token, SORTED.

    Sorted, and not in file order, because a verdict that MOVED UP THE PAGE because an
    unrelated section grew is not a verdict that moved.  What is being measured is the SET
    OF GRADED STATEMENTS the transcript makes, not their layout.
    """
    return sorted(l.strip() for l in text.splitlines() if is_verdict_line(l))


def token_multiset(text):
    """Every token on every verdict line, as a sorted list — repeats included."""
    out = []
    for line in text.splitlines():
        if is_verdict_line(line):
            out.extend(verdict_tokens(line))
    return sorted(out)


# ======================================================================================
# THE DECLARATION — A TRANSCRIPT THAT SAYS IT CANNOT BE A FIXED POINT (mg-5491)
# ======================================================================================
#
# WHY THE CLASSIFIER NEEDED ONE.  `code/audit_c067/out_c1_rebase.txt` opens
#
#     A TRUE RECORD WHOSE OWN PRODUCER CAN NO LONGER SEE IT.  DO NOT RE-RUN THIS.
#
# and explains, in the file, that a re-run writes a FALSE 0 over a TRUE 5 because its
# producer pairs commits by subject inside `git log -n 40`.  mg-30bd's sweep re-ran it and
# graded the result, so the record carries the instrument's own blindness as a finding about
# the corpus.  `code/verdict_delivery_bf3f`'s four read the LIVE mg verdict and mail stream:
# no commit can make them reproduce, and re-running them measures a different afternoon.
# Those five are not findings about this repository at all, and reading them one at a time is
# how that was found.  THE GENERAL REPAIR IS NOT FIVE EXCLUSIONS, IT IS A NOTION: give the
# classifier a way for a transcript to say `I am not a fixed point, and here is why`, and the
# whole class stops being false positives instead of these five stopping.
#
# WHY IT IS NOT AN UNFALSIFIABLE ESCAPE HATCH, WHICH IS THE OBJECTION IT HAS TO SURVIVE —
# mg-f771's own warning about a wider normaliser, one instrument along.  Four things, and the
# third is the one that does the work:
#
#   1  IT IS A HAND-TYPED LITERAL, not a regex over "prose that sounds like a disclaimer".
#      `DO NOT RE-RUN THIS` in a sentence is not a declaration; this line is.
#   2  IT MUST BE IN THE FIRST `DECLARATION_WINDOW` LINES.  A declaration is made at the
#      HEAD of the file it is about.  The window is what stops a QUOTATION exempting the
#      transcript that quotes it — and this estate's instruments quote each other constantly,
#      including `report.py`, which prints this literal in its own §3b.
#   3  IT IS CHECKED IN BOTH DIRECTIONS.  A transcript declaring itself unable to reproduce,
#      WHICH THEN REPRODUCES BYTE-IDENTICALLY IN THE SWEEP, is a FALSE DECLARATION and
#      report.py §3b says so as a finding.  That is the same discipline mg-937c put on
#      `cause: RECORD-DISAGREES`: a hand field the record can contradict is a claim, and a
#      hand field it cannot is a laundry.
#   4  NOTHING IS HIDDEN.  Every declaration is COUNTED AND LISTED with the bucket it would
#      have carried, so the exemption class is exactly as visible as the stale class, and it
#      grows in public.
#
# WHAT IT STILL CANNOT CHECK, SAID HERE RATHER THAN DISCOVERED LATER: that the REASON is the
# right reason, or that no commit could have made the transcript reproduce.  A declaration is
# a judgement by the transcript's owner and this is an ADDRESS for it, not a proof of it.

DECLARATION = "NOT-A-FIXED-POINT:"

# 20 lines.  Long enough for a `#`-commented note header to carry the marker after a rule and
# a title, short enough that no listing, table or quotation in the body of a transcript can
# reach it.  Measured against the corpus rather than guessed: the five transcripts this
# repair covers carry theirs at lines 2-6.
DECLARATION_WINDOW = 20


def declaration(text):
    """The transcript's own declaration that it is not a fixed point, or None.

    Returns the REASON — whatever follows the marker on its line.  An empty reason comes
    back as `""` and is NOT honoured: report.py counts it MALFORMED and grades the
    transcript exactly as if the line were not there, because a marker with nothing after it
    is an exemption nobody signed.  The two are different answers and `None` is neither.
    """
    for line in text.split("\n")[:DECLARATION_WINDOW]:
        s = line.strip().lstrip("#").strip()
        if s.startswith(DECLARATION):
            return s[len(DECLARATION):].strip()
    return None


# ======================================================================================
# THE HISTORY-WALK LINE — A DETECTOR THAT WAS NARROWER THAN THE FAMILY IT NAMED (mg-aff1)
# ======================================================================================
#
# WHAT IT IS FOR.  `report.py` puts a NOTE on a verdict-stale entry whose moved lines are a
# `git log` walk, because that entry's cause is legible from the lines themselves and a
# reader should not have to re-derive it.  It annotates; it grades nothing, moves no bucket
# and changes no count.  That is why widening it is cheap and why getting it wrong is not:
# a NOTE is an assertion about somebody else's transcript, printed in this corpus's record.
#
# THE DEFECT.  It lived in `report.py` as `^\s*(?:HEAD:\s*)?<sha>\s+\S` — a masked sha at
# the START of the line.  mg-937c's own arm measured what that missed and said so: 5 of the
# 9 rows the baseline calls HISTORY-WALK carried no NOTE, found by READING them rather than
# by the detector, and named three times as owed and as wanting its own commit.  The newest
# of the nine arrived in mg-5491's first caught growth event and was one of the five, so the
# under-detection was getting worse in the rows that were arriving.
#
# THE TWO SHAPES IT MISSED, AND THE ONE IT STILL DOES:
#
#   1  A LABELLED SHA.  `by <sha>  repair: ...`, `at <sha>: ## ...`,
#      `the tip      <sha> <date>  docs: ...` — a walk whose format string puts a word in
#      front of the sha, or a colon behind it.  Repaired here.
#   2  `HEAD's subject : <subject>` — named in mg-937c's own §6.4 as the shape it misses.
#      A hand-typed literal, exactly like DECLARATION and for the same reason.  Repaired.
#   3  A BARE COMMIT SUBJECT with no sha and no label at all.  NOT repaired, and §6.4 of
#      out_owners_937c.txt now measures why rather than asserting it: see `walk_bare_subject`.
#
# WHY THE WINDOW, WHICH IS THE HALF THAT DOES THE WORK.  `a <sha> anywhere in the line` is
# the obvious widening and it is REFUTED ON THE RECORD, not argued against: it fires on
# every FINDING sentence that happens to quote a sha, and out_owners_937c.txt §6.4 prints
# the count.  A walk line puts its sha in a COLUMN, so the sha sits at the head of the line
# behind at most a short word label — letters and spaces only, no punctuation, because
# `FINDING: ... deleted by <sha> ...` and `N20 H8: the <sha> table's` are prose and their
# prefixes say so.  The window is measured, not chosen: the widest true label on the record
# is `the tip      ` at 13 characters, and the hit set is IDENTICAL at every window from 13
# to 24, so 16 is inside a plateau rather than tuned to a corpus.
#
# WHAT NO WINDOW CAN DO, AND WHY THE THIRD SHAPE STAYS OPEN.  A bare commit subject is
# prose, and the only non-fuzzy way to know one is to compare it against the history it came
# from.  THAT IS REFUSED ON THIS DIRECTORY'S OWN GROUNDS: a detector that reads `git log`
# answers differently on different days, so the transcript carrying its answer stops being a
# function of repo state — which is mg-e720's family, the very class this NOTE names.  A
# history-walk detector that walked history would be a member of the population it counts.

WALK_LABEL_WINDOW = 16

# The `HEAD's subject` label, hand-typed for DECLARATION's reason 1: a literal, not a regex
# over "prose that sounds like a commit subject".
HEAD_SUBJECT = re.compile(r"^\s*HEAD's subject\s*:\s*\S")

WALK_SHA = re.compile(r"^(?:HEAD:\s*)?[A-Za-z ]{0,%d}<sha>[:,]?\s+\S" % WALK_LABEL_WINDOW)


def is_walk_line(line):
    """Is this masked line one row of a `git log` walk?  Pure string -> bool."""
    return bool(WALK_SHA.match(line) or HEAD_SUBJECT.match(line))


# THE THREE THAT FAILED, KEPT RATHER THAN DELETED — `naive_mask`'s arrangement one detector
# along.  `selftest_30bd.py` runs them on planted strings and `owners_937c.py` runs them over
# the whole record on every suite run, so the refutations are measurements and not sentences.
# The first is THE RULE THIS ONE REPLACES: a repair whose BEFORE is not printed beside its
# AFTER is an assertion, so the narrow rule ships and §6.4 reports both counts.

WALK_LINE_START = re.compile(r"^\s*(?:HEAD:\s*)?<sha>\s+\S")

WALK_ANYWHERE = re.compile(r"(?:^|\s)<sha>[:,]?\s+\S")

# A conventional-commit prefix: `instrument: `, `census+repair: `.  Reads as decisive until
# it is run — `unmutated: 0   mutated: 20`, `verdicts: wall=CONCURRENT` and
# `species_repair_a4ef: \`set -e\` appears once` have the same shape and are not subjects.
# A closed vocabulary of commit types would separate them today and rot silently tomorrow,
# which is this detector's own defect one level in: this estate's log carries `refresh`,
# `measure`, `declare`, `amend`, `land`, `discharge`, `owners`, `scope` and `census+repair`,
# and the set is open by construction.
WALK_BARE_SUBJECT = re.compile(r"^\s*[a-z][a-z0-9_]*(?:[+/][a-z0-9_]+)*:\s+\S")


def walk_line_start(line):
    """THE RULE mg-aff1 REPLACED — a masked sha at line start.  For the controls only."""
    return bool(WALK_LINE_START.match(line))


def walk_anywhere(line):
    """THE OBVIOUS WIDENING, refuted on the record.  For the controls only."""
    return bool(WALK_ANYWHERE.search(line))


def walk_bare_subject(line):
    """THE REMAINING SHAPE, undecidable from the line.  For the controls only."""
    return bool(WALK_BARE_SUBJECT.match(line))


# ======================================================================================
# THE OUT-OF-FAMILY COLUMN'S OWN POWER — A CONTROL THAT HAS NEVER FIRED IS A CLAIM (mg-cda7)
# ======================================================================================
#
# WHAT mg-aff1 SHIPPED AND WHAT IT LEFT.  The widening above went 10 hits -> 18 and reported
# two numbers, not one: ALL 8 GAINED IN-FAMILY, and THE OUT COLUMN DID NOT MOVE.  That is
# the right pair to print — 10 -> 18 alone is equally consistent with `found eight more of
# the thing` and `started matching a neighbouring thing`.  What it does not establish is
# THAT THE PAIR IS HARD TO PRODUCE.  mg-aff1's own carry-forward says so in as many words:
# is the OUT column sensitive enough to have caught a bad widening?
#
# THE COLUMN HAS POWER AND IT IS MEASURED, NOT ASSERTED.  `owners_937c.py` §6b runs the
# battery below over every quoted line in the record.  Of the candidates that gain any line
# at all, EVERY ONE moves the OUT column — the refutation of `anywhere` was not luck.
#
# AND THE COLUMN HAS A BLIND SPOT, WHICH IS STRUCTURAL AND NOT A TUNING.  The in/out split
# is a PROXY over PATHS: a line is in-family because the row it sits in was read and filed
# HISTORY-WALK, not because anybody looked at the line.  So a widening confined to lines
# INSIDE those rows moves the OUT column by exactly zero however wrong it is, and §6b prints
# how much room that leaves.  Two of the planted widenings below are in that room: `finding
# sha` and `predicted row` each gain lines, gain them ALL IN-FAMILY, and leave OUT where it
# was — mg-aff1's exact signature, on rules that are not walk detectors at all.
#
# SO `OUT UNMOVED` IS NECESSARY AND NOT SUFFICIENT, and the third column is what closes it:
# OWNERS.json's `walk_lines` carries a hand verdict for EVERY quoted line inside a
# HISTORY-WALK row, and a widening is graded on how many NOT-WALK lines it gains.  That is
# the same remedy mg-937c gave the 150 — read them one at a time and put the reading in a
# file the arm grades against the record — one level in, at the LINE instead of the ROW.
# What it does not do is decide whether a reading is RIGHT: nothing here checks that, the
# same declaration this directory already makes about `cause`, and §6b says it plainly.

import hashlib                                                     # noqa: E402


def line_key(text):
    """A stable identity for one quoted line: 12 hex of sha256 over its stripped text.

    Keyed by DIGEST rather than by text because the record's lines run to 900 characters and
    a hand file is unreadable at that width; the entry carries an excerpt beside the digest
    so a reader still sees what was read.  Keyed on the MASKED line, which is what the record
    stores, so the key is a function of the frozen sweep and not of any tree.
    """
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()[:12]


# THE BATTERY.  Every rule is kept here rather than written inline in the arm, for the reason
# mg-aff1 moved the detector out of report.py: a rule nothing can plant a world against is a
# rule nobody can bound.  Four are the versions of the detector that have been written (the
# shipped one, the one it replaced, and the two refuted); the rest are CANDIDATES — some are
# widenings a successor might plausibly reach for, and some are bad on purpose.  They are in
# one list so that §6b grades them by the SAME two columns and nothing is graded by hand.
#
# `bad` is this file's own claim about the rule and is NOT what the arm reports on: the arm
# reports the columns and lets them disagree with it.  A field that could not disagree would
# be a label, not a measurement.
CANDIDATE_WIDENINGS = [
    ("C1", "any label character, same tail", False,
     r"^(?:HEAD:\s*)?.{0,16}<sha>[:,]?\s+\S"),
    ("C2", "drop the trailing `\\s+\\S`", False,
     r"^(?:HEAD:\s*)?[A-Za-z ]{0,16}<sha>"),
    ("C3", "let the label carry punctuation", False,
     r"^(?:HEAD:\s*)?[\w .*+()\[\]-]{0,16}<sha>[:,]?\s+\S"),
    ("C4", "window 40 — the top of the plateau", False,
     r"^(?:HEAD:\s*)?[A-Za-z ]{0,40}<sha>[:,]?\s+\S"),
    ("C5", "any `... subject :` label", False,
     r"^\s*\S.{0,20}subject\s*:\s*\S"),
    ("C6", "two shas on the line", False,
     r"<sha>\s+.*<sha>"),
    ("C7", "a masked date on the line", False,
     r"<date>"),
    ("C8", "a sha followed by a digit column", False,
     r"^(?:HEAD:\s*)?[A-Za-z ]{0,16}<sha>\s+\d"),
    # --- bad on purpose.  B1 and B2 are the two that the OUT column cannot see. ---------
    ("B1", "a `FINDING: <sha>` sentence", True,
     r"^\s*(?:\*\*\* )?FINDING: <sha>"),
    ("B2", "a `P<n> predicted / got` row", True,
     r"^\s*P\d+[a-z]?\s+predicted\b"),
    ("B3", "an `A<n> TOTAL BAD:` counter", True,
     r"^\s*A\d+ TOTAL BAD:"),
    ("B4", "the bare-subject rule, case-blind", True,
     r"(?i)^\s*[a-z][a-z0-9_]*(?:[+/][a-z0-9_]+)*:\s+\S"),
    ("B5", "any line quoting a sha at all", True,
     r"<sha>"),
]


def candidate(pattern):
    """A candidate widening as a predicate.  A widening cannot LOSE hits — it is the shipped
    rule OR the candidate — so the columns below are deltas of a superset and never a swap.
    That is a property of how the battery is composed, and it is why `gained` is subtraction.
    """
    rx = re.compile(pattern)
    return lambda line: bool(is_walk_line(line) or rx.search(line))


# ======================================================================================
# THE VERDICT
# ======================================================================================

IDENTICAL = "IDENTICAL"
BENIGN_F771 = "BENIGN/timing+path"
BENIGN_ADDR = "BENIGN/address+asof"
VERDICT_TOKEN = "VERDICT-STALE/token"
VERDICT_NUMBER = "VERDICT-STALE/number"
NON_VERDICT = "NON-VERDICT"

VERDICT_STALE = (VERDICT_TOKEN, VERDICT_NUMBER)
BENIGN = (IDENTICAL, BENIGN_F771, BENIGN_ADDR)


def classify(committed, worktree, mask=None):
    """(bucket, detail) for one committed transcript against its regeneration at HEAD."""
    f = lib_f771.verdict_for(committed, worktree)
    if f == "AGREES":
        return IDENTICAL, ""
    if f == "NOISE":
        return BENIGN_F771, "mg-f771 N1/N2/N3"
    a, b = canonical(committed, mask), canonical(worktree, mask)
    if a == b or lib_f771.texts_equivalent(a, b):
        return BENIGN_ADDR, "A1 line addresses / A2 sha, date, clock"
    va, vb = verdict_lines(a), verdict_lines(b)
    if va != vb:
        ta, tb = token_multiset(a), token_multiset(b)
        if ta != tb:
            return VERDICT_TOKEN, _token_delta(ta, tb)
        return VERDICT_NUMBER, "same tokens, a number under one of them moved"
    return NON_VERDICT, "differs outside every verdict line"


def _token_delta(ta, tb):
    """`MISSED -1, WIDER -3` — what the token multiset did, so the bucket is not asserted."""
    import collections
    ca, cb = collections.Counter(ta), collections.Counter(tb)
    parts = []
    for tok in sorted(set(ca) | set(cb)):
        d = cb[tok] - ca[tok]
        if d:
            parts.append("%s %+d" % (tok, d))
    return ", ".join(parts)


def verdict_line_diff(committed, worktree, limit=6):
    """The verdict lines that moved, as (mark, text), truncated with a stated remainder.

    Reported on the CANONICAL text — quoting the raw lines would put a worktree path into a
    tracked transcript and re-create a defect this estate has already paid for twice.
    """
    import difflib
    a, b = verdict_lines(canonical(committed)), verdict_lines(canonical(worktree))
    rows = []
    for ln in difflib.unified_diff(a, b, lineterm="", n=0):
        if ln.startswith(("---", "+++", "@@")):
            continue
        if ln[:1] in ("-", "+"):
            rows.append((ln[0], ln[1:].rstrip()))
    return rows[:limit], max(0, len(rows) - limit)
