#!/usr/bin/env python3
"""mg-30bd — THE CLASSIFIER FOR VERDICT-STALENESS, AND THE TOKEN SET IS THE INSTRUMENT.

WHY THIS EXISTS.  `code/asof_census_20ee` measures a population defined by `path:NNN`
ADDRESSES into files the instrument does not own.  mg-20ee said in as many words that "the
verdicts are not affected ... this must not be reported as a correctness defect", and that
sentence is TRUE OF THE POPULATION THAT CENSUS MEASURES AND FALSE OF THE CORPUS.  A
transcript can drift in its VERDICTS without any address moving, and such a transcript is
invisible to an address classifier BY CONSTRUCTION — it is not looking for that.

`code/species_extent_audit_6cb9` is the existence proof and it was found BY ACCIDENT, by
p6e4f, while pinning something else: its committed `out_a1_bothways.txt` says
`A1 TOTAL BAD: 1` with a `*** MISSED ***` row and two `*** EXTENT WIDER ***` rows; the same
script at HEAD today says `A1 TOTAL BAD: 0` and those rows are gone.  6cb9 is NOT among
mg-20ee's 44 candidates, so it sits outside the corrected population of 32 entirely.

A stale ADDRESS relocates a reader wrongly.  A stale VERDICT says the corpus measured
something it no longer measures — and it reads as a finding.  This module measures the
second class.  IT REPAIRS NOTHING: a verdict that has moved is a finding about the corpus and
needs an owner per instance, not a batch repair.

------------------------------------------------------------------------------------------
THE CLASSIFICATION, IN ORDER.  Each step is a REFINEMENT of the one before, and the first
two are BORROWED rather than re-spelled, because a second definition of "benign" is a second
place for the definition to drift.

  0  IDENTICAL          the committed bytes and the regenerated bytes are equal.
  1  BENIGN/f771        `lib_f771.verdict_for` says NOISE — i.e. the difference is entirely
                        inside mg-f771's declared N1 (an absolute path to a checkout of this
                        repository) and N2 (decimal seconds), under N3's prefix rule.  This
                        is the TIMING family and the CHECKOUT-PATH family, and it is the
                        gate's own definition, imported and not re-implemented.
  2  BENIGN/address     under A1 (a `file.ext:NNN` or `dir/file:NNN` line address) and A2
                        (a git sha, an ISO date, a clock time) the two texts become
                        equivalent.  This is mg-c824/mg-20ee's ADDRESS family and the
                        AS-OF-BLOCK family.
  3  VERDICT-STALE      the two texts differ in their VERDICT LINES (below).  THE HEADLINE.
  4  NON-VERDICT        they differ, but not in any verdict line.  Corpus-size counts land
                        here, and so does everything else this instrument has no name for.

WHY CORPUS-SIZE IS NOT MASKED, THOUGH THE TICKET NAMES IT A BENIGN FAMILY.  Masking it means
masking INTEGERS, and `A1 TOTAL BAD: 1 -> 0` is an integer.  A mask wide enough to eat
"530 markdown file(s) -> 531" and narrow enough to spare "TOTAL BAD: 1 -> 0" is a mask about
nouns, i.e. a list of the corpus nouns somebody has already looked at — mg-f771's own
warning about a wider normaliser being "an unfalsifiable escape hatch" applies exactly.  So
corpus-size is NOT proven benign here; it falls into bucket 4 and is COUNTED there.  Nothing
in the headline depends on that choice, because the headline is defined by MOVEMENT IN
VERDICT LINES and not by what is left over.

------------------------------------------------------------------------------------------
THE TOKEN SET.  `TOKENS` below is the instrument and it must be quotable, so it is a
hand-typed literal and not a regex over "words that look like verdicts".  A line is a
VERDICT LINE iff, after normalisation, it contains at least one token as a whole word.

Each token is ALL-CAPS.  That is a rule and not an accident: this corpus writes its graded
outcomes in capitals (`*** MISSED ***`, `VERDICT: RED`, `TOTAL BAD: 1`, `CAUGHT`, `HELD`)
and writes its prose in sentence case, so the case requirement is most of the selectivity.
The tokens were chosen by reading the ALL-CAPS frequency table over all 1051 tracked
transcripts at HEAD (the derivation is in README §2) and keeping the words that name a
GRADED OUTCOME or LABEL ONE, then dropping the ones that are only ever prose emphasis
(`THE`, `AND`, `NOT`, `THIS`, `EVERY`, ...).

WHAT THE CHOICE COSTS, STATED RATHER THAN DISCOVERED:
  * OVER-INCLUSION.  A corpus-size count that happens to sit on a line carrying a token
    ("PASS -- 530 file(s)") is graded VERDICT-STALE by this instrument.  That is why the
    verdict-stale bucket is SPLIT into TOKEN-MOVE (a token appeared, vanished or changed)
    and NUMBER-ON-A-VERDICT-LINE (the tokens are the same multiset and a number under one
    moved).  Both are reported; only the first is the strong claim.
  * UNDER-INCLUSION.  A verdict stated in a word not on the list, or in lower case, is
    invisible here.  That is a blind spot of the TOKEN SET, and it is distinct from the
    blind spot of the METHOD (README §5).
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

# mg-f771's normaliser is IMPORTED, not copied.  Its N1/N2/N3 are the gate's own definition
# of "not a function of repo state", and this instrument's bucket 1 must be that definition
# rather than a second one that can drift away from it.
sys.path.insert(0, os.path.join(ROOT, "code", "gate_fixed_point_f771"))
import lib_f771                                                    # noqa: E402


# ======================================================================================
# A1/A2 — the ADDRESS and AS-OF-BLOCK masks.  Applied ONLY after mg-f771 has already said
# DISAGREES, so they can never make the gate's own verdict looser than the gate's.
# ======================================================================================

# A1.  A LINE ADDRESS, and the thing in front of the colon must LOOK LIKE A PATH — it must
# carry a dot-extension or a slash.  `build.sh:342`, `STATE.md:210`, `code/a/b.py:17` are
# addresses; `TOTAL BAD:1` is not, and world W12 holds that boundary.  The first version of
# this regex was `(?<=[\w./-]):\d+\b`, which ate the second one.
ADDRESS = re.compile(r"\b((?:[\w.-]*/)*[\w-]+\.[A-Za-z][\w]{0,5}|(?:[\w.-]+/)+[\w.-]+):\d+\b")

# A2.  The as-of block: a git sha, an ISO date, a clock time.  A sha is 7-40 hex characters
# as a whole word; the length floor is 7 because this repo quotes short shas.
SHA = re.compile(r"\b[0-9a-f]{7,40}\b")
DATE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
CLOCK = re.compile(r"\b\d{1,2}:\d{2}(?::\d{2})?\b")


def mask_address_and_asof(text):
    """A1 + A2.  Pure string -> string."""
    text = ADDRESS.sub(lambda m: m.group(1) + ":<L>", text)
    text = DATE.sub("<date>", text)
    text = CLOCK.sub("<clock>", text)
    text = SHA.sub("<sha>", text)
    return text


# THE ONE THAT FAILED, KEPT RATHER THAN DELETED.  This was the first `ADDRESS`, and it eats
# `TOTAL BAD:1` — i.e. it turns the exact number this ticket is about into a benign address
# move.  `selftest_30bd.py` re-runs the classification under it every time the suite runs, so
# the failure is a measurement on the record and not a sentence in a README.
NAIVE_ADDRESS = re.compile(r"(?<=[\w./-]):\d+\b")


def naive_mask(text):
    """A1 as first written, with A2 unchanged, for the selftest's demonstration only."""
    text = NAIVE_ADDRESS.sub(":<L>", text)
    text = DATE.sub("<date>", text)
    text = CLOCK.sub("<clock>", text)
    text = SHA.sub("<sha>", text)
    return text


# ======================================================================================
# THE TOKEN SET
# ======================================================================================

TOKENS = (
    # graded outcomes
    "AGREES", "BAD", "BROKEN", "CAUGHT", "CLEAN", "CONFIRMED", "DIFFER", "DIFFERS",
    "DISAGREES", "FAIL", "FAILED", "FAILS", "FALSE", "FIRED", "FIRES", "GREEN", "HELD",
    "HIT", "HOLDS", "LAUNDERED", "MISS", "MISSED", "MISSING", "NARROWER", "NOISE",
    "OVERSTATES", "PASS", "PASSED", "RED", "REFUSED", "REFUTED", "REPRODUCES", "SILENT",
    "SLACK", "TRUE", "UNDERSTATES", "UNFALSIFIABLE", "UNMEASURED", "WIDER", "WRONG",
    # the labels a graded outcome is written under
    "FINDING", "FINDINGS", "VERDICT", "VERDICTS",
)

TOKEN_RE = re.compile(r"\b(?:%s)\b" % "|".join(sorted(TOKENS, key=len, reverse=True)))


def verdict_tokens(line):
    """The tokens on one line, in order of appearance (a list, so repeats count)."""
    return TOKEN_RE.findall(line)


def is_verdict_line(line):
    return bool(TOKEN_RE.search(line))


def canonical(text, mask=None):
    """N1+N2 (mg-f771) then A1+A2.  The text every comparison below is made on.

    `mask` is a parameter for ONE reason: `selftest_30bd.py` re-runs the classification under
    the ADDRESS REGEX THAT FAILED, so that failure stays on the record as a run rather than
    as a sentence in a README.  Nothing else passes it.
    """
    return (mask or mask_address_and_asof)(lib_f771.normalise(text))


def verdict_lines(text):
    """The canonical lines that carry at least one token, SORTED.

    Sorted, and not in file order, because a verdict that MOVED UP THE PAGE because an
    unrelated section grew is not a verdict that moved.  What is being measured is the SET
    OF GRADED STATEMENTS the transcript makes, not their layout.
    """
    return sorted(l.strip() for l in text.splitlines() if is_verdict_line(l))


def token_multiset(text):
    """Every token on every verdict line, as a sorted list — repeats included."""
    out = []
    for line in text.splitlines():
        if is_verdict_line(line):
            out.extend(verdict_tokens(line))
    return sorted(out)


# ======================================================================================
# THE DECLARATION — A TRANSCRIPT THAT SAYS IT CANNOT BE A FIXED POINT (mg-5491)
# ======================================================================================
#
# WHY THE CLASSIFIER NEEDED ONE.  `code/audit_c067/out_c1_rebase.txt` opens
#
#     A TRUE RECORD WHOSE OWN PRODUCER CAN NO LONGER SEE IT.  DO NOT RE-RUN THIS.
#
# and explains, in the file, that a re-run writes a FALSE 0 over a TRUE 5 because its
# producer pairs commits by subject inside `git log -n 40`.  mg-30bd's sweep re-ran it and
# graded the result, so the record carries the instrument's own blindness as a finding about
# the corpus.  `code/verdict_delivery_bf3f`'s four read the LIVE mg verdict and mail stream:
# no commit can make them reproduce, and re-running them measures a different afternoon.
# Those five are not findings about this repository at all, and reading them one at a time is
# how that was found.  THE GENERAL REPAIR IS NOT FIVE EXCLUSIONS, IT IS A NOTION: give the
# classifier a way for a transcript to say `I am not a fixed point, and here is why`, and the
# whole class stops being false positives instead of these five stopping.
#
# WHY IT IS NOT AN UNFALSIFIABLE ESCAPE HATCH, WHICH IS THE OBJECTION IT HAS TO SURVIVE —
# mg-f771's own warning about a wider normaliser, one instrument along.  Four things, and the
# third is the one that does the work:
#
#   1  IT IS A HAND-TYPED LITERAL, not a regex over "prose that sounds like a disclaimer".
#      `DO NOT RE-RUN THIS` in a sentence is not a declaration; this line is.
#   2  IT MUST BE IN THE FIRST `DECLARATION_WINDOW` LINES.  A declaration is made at the
#      HEAD of the file it is about.  The window is what stops a QUOTATION exempting the
#      transcript that quotes it — and this estate's instruments quote each other constantly,
#      including `report.py`, which prints this literal in its own §3b.
#   3  IT IS CHECKED IN BOTH DIRECTIONS.  A transcript declaring itself unable to reproduce,
#      WHICH THEN REPRODUCES BYTE-IDENTICALLY IN THE SWEEP, is a FALSE DECLARATION and
#      report.py §3b says so as a finding.  That is the same discipline mg-937c put on
#      `cause: RECORD-DISAGREES`: a hand field the record can contradict is a claim, and a
#      hand field it cannot is a laundry.
#   4  NOTHING IS HIDDEN.  Every declaration is COUNTED AND LISTED with the bucket it would
#      have carried, so the exemption class is exactly as visible as the stale class, and it
#      grows in public.
#
# WHAT IT STILL CANNOT CHECK, SAID HERE RATHER THAN DISCOVERED LATER: that the REASON is the
# right reason, or that no commit could have made the transcript reproduce.  A declaration is
# a judgement by the transcript's owner and this is an ADDRESS for it, not a proof of it.

DECLARATION = "NOT-A-FIXED-POINT:"

# 20 lines.  Long enough for a `#`-commented note header to carry the marker after a rule and
# a title, short enough that no listing, table or quotation in the body of a transcript can
# reach it.  Measured against the corpus rather than guessed: the five transcripts this
# repair covers carry theirs at lines 2-6.
DECLARATION_WINDOW = 20


def declaration(text):
    """The transcript's own declaration that it is not a fixed point, or None.

    Returns the REASON — whatever follows the marker on its line.  An empty reason comes
    back as `""` and is NOT honoured: report.py counts it MALFORMED and grades the
    transcript exactly as if the line were not there, because a marker with nothing after it
    is an exemption nobody signed.  The two are different answers and `None` is neither.
    """
    for line in text.split("\n")[:DECLARATION_WINDOW]:
        s = line.strip().lstrip("#").strip()
        if s.startswith(DECLARATION):
            return s[len(DECLARATION):].strip()
    return None


# ======================================================================================
# THE VERDICT
# ======================================================================================

IDENTICAL = "IDENTICAL"
BENIGN_F771 = "BENIGN/timing+path"
BENIGN_ADDR = "BENIGN/address+asof"
VERDICT_TOKEN = "VERDICT-STALE/token"
VERDICT_NUMBER = "VERDICT-STALE/number"
NON_VERDICT = "NON-VERDICT"

VERDICT_STALE = (VERDICT_TOKEN, VERDICT_NUMBER)
BENIGN = (IDENTICAL, BENIGN_F771, BENIGN_ADDR)


def classify(committed, worktree, mask=None):
    """(bucket, detail) for one committed transcript against its regeneration at HEAD."""
    f = lib_f771.verdict_for(committed, worktree)
    if f == "AGREES":
        return IDENTICAL, ""
    if f == "NOISE":
        return BENIGN_F771, "mg-f771 N1/N2/N3"
    a, b = canonical(committed, mask), canonical(worktree, mask)
    if a == b or lib_f771.texts_equivalent(a, b):
        return BENIGN_ADDR, "A1 line addresses / A2 sha, date, clock"
    va, vb = verdict_lines(a), verdict_lines(b)
    if va != vb:
        ta, tb = token_multiset(a), token_multiset(b)
        if ta != tb:
            return VERDICT_TOKEN, _token_delta(ta, tb)
        return VERDICT_NUMBER, "same tokens, a number under one of them moved"
    return NON_VERDICT, "differs outside every verdict line"


def _token_delta(ta, tb):
    """`MISSED -1, WIDER -3` — what the token multiset did, so the bucket is not asserted."""
    import collections
    ca, cb = collections.Counter(ta), collections.Counter(tb)
    parts = []
    for tok in sorted(set(ca) | set(cb)):
        d = cb[tok] - ca[tok]
        if d:
            parts.append("%s %+d" % (tok, d))
    return ", ".join(parts)


def verdict_line_diff(committed, worktree, limit=6):
    """The verdict lines that moved, as (mark, text), truncated with a stated remainder.

    Reported on the CANONICAL text — quoting the raw lines would put a worktree path into a
    tracked transcript and re-create a defect this estate has already paid for twice.
    """
    import difflib
    a, b = verdict_lines(canonical(committed)), verdict_lines(canonical(worktree))
    rows = []
    for ln in difflib.unified_diff(a, b, lineterm="", n=0):
        if ln.startswith(("---", "+++", "@@")):
            continue
        if ln[:1] in ("-", "+"):
            rows.append((ln[0], ln[1:].rstrip()))
    return rows[:limit], max(0, len(rows) - limit)
