#!/usr/bin/env python3
"""mg-f771 — DOES THE GATE HAVE A FIXED POINT?

A COMMITTED `out_*.txt` MUST NEVER BE ABLE TO DISAGREE WITH THE REPO IT DESCRIBES.  That is
the invariant this arm enforces, and it is enforced by the cheapest measurement available:
`./build.sh` has just rewritten every transcript its six suites own, so the tree itself now
holds both halves of the comparison.  This arm reads them.

  for every tracked `code/**/out_*.txt` that differs from its committed copy at HEAD:
      normalise both (lib_f771 N1, N2 — absolute checkout paths and decimal seconds)
      if the normalised forms still differ, the committed copy asserts something this
      tree contradicts.  RED.

WHY IT RUNS LAST AND WHY IT DEMANDS A HANDSHAKE.  Its subject is the side effect of a gate
run.  Run on its own it would compare each committed transcript against a worktree copy
nothing had refreshed, find them equal, and print a green that means "nobody has edited
these by hand" under a heading that says "the corpus agrees with itself" — a laundered
green in the file written to find them.  So `build.sh` sets BUILD_SH_RAN_THE_SUITES=1 and
this arm REFUSES (exit 2) without it.  Could-not-tell must not map onto nothing-wrong.

WHAT ITS GREEN DOES NOT MEAN, said here so it is not over-read.  It cannot check that a
transcript is TRUE — only that the committed bytes and the freshly generated bytes make the
same assertions.  If an instrument is wrong, it is wrong identically in both, and this arm
is silent.  The gate is on AGREEMENT, not on truth, the same split as mg-03cf's and
mg-602d's and for the same reason.

THE WATCHED CLASS IS TOTAL AND INCLUDES THIS ARM'S OWN TRANSCRIPT (mg-c15e).  It did not
used to.  The exemption was forced by a self-reference: this file was written AFTER the
measurement and its text named the disagreement set, so a red run's transcript was committed
alongside the refresh that makes the tree green and the next run graded it DISAGREES.  On the
record that oscillation cost 7 commits of `main` whose entire diff is this one file, and 16
of its 31 committed versions were RED (mg-585e).

THE PROPERTY IS NOT `ITS TEXT DEPENDS ON THE VERDICT`, and getting that right is what let the
exemption go.  This arm runs at tree T and its output is committed into T'; the repair that
produces T' is `commit the regenerated transcripts`; so the disagreement set at T' is EMPTY
BY DEFINITION OF THE REPAIR.  A transcript cannot record a quantity its own commit zeroes.
The old docstring rule here — "only the DISAGREES list, WHICH IS REPO STATE, is on stdout" —
therefore picked the wrong test: the right one is DOES THE REPAIR MOVE IT, and the two
disagree on exactly one item, which was the whole of §2.

SO §2 IS NOW THE RULE INVENTORY, and this file's stdout is a pure function of `lib_f771.py`'s
source: the constants the verdict is a function of, printed in full, and a digest of the six
functions that decide.  It is not constant — it moves when the normaliser moves — and that is
what the exemption's removal buys, which is this instrument's own stated main risk: an
operator who WIDENS the rule and does not re-run the gate is caught by the control they
widened.  WHAT IT COSTS IS ONE SENTENCE: the committed transcript stops being quotable for
`was the gate green`.  The file that opened this ticket was stale precisely BECAUSE the
quotable part was the verdict.

THE OUTCOME GOES TO THE EXIT STATUS AND TO STDERR, which is where the merge gate has always
read it and where README D4 already put this arm's other run-dependent state — how many
transcripts moved, and which were graded NOISE.  A REFUSAL AND A CRASH GO THERE TOO, and for
the same reason rather than for a new one: a traceback on stdout is a transcript whose text
is a function of the run, which is the defect this section exists to have removed.

ONE CLASS OF TRANSCRIPT IS GRADED AGAINST A PIN AND NOT AGAINST THIS TREE (mg-05c6).  A
transcript whose subject is the WHOLE corpus has no per-branch fixed point: it moves when
anybody's branch lands, so the invariant above made every branch a writer of one shared file
and two of them conflicted on it in one morning.  Such a transcript declares itself, prints a
digest of what it read, and is graded CORPUS — not red — when that digest moved.  Same digest
beside a moved text is still RED, and drift past a declared bound is STALE, which is red.  The
declared list, the reasoning and the cost are in `lib_f771.CORPUS_SCOPED`.

A SECOND LIMIT, and it is the one that costs.  `bytes 138325` in
`code/state_ratchet_e331/out_ratchet.txt` is STATE.md's size, which IS a function of repo
state — so a branch that edits STATE.md and does not carry a refreshed transcript goes RED
here.  That is not a side effect to be tuned out; it is the invariant applied to the case
that made the invariant worth having, and it is the cost mg-f771 named in advance as
"the current dirty-tree behaviour made mandatory instead of accidental".  README §5.

EXITS 0 if the corpus agrees with itself, 1 if a committed transcript disagrees, 2 if this
arm could not reach a decision.
"""

import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_f771 as L  # noqa: E402

W = 92

err = sys.stderr


def rule(ch="-"):
    print(ch * W)


def transcript():
    """EVERYTHING THIS ARM WRITES TO STDOUT, and it is a function of `lib_f771.py` and of
    nothing else — no tree, no clock, no verdict.  Written once and called from the happy
    path, from the refusal and from the crash handler, because a transcript that is the
    fixed point only when the run went well is not a fixed point."""
    print("=" * W)
    print("mg-f771  THE GATE'S OWN FIXED POINT — what is watched, and by what rule it is judged")
    print("=" * W)
    print()

    print("§1  THE WATCHED CLASS")
    rule()
    print("  every tracked file under code/ named out_*.txt, compared against HEAD.")
    print("  Nothing is regenerated by this arm; it only reads.  A transcript no suite")
    print("  rewrites is never modified and therefore never appears in the changed set —")
    print("  which is how mg-c824's out_a4_census.txt stays outside this control by")
    print("  construction rather than by exemption.")
    print()
    print("  NOTHING IS EXEMPT.  THE CLASS IS TOTAL, AND THIS ARM'S OWN TRANSCRIPT IS IN IT.")
    print("  It was the one exclusion until mg-c15e, because its text named the disagreement")
    print("  set and that set is emptied by the very commit that carries the file — so each")
    print("  run's fix was the next run's disagreement, 16 of 31 committed versions RED and 7")
    print("  commits of main existing for nothing else.  The exclusion is gone rather than")
    print("  narrowed: §2 no longer records the outcome, so there is nothing left to oscillate")
    print("  and no file that needs forgiving.  Worlds E1-E8 in g1 hold the class to that.")
    print()
    print("  HOW MANY MOVED, WHICH WERE GRADED NOISE, AND WHAT DISAGREED ARE ON STDERR AND NOT")
    print("  HERE.  That set is not a fixed point of this arm's own commit, and an earlier")
    print("  draft that printed it made THIS ARM fail its own invariant on its second run.")
    print("  The build log keeps stderr and no tracked file does.  README D4.")
    print()
    print("  AND %d TRANSCRIPT(S) ARE GRADED AGAINST A CORPUS PIN RATHER THAN AGAINST THIS"
          % len(L.CORPUS_SCOPED))
    print("  TREE, because their subject IS the tree and so they have no per-branch fixed")
    print("  point.  The list is declared, not a shape a transcript can grow into:")
    for rel in sorted(L.CORPUS_SCOPED):
        print("      %s" % rel)
    print("  A pin that moved says the corpus moved and the difference is not this branch's.")
    print("  The SAME pin beside a moved text says the instrument changed its answer on an")
    print("  unchanged corpus, and is RED.  Drift past %d directories is STALE, also red."
          % L.CORPUS_DRIFT_LIMIT)
    print("  HOW FAR EACH HAS DRIFTED IS ON STDERR, for the reason the paragraph above gives:")
    print("  it moves with every landing and this file must not.  lib_f771.CORPUS_SCOPED.")
    print()
    for line in L.rule_inventory(L.lib_source()):
        print(line)


def report_disagreements(bad, graded):
    """The disagreement set, on STDERR.  It is the half of this arm's answer that its own
    commit destroys, and it is shown rather than merely counted for the reason it always was:
    a control that asserts a disagreement without quoting one is not readable."""
    verdicts = dict(graded)
    err.write("mg-f771 g0: THE DISAGREEMENTS, SHOWN.  Lines are quoted AFTER normalisation, "
              "so nothing here can smuggle a worktree path into a tracked file.  `-` is the "
              "committed copy, `+` is this tree.\n")
    for rel in bad:
        err.write("mg-f771 g0:   %-9s %s\n" % (verdicts[rel], rel))
        if verdicts[rel] == "STALE":
            pin_c = L.corpus_pin(L.committed_text(rel))
            pin_w = L.corpus_pin(L.worktree_text(rel))
            err.write("mg-f771 g0:     a corpus-scoped transcript whose population drifted "
                      "%d -> %d, past the declared bound of %d.  This branch did not cause "
                      "the drift and the arbitrariness of who pays is the declared cost of "
                      "the bound — but a pinned report nobody ever refreshes is the defect "
                      "this whole control exists to find.\n"
                      % (pin_c[1], pin_w[1], L.CORPUS_DRIFT_LIMIT))
        rows, dropped = L.first_disagreement(L.committed_text(rel), L.worktree_text(rel))
        for mark, text in rows:
            if mark == "@":
                err.write("mg-f771 g0:     %s\n" % text)
            else:
                err.write("mg-f771 g0:     %s %s\n" % (mark, text.strip()[:80]))
        if dropped:
            err.write("mg-f771 g0:     ... %d further hunk line(s) not shown\n" % dropped)
    err.write("mg-f771 g0: THE REPAIR IS TO COMMIT THE REGENERATED FILES.  They are already "
              "in the worktree; ./build.sh wrote them.  This arm is not asking for a rerun.\n")


def main():
    t0 = time.time()
    transcript()

    if os.environ.get(L.FRESH_ENV) != "1":
        err.write(
            "mg-f771 g0: REFUSED — %s is not set.  This arm reads the side effect of a gate "
            "run: `./build.sh` rewrites the transcripts its suites own, and this arm asks "
            "whether the rewritten bytes still say what the COMMITTED bytes say.  Without a "
            "gate run there is nothing to compare and a green here would mean only 'nobody "
            "hand-edited these', under a heading that claims more.  Run `./build.sh`, which "
            "sets the variable, or set it by hand if you have just run the suites "
            "yourself.\n" % L.FRESH_ENV)
        return 2

    try:
        L.require_git()
        changed = L.changed_transcripts()
        graded = [(rel, L.verdict_for(L.committed_text(rel), L.worktree_text(rel), rel))
                  for rel in changed]
    except L.Refused as exc:
        err.write("mg-f771 g0: REFUSED — %s\n" % exc)
        return 2

    bad = [r for r, v in graded if v in L.RED_VERDICTS]
    noise = [r for r, v in graded if v == "NOISE"]
    corpus = [r for r, v in graded if v == "CORPUS"]

    # The jitter channel.  The build log keeps it; no tracked file does.
    err.write("mg-f771 g0: %d watched transcript(s) moved — %d red, %d NOISE, %d CORPUS\n"
              % (len(graded), len(bad), len(noise), len(corpus)))
    for rel, v in graded:
        err.write("mg-f771 g0:   %-9s %s\n" % (v, rel))
    if noise:
        err.write("mg-f771 g0: the NOISE ones moved but say the same thing.  Leaving them "
                  "modified is not a defect and committing them is not required.\n")
    for rel in corpus:
        pin_c = L.corpus_pin(L.committed_text(rel))
        pin_w = L.corpus_pin(L.worktree_text(rel))
        err.write("mg-f771 g0: %s is corpus-scoped; its pin moved %s -> %s and its population "
                  "%d -> %d (bound %d).  Restore it rather than committing it — the refresh "
                  "is owed by whoever trips the bound, not by this branch.\n"
                  % (rel, pin_c[0], pin_w[0], pin_c[1], pin_w[1], L.CORPUS_DRIFT_LIMIT))

    if bad:
        report_disagreements(bad, graded)
        err.write("mg-f771 g0: VERDICT: RED — %d committed transcript(s) disagree with this "
                  "tree.  %.2fs\n" % (len(bad), time.time() - t0))
        return 1

    err.write("mg-f771 g0: VERDICT: GREEN — 0 disagreements.  Every watched transcript that "
              "moved during this gate run moved only in the declared families that are not a "
              "function of THIS BRANCH's repo state.  %.2fs\n" % (time.time() - t0))
    return 0


if __name__ == "__main__":
    # A crash goes to STDERR and the transcript is still written, which is the opposite of
    # what this file did before mg-c15e and is the same rule applied to a case it had got
    # wrong.  The old arrangement printed the traceback to stdout so it would land in the
    # tracked file rather than only in the jitter channel — but the tracked file is now
    # INSIDE the watched class, so a traceback in it is a committed transcript that
    # disagrees with every tree that does not reproduce the crash.  `could not tell` is exit
    # 2 and it is never a silent green: stderr is in the build log and the status is what
    # the gate reads.
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except BaseException:                                   # noqa: BLE001 - deliberate
        import traceback
        err.write("mg-f771 g0: REFUSED — this arm crashed and therefore reached no verdict:\n")
        traceback.print_exc(file=err)
        sys.exit(2)
