#!/usr/bin/env python3
"""mg-f771 — DOES THE GATE HAVE A FIXED POINT?

A COMMITTED `out_*.txt` MUST NEVER BE ABLE TO DISAGREE WITH THE REPO IT DESCRIBES.  That is
the invariant this arm enforces, and it is enforced by the cheapest measurement available:
`./build.sh` has just rewritten every transcript its six suites own, so the tree itself now
holds both halves of the comparison.  This arm reads them.

  for every tracked `code/**/out_*.txt` that differs from its committed copy at HEAD:
      normalise both (lib_f771 N1, N2 — absolute checkout paths and decimal seconds)
      if the normalised forms still differ, the committed copy asserts something this
      tree contradicts.  RED.

WHY IT RUNS LAST AND WHY IT DEMANDS A HANDSHAKE.  Its subject is the side effect of a gate
run.  Run on its own it would compare each committed transcript against a worktree copy
nothing had refreshed, find them equal, and print a green that means "nobody has edited
these by hand" under a heading that says "the corpus agrees with itself" — a laundered
green in the file written to find them.  So `build.sh` sets BUILD_SH_RAN_THE_SUITES=1 and
this arm REFUSES (exit 2) without it.  Could-not-tell must not map onto nothing-wrong.

WHAT ITS GREEN DOES NOT MEAN, said here so it is not over-read.  It cannot check that a
transcript is TRUE — only that the committed bytes and the freshly generated bytes make the
same assertions.  If an instrument is wrong, it is wrong identically in both, and this arm
is silent.  The gate is on AGREEMENT, not on truth, the same split as mg-03cf's and
mg-602d's and for the same reason.

THIS TRANSCRIPT RECORDS ONLY WHAT IS A FUNCTION OF REPO STATE, AND THAT RULE WAS LEARNED THE
HARD WAY ON RUN 2 (README D4).  The first draft printed the whole changed set — how many
transcripts moved, and which ones were graded NOISE.  That set is NOT repo state: whether
`out_g1_values.txt` moves depends on whether its wall-clock timing happened to round to the
same tenth as last run.  So this arm's own transcript changed between two runs of an
unchanged tree, and the arm graded its own committed copy DISAGREES — the remedy failing the
invariant it enforces, on its second run, measured rather than anticipated.  The operational
detail is therefore written to STDERR, where the build log keeps it and no tracked file does.
Only the DISAGREES list, which is repo state, is on stdout.

ONE CLASS OF TRANSCRIPT IS GRADED AGAINST A PIN AND NOT AGAINST THIS TREE (mg-05c6).  A
transcript whose subject is the WHOLE corpus has no per-branch fixed point: it moves when
anybody's branch lands, so the invariant above made every branch a writer of one shared file
and two of them conflicted on it in one morning.  Such a transcript declares itself, prints a
digest of what it read, and is graded CORPUS — not red — when that digest moved.  Same digest
beside a moved text is still RED, and drift past a declared bound is STALE, which is red.  The
declared list, the reasoning and the cost are in `lib_f771.CORPUS_SCOPED`.

A SECOND LIMIT, and it is the one that costs.  `bytes 138325` in
`code/state_ratchet_e331/out_ratchet.txt` is STATE.md's size, which IS a function of repo
state — so a branch that edits STATE.md and does not carry a refreshed transcript goes RED
here.  That is not a side effect to be tuned out; it is the invariant applied to the case
that made the invariant worth having, and it is the cost mg-f771 named in advance as
"the current dirty-tree behaviour made mandatory instead of accidental".  README §5.

EXITS 0 if the corpus agrees with itself, 1 if a committed transcript disagrees, 2 if this
arm could not reach a decision.
"""

import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_f771 as L  # noqa: E402

W = 92


def rule(ch="-"):
    print(ch * W)


def main():
    t0 = time.time()
    print("=" * W)
    print("mg-f771  THE GATE'S OWN FIXED POINT — can a committed transcript disagree with the tree?")
    print("=" * W)
    print()

    if os.environ.get(L.FRESH_ENV) != "1":
        print("REFUSED — %s is not set." % L.FRESH_ENV)
        print()
        print("  This arm reads the side effect of a gate run: `./build.sh` rewrites the")
        print("  transcripts its suites own, and this arm asks whether the rewritten bytes")
        print("  still say what the COMMITTED bytes say.  Without a gate run there is nothing")
        print("  to compare and a green here would mean only 'nobody hand-edited these',")
        print("  under a heading that claims more.  Run `./build.sh`, which sets the variable,")
        print("  or set it by hand if you have just run the suites yourself.")
        return 2

    try:
        L.require_git()
        changed = L.changed_transcripts()
    except L.Refused as exc:
        print("REFUSED — %s" % exc)
        return 2

    print("§1  THE WATCHED CLASS")
    rule()
    print("  every tracked file under code/ named out_*.txt, compared against HEAD.")
    print("  Nothing is regenerated by this arm; it only reads.  A transcript no suite")
    print("  rewrites is never modified and therefore never appears below — which is how")
    print("  mg-c824's out_a4_census.txt stays outside this control by construction.")
    print()
    print("  ONE FILE IS EXEMPT AND IT IS THIS ARM'S OWN TRANSCRIPT, not this directory:")
    for rel in L.SELF_EXCLUDED:
        print("      %s" % rel)
    print("  It is written AFTER the measurement and its text depends on the verdict, so a")
    print("  red run's transcript is committed alongside the refresh that makes the tree")
    print("  green and the next run grades it DISAGREES — an innocent branch red for a")
    print("  non-reason.  Measured over five runs; the oscillation does not damp.  Worlds")
    print("  E1-E7 in g1 hold the exemption to one file.  out_g1_controls.txt IS watched.")
    print()
    print("  HOW MANY MOVED, AND WHICH ONES WERE GRADED NOISE, ARE ON STDERR AND NOT HERE.")
    print("  That set is not repo state — whether a transcript moves depends on whether its")
    print("  wall-clock timing rounded to the same tenth as last run — and putting it in a")
    print("  tracked file made THIS ARM fail its own invariant on its second run.  README D4.")
    print()
    print("  AND %d TRANSCRIPT(S) ARE GRADED AGAINST A CORPUS PIN RATHER THAN AGAINST THIS"
          % len(L.CORPUS_SCOPED))
    print("  TREE, because their subject IS the tree and so they have no per-branch fixed")
    print("  point.  The list is declared, not a shape a transcript can grow into:")
    for rel in sorted(L.CORPUS_SCOPED):
        print("      %s" % rel)
    print("  A pin that moved says the corpus moved and the difference is not this branch's.")
    print("  The SAME pin beside a moved text says the instrument changed its answer on an")
    print("  unchanged corpus, and is RED.  Drift past %d directories is STALE, also red."
          % L.CORPUS_DRIFT_LIMIT)
    print("  HOW FAR EACH HAS DRIFTED IS ON STDERR, for the reason the paragraph above gives:")
    print("  it moves with every landing and this file must not.  lib_f771.CORPUS_SCOPED.")
    print()

    graded = []
    try:
        for rel in changed:
            graded.append((rel, L.verdict_for(L.committed_text(rel),
                                              L.worktree_text(rel), rel)))
    except L.Refused as exc:
        print("REFUSED — %s" % exc)
        return 2

    bad = [r for r, v in graded if v in L.RED_VERDICTS]
    noise = [r for r, v in graded if v == "NOISE"]
    corpus = [r for r, v in graded if v == "CORPUS"]

    # The jitter channel.  The build log keeps it; no tracked file does.
    err = sys.stderr
    err.write("mg-f771 g0: %d watched transcript(s) moved — %d red, %d NOISE, %d CORPUS\n"
              % (len(graded), len(bad), len(noise), len(corpus)))
    for rel, v in graded:
        err.write("mg-f771 g0:   %-9s %s\n" % (v, rel))
    if noise:
        err.write("mg-f771 g0: the NOISE ones moved but say the same thing.  Leaving them "
                  "modified is not a defect and committing them is not required.\n")
    for rel in corpus:
        pin_c = L.corpus_pin(L.committed_text(rel))
        pin_w = L.corpus_pin(L.worktree_text(rel))
        err.write("mg-f771 g0: %s is corpus-scoped; its pin moved %s -> %s and its population "
                  "%d -> %d (bound %d).  Restore it rather than committing it — the refresh "
                  "is owed by whoever trips the bound, not by this branch.\n"
                  % (rel, pin_c[0], pin_w[0], pin_c[1], pin_w[1], L.CORPUS_DRIFT_LIMIT))

    if bad:
        print("§2  THE DISAGREEMENTS, SHOWN")
        rule()
        print("  Lines quoted after normalisation, so that this transcript cannot itself")
        print("  smuggle a worktree path into the corpus.")
        print("  `-` is the committed copy, `+` is this tree.")
        verdicts = dict(graded)
        for rel in bad:
            print()
            print("  %-9s %s" % (verdicts[rel], rel))
            if verdicts[rel] == "STALE":
                pin_c = L.corpus_pin(L.committed_text(rel))
                pin_w = L.corpus_pin(L.worktree_text(rel))
                print("    a corpus-scoped transcript whose population drifted %d -> %d, past"
                      % (pin_c[1], pin_w[1]))
                print("    the declared bound of %d.  This branch did not cause the drift and"
                      % L.CORPUS_DRIFT_LIMIT)
                print("    the arbitrariness of who pays is the declared cost of the bound —")
                print("    but a pinned report nobody ever refreshes is the defect this whole")
                print("    control exists to find.  lib_f771.CORPUS_SCOPED states the price.")
            rows, dropped = L.first_disagreement(
                L.committed_text(rel), L.worktree_text(rel))
            for mark, text in rows:
                if mark == "@":
                    print("    %s" % text)
                else:
                    print("    %s %s" % (mark, text.strip()[:80]))
            if dropped:
                print("    ... %d further hunk line(s) not shown" % dropped)
        print()
        print("  THE REPAIR IS TO COMMIT THE REGENERATED FILES.  They are already in the")
        print("  worktree; `./build.sh` wrote them.  This arm is not asking for a rerun.")
        print()
        print("VERDICT: RED — %d committed transcript(s) disagree with this tree.  %.2fs"
              % (len(bad), time.time() - t0))
        return 1

    print("§2  NO DISAGREEMENTS")
    rule()
    print("  Every watched transcript that moved during this gate run moved only in the")
    print("  declared families that are not a function of THIS BRANCH's repo state: the two")
    print("  normaliser families, or a corpus-scoped reading whose pin moved and whose drift")
    print("  is inside the bound.  No committed transcript asserts anything this tree")
    print("  contradicts that this branch is the author of.")
    print()
    print("VERDICT: GREEN — 0 disagreements.  %.2fs" % (time.time() - t0))
    return 0


if __name__ == "__main__":
    # A crash must land IN THE TRANSCRIPT and not only on stderr, because stderr is this
    # arm's jitter channel and is deliberately not tracked.  `could not tell` is exit 2.
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except BaseException:                                   # noqa: BLE001 - deliberate
        import traceback
        print()
        print("REFUSED — this arm crashed and therefore reached no verdict:")
        traceback.print_exc(file=sys.stdout)
        sys.exit(2)
