"""mg-0b07 p1 -- IS THE DECLARATION DERIVED, OR REGENERATED BY HAND?

The subject's OPEN 2 answer is that `kern5f9a.unit_removed` parses the tree
before and after each patch, so the declaration cannot disagree with the patch.
A derivation that is in fact regenerated by hand is the defect wearing the fix's
name, and this lineage has produced that substitution before.  Reading the code
does not settle it; the code could be right and the transcript hand-maintained,
or the function could be correct and unreached.

SO THE PATCH IS CHANGED AND THE DECLARATION IS READ, WITH NOTHING ELSE EDITED.
A runnable copy of the subject's instrument is made in a temporary tree, ONE
token of its mutation table is rewritten, and its own `d2_deletion.py` is run.
The declaration is taken out of its own stdout.  If it follows the patch without
anyone touching a declaration, it is computed; if it does not, it is written.

The unperturbed copy is run first, as the harness's own control.
"""

import ast
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kern0b07 import (                                          # noqa: E402
    BAR, INSTR, REPO, claim, declaration_line, finding, head,
    instrument_copy, report, run_instrument,
)

# The two perturbations, each ONE edit to the subject's mutation TABLE and none
# to any declaration.  They move the declaration in two different directions:
# W changes the SIZE and the label set, M changes the UNIT KIND and the
# FUNCTION.  A declaration that tracks both is a function of the patch.
W_OLD = '("AFTER-5", None, NEW_FILES, [NEW_SHAPE],'
W_NEW = '("AFTER-5", None, NEW_FILES, [NEW_SHAPE, NEW_DIAG],'

M_OLD = ("NEW_SIGNS = ('face_complex.py',\n"
         "             '            signs_read += 1\\n',\n"
         "             '            pass\\n')")
M_NEW = ("NEW_SIGNS = ('face_complex.py',\n"
         "             '    if m != len(B) or any(len(A[i]) != len(B[i]) "
         "for i in range(m)):\\n'\n"
         "             '        return frozenset([\"shape\"])\\n',\n"
         "             '    if any(len(A[i]) != len(B[i]) for i in range(m)):"
         "\\n'\n"
         "             '        return frozenset([\"shape\"])\\n')")


def declarations(text):
    return {t: declaration_line(text, t)
            for t in ("BEFORE-1", "BEFORE-2", "AFTER-1", "AFTER-2", "AFTER-3",
                      "AFTER-4", "AFTER-5", "AFTER-6", "R1", "R2", "R3")}


def main():
    print(BAR)
    print("mg-0b07 p1 -- the declaration: derived, or written and regenerated?")
    print(BAR)
    print("\nPREDICTIONS, registered before these runs (PREDICTIONS.md p1):")
    print("   p1.1  unperturbed copy       exit 0, AFTER-5's declaration "
          "unchanged from the in-place run")
    print("   p1.2  W: AFTER-5 widened      1 `return` -> 2 `return`, label set "
          "gains 'diagonal', d2 exit 1")
    print("   p1.3  M: AFTER-4 repointed    0/1/0 from `absorb_trace` -> 0/0/1 "
          "from `gate_violations`, d2 exit 1")
    print("   p1.5  no second statement of the size survives: `returns_removed` "
          "absent, no integer in MUTATIONS")
    print("   p1.6  d1, d3, d4 transcripts reproduce byte-identically\n")

    head("1.  THE CONTROL -- the instrument copied and NOT perturbed")
    print("A copy that answers differently from the original makes every row "
          "below\nunreadable, so the copy is run first with nothing changed.\n")
    _tmp0, dst0 = instrument_copy()
    out0, code0 = run_instrument(dst0)
    base_decl = declarations(out0)
    committed = open(os.path.join(INSTR, "out_d2_deletion.txt")).read()
    committed_decl = declarations(committed)
    same = [t for t in base_decl if base_decl[t] == committed_decl[t]]
    claim("the unperturbed copy runs the subject's own d2 to completion and "
          "exits %d, and its eleven printed declarations agree with the "
          "committed transcript's on %d of %d"
          % (code0, len(same), len(base_decl)),
          code0 == 0 and len(same) == len(base_decl),
          "the copy differing from the original -- a symlinked predicate "
          "directory, a `.git` pointer that does not resolve, or an instrument "
          "that reads something outside its own tree.  Any of those would make "
          "the perturbed runs below measure the harness instead of the subject",
          "exit %d; declarations agreeing: %d of %d; AFTER-5 reads %s"
          % (code0, len(same), len(base_decl), base_decl["AFTER-5"]))

    head("2.  W -- THE PATCH IS WIDENED, AND NOTHING ELSE IS TOUCHED")
    print("One token of the mutation table:\n")
    print("    %s\n -> %s\n" % (W_OLD, W_NEW))
    print("AFTER-5 now removes the `shape` return AND the `diagonal` return.  "
          "No sentence,\nno table entry and no declaration is edited.  If the "
          "declaration is computed it\nmust say two returns and name a second "
          "gate; if it was written, it goes on saying\nwhat it said.\n")
    _tmpw, dstw = instrument_copy([(W_OLD, W_NEW)])
    outw, codew = run_instrument(dstw)
    dw = declarations(outw)
    print("   before: %s" % base_decl["AFTER-5"])
    print("   after : %s" % dw["AFTER-5"])
    got_two = dw["AFTER-5"] is not None and "2 `return`" in dw["AFTER-5"]
    got_label = dw["AFTER-5"] is not None and "'diagonal'" in dw["AFTER-5"]
    claim("THE DECLARATION FOLLOWED THE PATCH: it goes from %r to %r and its "
          "label list gains 'diagonal', with no declaration edited anywhere"
          % ("1 `return`" if "1 `return`" in (base_decl["AFTER-5"] or "") else "?",
             "2 `return`" if got_two else "unchanged"),
          got_two and got_label,
          "the declaration being a stored sentence, or being regenerated by a "
          "hand that was not asked to run.  Under either, this line prints the "
          "OLD size for the NEW patch -- which is mg-9220's defect exactly, and "
          "the reason changing the patch is the only test that separates a "
          "derivation from a correction",
          "widened declaration: %s" % dw["AFTER-5"])
    others = [t for t in dw if t != "AFTER-5" and dw[t] != base_decl[t]]
    claim("and ONLY AFTER-5's declaration moved: %d of the other %d are "
          "byte-identical to the unperturbed run"
          % (len(dw) - 1 - len(others), len(dw) - 1),
          not others,
          "a declaration that is a function of something other than its own "
          "patch -- a global count, a file-level total, or a table index.  Any "
          "of those would move ten rows when one patch changed",
          "moved besides AFTER-5: %s" % (", ".join(others) or "none"))
    claim("and the subject's own at-most-one-return claim goes RED under the "
          "widening (d2 exit %d)" % codew, codew == 1,
          "the widened patch being tolerated -- which would mean the count "
          "that guards bundled deletions is not read.  This is the subject's "
          "check, exercised by this audit's mutation rather than by its own",
          "d2 exit %d; the specimen R3 is excluded by name, AFTER-5 is not"
          % codew)

    head("3.  M -- THE PATCH IS REPOINTED, AT ANOTHER UNIT IN ANOTHER FUNCTION")
    print("AFTER-4 removes a statement from `absorb_trace`.  Its patch is "
          "repointed at the\nFIRST CLAUSE of `gate_violations`'s shape guard -- "
          "a different unit KIND in a\ndifferent FUNCTION.  A declaration that "
          "tracks a size but not a kind would still\nsay 'one statement'.\n")
    _tmpm, dstm = instrument_copy([(M_OLD, M_NEW)])
    outm, codem = run_instrument(dstm)
    dm = declarations(outm)
    print("   before: %s" % base_decl["AFTER-4"])
    print("   after : %s" % dm["AFTER-4"])
    txt = dm["AFTER-4"] or ""
    kind_ok = "0 `return`, 0 other statement(s), 1 boolean clause(s)" in txt
    where_ok = "`gate_violations`" in txt and "`absorb_trace`" not in txt
    claim("THE DECLARATION FOLLOWED THE KIND AND THE PLACE: it goes from a "
          "statement in `absorb_trace` to %s, with no declaration edited"
          % ("a boolean clause in `gate_violations`" if kind_ok and where_ok
             else "something else"),
          kind_ok and where_ok,
          "the unit kind or the enclosing function being written beside the "
          "mutation rather than read out of the patch.  `where` is derived from "
          "the anchor's own position, so a mutation moved to another function "
          "reports the other function -- and this is that, run",
          "repointed declaration: %s" % txt)
    fin = [ln for ln in outm.split("\n")
           if "AFTER-4" in ln or "FINEST UNIT" in ln]
    finest = next((ln for ln in outm.split("\n")
                   if "AIMED AT: the counter" in ln), "")
    claim("and the FINEST UNIT sentence moved with it: %r"
          % (finest[finest.find("FINEST UNIT"):][:96] if finest else ""),
          "a CONDITION of 2 clause(s)" in finest,
          "`finest_unit` being keyed to the mutation rather than to the "
          "measured delta.  It is the sentence a reader uses to decide how far "
          "the evidence reaches, so a stale one is worse than none",
          "%d line(s) of AFTER-4 output inspected" % len(fin))
    claim("and the subject's own registered prediction for AFTER-4 goes RED "
          "under the repointing (d2 exit %d)" % codem, codem == 1,
          "the repointed mutation still matching AFTER-4's registered "
          "CHANGES/0 -- `gate_violations`'s shape guard is inert whole "
          "(mg-c4c8 F3), so a clause of it cannot move the artifact",
          "d2 exit %d" % codem)

    head("4.  IS THERE A SECOND, INDEPENDENT STATEMENT OF THE SIZE LEFT?")
    print("mg-9220 had two: the written sentence and `returns_removed`, a line "
          "heuristic.\nTwo statements of one number are two things that can "
          "disagree.  The subject says\nit removed the second; that is checked "
          "here rather than read.\n")
    d2src = open(os.path.join(INSTR, "d2_deletion.py")).read()
    kernsrc = open(os.path.join(INSTR, "kern5f9a.py")).read()
    heur = ("returns_removed" in d2src) or ("returns_removed" in kernsrc)
    tree = ast.parse(d2src)
    mut_ints = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == "MUTATIONS"
                for t in node.targets):
            mut_ints = [n.value for n in ast.walk(node)
                        if isinstance(n, ast.Constant)
                        and isinstance(n.value, int)
                        and not isinstance(n.value, bool)]
    claim("`returns_removed` is GONE from both the instrument and its kernel, "
          "and the MUTATIONS table contains %d integer literal(s) -- no "
          "mutation states a size" % len(mut_ints),
          not heur and not mut_ints,
          "a second statement of the same number reappearing anywhere: a "
          "line-counting heuristic, a size in the table, or a size in an `aim`. "
          " Any of them can disagree with the parse, and then a reader has two "
          "declarations and no way to choose",
          "returns_removed present: %s; integers in MUTATIONS: %s"
          % (heur, mut_ints or "none"))

    head("5.  DO THE COMMITTED TRANSCRIPTS REGENERATE FROM THE COMMITTED TREE?")
    print("A derivation that is regenerated by hand and a derivation that is "
          "computed look\nthe same in a file.  They differ in whether the file "
          "comes back.\n")
    print("SAID PLAINLY: out_d2_deletion.txt was regenerated in "
          "reconnaissance, BEFORE the\npredictions above were written.  Its row "
          "is reported with that provenance and is\nNOT scored as a prediction. "
          " d1, d3 and d4 were predicted first.\n")
    rows = []
    for script, out in (("d1_trace.py", "out_d1_trace.txt"),
                        ("d3_reintroduction.py", "out_d3_reintroduction.txt"),
                        ("d4_auditor_rerun.py", "out_d4_auditor_rerun.txt")):
        args = [sys.executable, script] + (["5"] if script == "d1_trace.py"
                                           else [])
        r = subprocess.run(args, cwd=INSTR, capture_output=True, text=True)
        got = r.stdout + r.stderr
        want = open(os.path.join(INSTR, out)).read()
        rows.append((out, got == want, r.returncode, len(got), len(want)))
        print("   %-28s %-16s exit %d  %d bytes regenerated, %d committed"
              % (out, "REPRODUCES" if got == want else "DIFFERS",
                 r.returncode, len(got), len(want)))
    # d2, re-run in reconnaissance and reported as such.
    r2 = subprocess.run([sys.executable, "d2_deletion.py"], cwd=INSTR,
                        capture_output=True, text=True)
    got2 = r2.stdout + r2.stderr
    want2 = open(os.path.join(INSTR, "out_d2_deletion.txt")).read()
    d2same = got2 == want2
    diffs = [(a, b) for a, b in zip(want2.split("\n"), got2.split("\n"))
             if a != b]
    print("   %-28s %-16s exit %d  %d bytes regenerated, %d committed"
          % ("out_d2_deletion.txt", "REPRODUCES" if d2same else "DIFFERS",
             r2.returncode, len(got2), len(want2)))
    claim("the three transcripts predicted to reproduce do: %d of 3"
          % sum(1 for _n, ok, _c, _a, _b in rows if ok),
          all(ok for _n, ok, _c, _a, _b in rows),
          "any edit to the predicate layer or to an instrument that is not "
          "followed by regenerating its transcript.  A committed transcript "
          "that does not come back is a record of a tree nobody can inspect",
          "; ".join("%s %s exit %d" % (n, "ok" if ok else "DIFFERS", c)
                    for n, ok, c, _a, _b in rows))
    if not d2same:
        finding("A1",
                "THE SUBJECT'S OWN CENTRAL TRANSCRIPT DOES NOT REGENERATE FROM "
                "THE TREE IT IS COMMITTED IN: out_d2_deletion.txt differs from "
                "a re-run at %d of %d line(s), and the line is a COUNT OF "
                "COMMITS -- 'of the 6 commits that ever touched "
                "face_complex.py' where the committed tree has 7, because the "
                "commit that publishes the transcript is itself the seventh."
                % (len(diffs), len(want2.split("\n"))),
                "The claim still HOLDS and d2 still exits %d, so nothing is "
                "hidden by it; what is wrong is the provenance.  This is the "
                "shape mg-821e's b534db7 published a post-commit measurement to "
                "fix in a sibling instrument, reintroduced here.  AND IT CANNOT "
                "BE FIXED BY REGENERATING ONCE: the number counts commits "
                "touching face_complex.py, so it moves again on the next one.  "
                "The differing line(s): %s"
                % (r2.returncode,
                   " || ".join("committed %r vs re-run %r"
                               % (a.strip()[:110], b.strip()[:110])
                               for a, b in diffs[:2])))
    return report()


if __name__ == "__main__":
    sys.exit(main())
