"""mg-0b07 p6 -- THE FLOOR ITEM: what this commit wrote OUTSIDE the thing it fixed.

Chosen by this audit because no list in the brief names it.

`0fb0e00` repairs a gate and an instrument.  It also regenerated FOUR derived
artifacts and edited TWO prior landing documents -- one of the four inside
ANOTHER AUDIT's directory.  A repair reaching into a directory whose whole
purpose is to be a record of what someone else measured is the one edit in this
lineage that can rewrite the evidence rather than add to it, and nothing in the
brief asks about it.

Three questions:

  1. does each regenerated control equal what ITS OWN GENERATOR produces on the
     committed tree?  Not "does the committed file equal the committed file" --
     each is rebuilt here from the artifact it is a function of;
  2. is the one file touched under an `*_audit_*` directory a generated control,
     or is it a transcript or a finding?
  3. what did the two prior landing documents lose?
"""

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kern0b07 import (                                          # noqa: E402
    BAR, FG, REPO, claim, finding, head, report, run_battery, scored_rows,
    source_at, tree_with,
)

COMMIT = "0fb0e00"
MARKERS = ("[PASS]", "[FAIL]", "[CANNOT FAIL]")


def retag(text, to):
    """Every scored row's marker replaced by `to`, and nothing else touched.

    Written here rather than imported: this file's whole job is to rebuild the
    committed controls from their own definitions, and borrowing the generator
    from the thing being checked would make each comparison `x == x`.
    """
    out = []
    for ln in text.split("\n"):
        s = ln.lstrip()
        hit = next((m for m in MARKERS if s.startswith(m)), None)
        out.append(ln[:len(ln) - len(s)] + to + s[len(hit):] if hit else ln)
    return "\n".join(out)


def main():
    print(BAR)
    print("mg-0b07 p6 -- the floor item: what this commit wrote outside itself")
    print(BAR)
    print("\nCHOSEN BY THIS AUDIT.  No list in the brief names it.\n")
    print("PREDICTIONS, registered before these runs (PREDICTIONS.md floor):")
    print("   f.1  4 of 4 regenerated controls equal their own generator's "
          "output")
    print("   f.2  exactly one file under an `*_audit_*` directory, and it is a "
          "generated control")
    print("   f.3  the two prior landing documents' diffs are ADDITIVE ONLY\n")

    head("1.  THE FOUR REGENERATED CONTROLS, REBUILT FROM THEIR GENERATORS")
    live_art, live_code = run_battery(tree_with("face_complex.py",
                                                source_at(None)))
    rows = []

    committed_art = open(os.path.join(FG, "controls_output.txt")).read()
    rows.append(("code/face_geometry/controls_output.txt",
                 live_art == committed_art,
                 "`controls.py 5`, run here", len(committed_art)))

    pc_fail = os.path.join(REPO, "code", "face_geometry_instr_5f9a",
                           "positive_control_all_fail.txt")
    want_fail = retag(committed_art, "[FAIL]")
    rows.append(("code/face_geometry_instr_5f9a/positive_control_all_fail.txt",
                 open(pc_fail).read() == want_fail,
                 "every scored row retagged [FAIL], rebuilt here",
                 len(want_fail)))

    pc_pass = os.path.join(REPO, "code", "face_geometry_audit_e7bc",
                           "pc_all_pass.txt")
    want_pass = retag(committed_art, "[PASS]")
    rows.append(("code/face_geometry_audit_e7bc/pc_all_pass.txt",
                 open(pc_pass).read() == want_pass,
                 "every scored row retagged [PASS], rebuilt here",
                 len(want_pass)))

    da45 = os.path.join(REPO, "code", "face_geometry_landing_da45")
    r = subprocess.run([sys.executable, "verify_landing.py"], cwd=da45,
                       capture_output=True, text=True)
    got = r.stdout + r.stderr
    want = open(os.path.join(da45, "out_verify.txt")).read()
    rows.append(("code/face_geometry_landing_da45/out_verify.txt", got == want,
                 "`verify_landing.py` re-run here, exit %d" % r.returncode,
                 len(want)))

    for name, ok, how, n in rows:
        print("   %-58s %-12s %6d bytes  (%s)"
              % (name.split("/", 1)[1], "MATCHES" if ok else "*** DIFFERS ***",
                 n, how))
    claim("each of the four regenerated controls equals what its own generator "
          "produces on the committed tree: %d of 4.  None of these comparisons "
          "is a file against itself"
          % sum(1 for _n, ok, _h, _b in rows if ok),
          all(ok for _n, ok, _h, _b in rows) and live_code == 0,
          "a control regenerated by hand, or regenerated from a tree other "
          "than this one.  A control that has drifted off its artifact is "
          "testing nothing about the artifact it sits beside -- and this "
          "commit regenerated four of them in one go, which is the moment that "
          "happens",
          "battery exit %d; %d scored rows in the artifact"
          % (live_code, len(scored_rows(committed_art))))

    head("2.  THE ONE FILE TOUCHED INSIDE ANOTHER AUDIT'S DIRECTORY")
    names = subprocess.run(["git", "show", "--name-only", "--format=",
                            COMMIT], cwd=REPO, capture_output=True,
                           text=True).stdout.split()
    in_audit = [n for n in names if "_audit_" in n]
    generated = [n for n in in_audit
                 if n.endswith(".txt") and "pc_all_pass" in n]
    transcripts = [n for n in in_audit
                   if n.endswith((".py", ".md")) or n.startswith("out_")
                   or "/out_" in n]
    for n in in_audit:
        print("   %s" % n)
    claim("this commit touches %d file under an `*_audit_*` directory: %s -- a "
          "GENERATED CONTROL, rebuilt above from the artifact it is a function "
          "of.  It touches %d audit transcript(s), script(s) or README(s)"
          % (len(in_audit), ", ".join(in_audit) or "none", len(transcripts)),
          len(in_audit) == 1 and len(generated) == 1 and not transcripts,
          "an audit's transcript, instrument or findings document being edited "
          "by the repair it audits.  That is the one edit in this lineage that "
          "rewrites evidence rather than adding to it, and it is the reason "
          "this item was chosen: a repair is allowed to move a generated "
          "control and is not allowed to move a record",
          "in audit directories: %s" % (", ".join(in_audit) or "none"))
    g1 = subprocess.run([sys.executable, "g1_positive_control.py"],
                        cwd=os.path.join(REPO, "code",
                                         "face_geometry_audit_e7bc"),
                        capture_output=True, text=True)
    claim("and mg-e7bc's own instrument, unmodified, still accepts the control "
          "this commit regenerated inside its directory: g1 exits %d"
          % g1.returncode,
          g1.returncode == 0,
          "the regeneration having produced something that audit's own check "
          "rejects -- which is what a hand-edited control looks like from "
          "inside the audit that owns it",
          "%s" % (g1.stdout.strip().split("\n")[-1] if g1.stdout else ""))

    head("3.  WHAT THE TWO PRIOR LANDING DOCUMENTS LOST")
    docs = ["docs/landing-mg-d0e2-vacuous-check.md",
            "docs/landing-mg-e7bc-granularity.md"]
    total_del = 0
    deleted_lines = []
    for d in docs:
        num = subprocess.run(["git", "diff", "--numstat",
                              "%s^" % COMMIT, COMMIT, "--", d], cwd=REPO,
                             capture_output=True, text=True).stdout.split()
        add, dele = int(num[0]), int(num[1])
        total_del += dele
        diff = subprocess.run(["git", "diff", "%s^" % COMMIT, COMMIT, "--", d],
                              cwd=REPO, capture_output=True, text=True).stdout
        gone = [ln[1:] for ln in diff.split("\n")
                if ln.startswith("-") and not ln.startswith("---")]
        deleted_lines += [(d, g) for g in gone]
        print("   %-46s +%-4d -%-4d" % (d.split("/")[-1], add, dele))
    for d, g in deleted_lines:
        print("       - %s" % g.strip()[:104])
    verdicts = [g for _d, g in deleted_lines
                if any(k in g for k in ("FINDING", "F1 ", "F2 ", "F3 ", "F4 ",
                                        "F5 ", "F6 ", "Verdict", "REFUTED",
                                        "OUTSTANDING"))]
    print("\n   PREDICTED: additive only.  OBSERVED: %d line(s) deleted.  "
          "THE PREDICTION IS A MISS\n   and is kept as written." % total_del)
    claim("no deleted line is a finding, a verdict or a disposition: %d of %d "
          "deleted lines are superseded FIGURES (byte count, claim count, "
          "runtime), each replaced by a line that carries the old value in a "
          "parenthetical" % (len(deleted_lines) - len(verdicts),
                             len(deleted_lines)),
          not verdicts,
          "a finding, a verdict or a refutation being edited out of a prior "
          "landing document by a later repair.  The figures are DERIVED "
          "quantities that moved because the artifact moved, and updating them "
          "in place is the treatment this repository gives derived numbers; "
          "the history is kept in the parentheticals rather than in the diff",
          "deleted: %d; of them findings/verdicts: %d"
          % (len(deleted_lines), len(verdicts)))
    finding("C1",
            "THE PREDICTION 'ADDITIVE ONLY' IS A MISS AND THE SUBSTANCE IS "
            "CLEAN: %d lines were deleted across the two prior landing "
            "documents, all of them stale DERIVED figures updated in place "
            "(23,684 -> 23,695 bytes; 72 -> 83 claims; 112 s -> 143 s), each "
            "keeping the superseded value in a parenthetical.  No finding, "
            "verdict or disposition was altered." % total_del,
            "Recorded as a finding of THIS AUDIT'S OWN PREDICTION rather than "
            "of the subject: the prediction was too strong.  It is kept "
            "because the distinction it forced -- between editing a derived "
            "figure and editing a record -- is the one that matters for the "
            "question, and because a prediction quietly relaxed after its run "
            "is not a prediction.")
    return report()


if __name__ == "__main__":
    sys.exit(main())
