#!/bin/sh
# mg-0b07: independent audit of mg-64b6 (`0fb0e00`) -- regenerate every transcript.
#
# Pure Python 3, no third-party packages.  Measured runtime 2026-07-31 on a 2024
# laptop: ~10 min.  Most of it is p1 and p5, which run the SUBJECT'S OWN
# `d2_deletion.py` six times (once unperturbed as a control, and five times with
# one token of its mutation table rewritten) at ~60 s each; the rest is ~40 full
# control batteries at ~2.1 s each.
#
# WHAT IT IS FOR.  mg-64b6 answers mg-c4c8's two open items: the third rung of
# the gate -> return -> clause regress, and a DECLARED UNIT that understated its
# own patch on 8 of 11.  Its answer to the second is that the declaration is now
# DERIVED -- parsed out of the tree before and after each patch.  A derivation
# that is in fact regenerated by hand looks identical in a file, so p1 CHANGES
# THE PATCH and reads what the declaration says, with nothing else edited.  Its
# answer to the first is that the condition has no boolean operator left, so
# there is no clause under the `return` for a fourth rung.  That is true, and p3
# asks the question the regress is actually about -- what is the finest unit
# whose PERTURBATION the battery can see -- and answers it by measurement.
#
# NOT `python3 x.py | tee out.txt`, and that is deliberate (mg-f922).  A
# pipeline's exit status in POSIX sh is the LAST command's, so `tee` succeeding
# would mask a verifier exiting 1 -- a committed transcript saying BROKEN under a
# run_all.sh that exited 0.  Here the status is captured and re-raised, so
# `set -e` is the whole failure protocol.
#
# CLAIMS vs FINDINGS.  A [BROKEN] claim means THIS audit is wrong and fails the
# run.  A [FINDING] means mg-64b6 is; it is printed and counted and does not.
#
# Nothing under ../face_geometry is written: every mutation goes to a copy in a
# temporary directory and every battery run captures stdout.
set -e
cd "$(dirname "$0")"

run() {
    out=$1
    shift
    set +e
    python3 "$@" > "$out" 2>&1
    status=$?
    set -e
    cat "$out"
    return $status
}

echo "== selftest: this audit's own primitives =="
run out_selftest_0b07.txt selftest_0b07.py

echo
echo "== p1: is the declaration DERIVED?  change the patch and read it =="
run out_p1_derived.txt p1_derived.py

echo
echo "== p2: the 8 of 11, re-measured, and the specimen's fidelity =="
run out_p2_units.txt p2_units.py

echo
echo "== p3: the grain regress -- where the floor actually is =="
run out_p3_grain.txt p3_grain.py

echo
echo "== p4: what mg-c4c8 confirmed -- unchanged, or quietly weaker? =="
run out_p4_confirmed.txt p4_confirmed.py

echo
echo "== p5: did the ENUMERATION happen, and is each item checked? =="
run out_p5_enumeration.txt p5_enumeration.py

echo
echo "== p6: THE FLOOR ITEM -- what this commit wrote outside itself =="
run out_p6_floor.txt p6_floor.py
