"""mg-d0e2 E1: THE DELETION TEST, on EVERY gate the explanation names.

mg-1c80 caught the second generation of this defect with one deletion: it
removed from the predicate the gate mg-da45's artifact called decisive and the
artifact regenerated BYTE-IDENTICALLY.  mg-5f9a was told to make that test bite,
and its commit reports running it on two gates.  `face_complex.ABSORB_GATES`
names FOUR, and the artifact's own sentences name all four.  This runs it on all
four, plus the sign counter the artifact says its claims actually rest on, plus
three mutations that are not deletions of a predicate gate at all (the order,
the exhaustive companion, the routing quantity).

BOTH DIRECTIONS ARE REPORTED.  "Deleted and identical" is not scored as a
failure here and must not be read as one: it is a fact about which gate the
bytes depend on, and for a gate the artifact never claimed was decisive it is
the correct outcome.  What would be a failure is an artifact SENTENCE that names
a gate as the reason while the bytes do not move when it goes.

Every prediction below was written before the corresponding run.
"""

import sys

from kernd0e2 import (DEL_DIAGONAL, DEL_DIAGONAL_FROM_VIOLATIONS,
                      DEL_MAGNITUDE, DEL_MAGNITUDE_FROM_VIOLATIONS,
                      DEL_PARITY, DEL_SHAPE, DEL_SIGNS_READ, FC,
                      INVERT_DIAGONAL_MOVES, SWAP_ORDER, report, run_battery)

BROKEN = 0


def claim(ok, text):
    global BROKEN
    if not ok:
        BROKEN += 1
    print("  [%s] %s" % ("OK    " if ok else "BROKEN", text))


print("== E1: the deletion test, every gate the explanation names ==")
print()
print("BASELINE -- the committed artifact, regenerated unmutated")
base, base_status = run_battery({}, "base")
committed = open("../face_geometry/controls_output.txt", "rb").read()
claim(base == committed,
      "controls.py reproduces its committed artifact byte for byte "
      "(%d bytes, exit %d); committed is %d bytes"
      % (len(base), base_status, len(committed)))
claim(base_status == 0, "the unmutated battery exits 0")
print()

# (label, edits_by_file, predicted_change, predicted_exit, note)
CASES = [
    ("delete gate 'shape'", {FC: DEL_SHAPE}, False, 0,
     "no pair in any population has a shape mismatch, so the gate never fires"),
    ("delete gate 'diagonal'", {FC: DEL_DIAGONAL}, True, 0,
     "294 of 297 violate both forced gates, so no ANSWER moves -- but the "
     "trace label the artifact prints does"),
    ("delete gate 'magnitude'", {FC: DEL_MAGNITUDE}, True, 1,
     "3 pairs in row I4 violate magnitude ALONE; their answers flip and a "
     "scored row fails"),
    ("delete gate 'parity'", {FC: DEL_PARITY}, True, 1,
     "the union-find-vs-brute-force instrument check should catch a predicate "
     "that can no longer reject"),
    ("stop counting signs_read", {FC: DEL_SIGNS_READ}, True, 0,
     "the count is what the rows now rest on, so it must be load-bearing on "
     "the bytes"),
    ("swap the two forced gates' order", {FC: SWAP_ORDER}, True, 0,
     "same answers, different trace -- the artifact says the split depends on "
     "the order, so it must move when the order does"),
    ("delete 'diagonal' from gate_violations", {FC: DEL_DIAGONAL_FROM_VIOLATIONS},
     True, 0,
     "the 'both forced gates violated' counts are printed, so they must move"),
    ("delete 'magnitude' from gate_violations", {FC: DEL_MAGNITUDE_FROM_VIOLATIONS},
     True, 0,
     "same, from the other side -- and row I4's 'the ONLY one violated' "
     "sentence is computed here"),
    ("invert diagonal_moves (the routing)", {FC: INVERT_DIAGONAL_MOVES}, True, 1,
     "the routing row scores the split, so inverting it must break a row"),
]

print("DELETION TEST -- predictions were registered before the runs")
results = {}
misses = []
for label, edits, pred_change, pred_exit, note in CASES:
    out, status = run_battery(edits, label.replace(" ", "_")[:20])
    ok, changed = report(label, base, out, status, pred_change, pred_exit)
    results[label] = (out, status, changed)
    if not ok:
        misses.append((label, changed, status, pred_change, pred_exit))
    print("       %s" % note)

print()
print("PREDICTION SCORE -- %d of %d matched" % (len(CASES) - len(misses), len(CASES)))
for label, changed, status, pc, pe in misses:
    print("  MISS: %-36s observed %s/exit %d, predicted %s/exit %d"
          % (label, "changed" if changed else "identical", status,
             "changed" if pc else "identical", pe))

print()
print("WHICH LINES MOVED, for each mutation that changed the artifact")
base_lines = base.decode().splitlines()
for label, edits, _pc, _pe, _n in CASES:
    out, status, changed = results[label]
    if not changed:
        print("  %-36s no line moved" % label)
        continue
    out_lines = out.decode().splitlines()
    if len(out_lines) != len(base_lines):
        print("  %-36s LINE COUNT MOVED %d -> %d"
              % (label, len(base_lines), len(out_lines)))
        continue
    moved = [i for i in range(len(base_lines))
             if base_lines[i] != out_lines[i]]
    tags = []
    for i in moved:
        s = base_lines[i].strip()
        tags.append(s.split("--")[0].strip()[:52] or s[:52])
    print("  %-36s %d line(s) moved" % (label, len(moved)))
    for t in tags:
        print("        - %s" % t)

print()
print("SCORED ROWS -- does any deletion change a LABEL, not just a number?")
def labels(b):
    out = []
    for ln in b.decode().splitlines():
        s = ln.strip()
        if s.startswith("[PASS]") or s.startswith("[FAIL]") \
           or s.startswith("[CANNOT FAIL]"):
            out.append(s.split("]")[0] + "]")
    return out

base_labels = labels(base)
claim(len(base_labels) == 41,
      "the unmutated battery scores %d rows -- lines whose marker STARTS the "
      "line.  mg-5f9a publishes 43, which counts two 'measured, not scored' "
      "bullets that mention [CANNOT FAIL] in prose; see E3" % len(base_labels))
for label, edits, _pc, _pe, _n in CASES:
    out, status, changed = results[label]
    ls = labels(out)
    same = ls == base_labels
    nfail = ls.count("[FAIL]")
    print("  %-36s %d rows, %d FAIL, labels %s"
          % (label, len(ls), nfail,
             "UNCHANGED" if same else "MOVED"))

print()
print("E1 claims broken: %d" % BROKEN)
sys.exit(1 if BROKEN else 0)
