"""Independent rebuild of the machinery mg-a3d4 uses.

Written from the mathematical definitions, NOT from code/hodge_leverage/ or
code/face_geometry/.  Nothing in this file imports either of them; the only
shared object is the mathematics.

Deliberate route differences from the audited implementation:

  * posets are enumerated by ELEMENT EXTENSION (add a new element with a
    down-ideal and an up-filter), not by the mg-276d instrument, and
    canonicalised by colour refinement + within-class permutation search.
    A000112 = 1,1,2,5,16,63,318 is the check.
  * linear extensions are generated by a minimal-element recursion on the
    ORDER, and a facet is read off as the chain of prefix sets -- the audited
    code goes through `le_to_facet`.
  * ideals are enumerated as antichain-free down-closed subsets by direct
    down-closure test over all 2^n subsets, not by lattice construction.
  * the face complex is the order complex of the proper part of J(P), built by
    chain extension over ideals.
"""

from fractions import Fraction
from itertools import permutations


# --------------------------------------------------------------------------
# posets
# --------------------------------------------------------------------------

class P0:
    """A finite poset on {0..n-1}. `lt` is a frozenset of strict pairs (a,b),
    transitively closed and antisymmetric."""

    __slots__ = ("n", "lt", "_up", "_dn")

    def __init__(self, n, lt):
        self.n = n
        self.lt = frozenset(lt)
        self._up = None
        self._dn = None

    def up(self, x):
        if self._up is None:
            self._up = [0] * self.n
            for (a, b) in self.lt:
                self._up[a] |= (1 << b)
        return self._up[x]

    def dn(self, x):
        if self._dn is None:
            self._dn = [0] * self.n
            for (a, b) in self.lt:
                self._dn[b] |= (1 << a)
        return self._dn[x]

    def tag(self):
        return " ".join("%d<%d" % (a, b) for (a, b) in sorted(self.lt)) or "(antichain)"

    def __repr__(self):
        return "P0(%d, %s)" % (self.n, self.tag())


def _gen_labelled(n):
    """Every labelled poset on {0..n-1}, by extension: element k is added with a
    strict down-set D (an ideal of the first k) and a strict up-set U (a filter
    of the first k), disjoint, with D x U already in the order."""
    states = [frozenset()]
    for k in range(n):
        dn = [0] * k
        nxt = []
        for rel in states:
            dnm = [0] * k
            upm = [0] * k
            for (a, b) in rel:
                dnm[b] |= 1 << a
                upm[a] |= 1 << b
            # all ideals D of the first k elements
            ideals = []
            filters = []
            for S in range(1 << k):
                ok = True
                for x in range(k):
                    if (S >> x) & 1 and (dnm[x] & ~S):
                        ok = False
                        break
                if ok:
                    ideals.append(S)
                ok = True
                for x in range(k):
                    if (S >> x) & 1 and (upm[x] & ~S):
                        ok = False
                        break
                if ok:
                    filters.append(S)
            for D in ideals:
                for U in filters:
                    if D & U:
                        continue
                    good = True
                    for d in range(k):
                        if not ((D >> d) & 1):
                            continue
                        if (upm[d] & U) != U:
                            good = False
                            break
                    if not good:
                        continue
                    add = set(rel)
                    for d in range(k):
                        if (D >> d) & 1:
                            add.add((d, k))
                    for u in range(k):
                        if (U >> u) & 1:
                            add.add((k, u))
                    nxt.append(frozenset(add))
        states = nxt
    return states


def _colours(n, lt):
    """Iterated colour refinement on (down-neighbour colours, up-neighbour
    colours).  Returns a list of colour ids, one per element."""
    dn = [[] for _ in range(n)]
    up = [[] for _ in range(n)]
    for (a, b) in lt:
        up[a].append(b)
        dn[b].append(a)
    col = [0] * n
    for _ in range(n + 1):
        sig = [(col[x], tuple(sorted(col[y] for y in dn[x])),
                tuple(sorted(col[y] for y in up[x]))) for x in range(n)]
        order = sorted(set(sig))
        newc = [order.index(s) for s in sig]
        if newc == col:
            break
        col = newc
    return col


def canon(n, lt):
    """Canonical key: the lexicographically least sorted relation tuple over all
    isomorphisms, searched only over permutations preserving the refined
    colouring (which every isomorphism must)."""
    col = _colours(n, lt)
    classes = {}
    for x in range(n):
        classes.setdefault(col[x], []).append(x)
    keys = sorted(classes)
    best = None
    pools = [list(permutations(classes[c])) for c in keys]

    def rec(i, target, acc):
        nonlocal best
        if i == len(pools):
            perm = [0] * n
            for src, dst in acc:
                perm[src] = dst
            key = tuple(sorted((perm[a], perm[b]) for (a, b) in lt))
            if best is None or key < best:
                best = key
            return
        base = target
        for p in pools[i]:
            rec(i + 1, base + len(p), acc + [(p[j], base + j) for j in range(len(p))])

    rec(0, 0, [])
    return (n, best)


def posets_upto_iso(n):
    seen = {}
    for rel in _gen_labelled(n):
        k = canon(n, rel)
        if k not in seen:
            seen[k] = P0(n, k[1])
    return [seen[k] for k in sorted(seen)]


# --------------------------------------------------------------------------
# linear extensions, ideals, faces
# --------------------------------------------------------------------------

def linexts(P):
    """All linear extensions as tuples of elements, by minimal-element
    recursion."""
    out = []
    full = (1 << P.n) - 1

    def rec(placed, word):
        if placed == full:
            out.append(tuple(word))
            return
        for x in range(P.n):
            if (placed >> x) & 1:
                continue
            if (P.dn(x) & ~placed):
                continue
            word.append(x)
            rec(placed | (1 << x), word)
            word.pop()

    rec(0, [])
    return out


def proper_ideals_of(P):
    """Every down-closed S with 0 < |S| < n, as bitmasks, by direct test over
    all subsets."""
    out = []
    full = (1 << P.n) - 1
    for S in range(1, full):
        ok = True
        for x in range(P.n):
            if (S >> x) & 1 and (P.dn(x) & ~S):
                ok = False
                break
        if ok:
            out.append(S)
    return out


def facet_of(P, w):
    """The facet of F(P) belonging to a linear extension w: the chain of
    proper prefix-sets."""
    out = []
    m = 0
    for x in w[:-1]:
        m |= (1 << x)
        out.append(m)
    return tuple(out)


def all_faces(P, verts=None):
    """Faces of F(P) as increasing chains of proper nonempty ideals, grouped by
    dimension (= len - 1); dimension -1 is the empty chain."""
    if verts is None:
        verts = proper_ideals_of(P)
    out = {-1: [()]}
    cur = [(v,) for v in verts]
    d = 0
    while cur:
        out[d] = cur
        nxt = []
        for c in cur:
            t = c[-1]
            for v in verts:
                if v != t and (t & v) == t:
                    nxt.append(c + (v,))
        cur = nxt
        d += 1
    return out


def blocks(P, sigma):
    full = (1 << P.n) - 1
    prev = 0
    bs = []
    for I in sigma:
        bs.append(I & ~prev)
        prev = I
    bs.append(full & ~prev)
    return tuple(bs)


def induced(P, mask):
    elts = [x for x in range(P.n) if (mask >> x) & 1]
    pos = {x: i for i, x in enumerate(elts)}
    return P0(len(elts), {(pos[a], pos[b]) for (a, b) in P.lt
                          if a in pos and b in pos})


# --------------------------------------------------------------------------
# the adjacent-transposition graph
# --------------------------------------------------------------------------

def at_graph(P):
    """(linear extensions, adjacency as list of sets).  An edge joins two linear
    extensions differing by swapping two adjacent, incomparable entries."""
    les = linexts(P)
    idx = {w: i for i, w in enumerate(les)}
    adj = [set() for _ in les]
    for w in les:
        i = idx[w]
        for t in range(P.n - 1):
            a, b = w[t], w[t + 1]
            if (a, b) in P.lt or (b, a) in P.lt:
                continue
            v = w[:t] + (b, a) + w[t + 2:]
            adj[i].add(idx[v])
    return les, adj


def at_laplacian(P):
    les, adj = at_graph(P)
    m = len(les)
    M = [[Fraction(0)] * m for _ in range(m)]
    for i in range(m):
        M[i][i] = Fraction(len(adj[i]))
        for j in adj[i]:
            M[i][j] -= 1
    return les, M


# --------------------------------------------------------------------------
# weighted links and their lambda_2
# --------------------------------------------------------------------------

def link_1skeleton(P, sigma, facets):
    """(vertices, edge-weight dict) of the weighted 1-skeleton of link(sigma),
    weights = number of facets of F(P) containing the 2-face.  Brute force from
    the facet list; the localisation theorem is not used."""
    s = set(sigma)
    cont = [set(f) - s for f in facets if s <= set(f)]
    verts = sorted(set().union(*cont)) if cont else []
    idx = {v: i for i, v in enumerate(verts)}
    ew = {}
    for f in cont:
        r = sorted(f)
        for a in range(len(r)):
            for b in range(a + 1, len(r)):
                k = (idx[r[a]], idx[r[b]])
                ew[k] = ew.get(k, 0) + 1
    return verts, ew


def lambda2_weighted(nv, ew):
    """Second largest eigenvalue of the random walk on a weighted graph, i.e.
    the largest eigenvalue of D^{-1/2} W D^{-1/2} restricted to the orthogonal
    complement of D^{1/2}1.  Symmetric dense Jacobi.  Returns None if the graph
    has no edge."""
    if nv == 0 or not ew:
        return None
    deg = [0.0] * nv
    for (i, j), w in ew.items():
        deg[i] += w
        deg[j] += w
    if any(d == 0 for d in deg):
        # isolated vertex: the walk is not irreducible; treat as lambda_2 = 1
        return 1.0
    import math
    A = [[0.0] * nv for _ in range(nv)]
    for (i, j), w in ew.items():
        v = w / math.sqrt(deg[i] * deg[j])
        A[i][j] = v
        A[j][i] = v
    # deflate the Perron vector sqrt(deg), eigenvalue 1
    tot = sum(deg)
    u = [math.sqrt(d / tot) for d in deg]
    for i in range(nv):
        for j in range(nv):
            A[i][j] -= 2.0 * u[i] * u[j]
    ev = jacobi_eigenvalues(A)
    # the deflation moved the eigenvalue 1 to -1; the rest are untouched.
    ev = sorted(ev)
    # remove one copy of the shifted Perron value (-1)
    k = min(range(len(ev)), key=lambda t: abs(ev[t] + 1.0))
    ev.pop(k)
    return max(ev) if ev else None


def jacobi_eigenvalues(Ain, tol=1e-13, sweeps=200):
    n = len(Ain)
    A = [row[:] for row in Ain]
    import math
    for _ in range(sweeps):
        off = 0.0
        for i in range(n):
            for j in range(i + 1, n):
                off += A[i][j] * A[i][j]
        if off < tol * tol:
            break
        for p in range(n):
            for q in range(p + 1, n):
                if abs(A[p][q]) < 1e-16:
                    continue
                theta = (A[q][q] - A[p][p]) / (2.0 * A[p][q])
                t = (1.0 if theta >= 0 else -1.0) / (abs(theta) + math.sqrt(theta * theta + 1.0))
                c = 1.0 / math.sqrt(t * t + 1.0)
                s = t * c
                for k in range(n):
                    akp = A[k][p]
                    akq = A[k][q]
                    A[k][p] = c * akp - s * akq
                    A[k][q] = s * akp + c * akq
                for k in range(n):
                    apk = A[p][k]
                    aqk = A[q][k]
                    A[p][k] = c * apk - s * aqk
                    A[q][k] = s * apk + c * aqk
    return [A[i][i] for i in range(n)]
