"""Is claim 1's CONCLUSION robust to the alternative reading of 'relative'?

L1 (mg-276d, CONDITIONAL) reads "relative" as relative to the boundary
subcomplex generated by the free ridges.  mg-a3d4 inherits that without
re-examination (its §13).  So: under the OTHER reading -- no boundary quotient,
i.e. the absolute top Laplacian -- is the top-degree object still a graph
object, or does claim 1 depend on L1?
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from audit_core import posets_upto_iso, at_graph
from audit_identities import ridge_data, sgn

for n in range(1,7):
    okabs=okshift=tot=0
    for P in posets_upto_iso(n):
        tot+=1
        les,facets,rf=ridge_data(P)
        m=len(facets); E=[sgn(w) for w in les]
        # absolute top Laplacian: d^T d over ALL ridges
        L=[[0]*m for _ in range(m)]
        for r,cof in rf.items():
            for (i,ti) in cof:
                L[i][i]+=1
            if len(cof)==2:
                (i,ti),(j,tj)=cof
                si=-1 if ti%2 else 1; sj=-1 if tj%2 else 1
                L[i][j]+=si*sj; L[j][i]+=si*sj
        _,adj=at_graph(P)
        # free ridges at facet i
        free=[sum(1 for t in range(len(facets[i])) if len(rf[facets[i][:t]+facets[i][t+1:]])==1) for i in range(m)]
        A=[[1 if j in adj[i] else 0 for j in range(m)] for i in range(m)]
        D=[len(adj[i]) for i in range(m)]
        okabs += all(E[i]*L[i][j]*E[j] == ((D[i]+free[i]) if i==j else 0) - A[i][j]
                     for i in range(m) for j in range(m))
        okshift+= all((D[i]+free[i])==(P.n-1) for i in range(m)) if m else True
    print("n=%d posets=%3d   E L^abs E == (deg+free)I - A on %3d   deg+free == n-1 on %3d"%(n,tot,okabs,okshift))
print()
print("So under EITHER reading the top-degree Hodge operator is a graph object:")
print("  relative -> Delta_AT = D - A ;  absolute -> (n-1)I - A .")
