#!/usr/bin/env python3
"""OVERTAKEN -- HAS A COMMITTED TRANSCRIPT'S PRODUCER MOVED SINCE IT WAS TAKEN?

mg-6b2d's remainder item 3, in its own words: *`out_pinnable_3b51.txt` still
says `R3 FIRES ON THIS DIRECTORY SIX TIMES` -- a literal tranche 6 replaced with
a computed count in `pinnable.py`.  It is a dated hand-run that NO SUITE
RE-TAKES.*

THAT SENTENCE NAMES ONE FILE AND THE PROPERTY IS A CLASS.  This estate ships
1125 committed transcripts under code/ at AS_OF.  Most are regenerated by a `run_all.sh` and so move
with their producer in one commit; some are hand-runs that no suite re-takes and
that say so about themselves; and NOTHING ANYWHERE TELLS YOU WHICH OF THE SECOND
KIND HAS BEEN LEFT BEHIND BY ITS OWN PRODUCER.  mg-f771's g0 sees a watched
transcript MOVE; it cannot see one that never gets the chance.  mg-ede8's
liveindex.py asks whether a transcript was already wrong AT ITS OWN COMMIT, and
its method is free only on figures that are a function of the tracked path list
-- which mg-bdc0's pathlist.py then measured at ZERO of 840.  This is the
neighbouring question, and it is cheaper than either: NOT `is this figure
wrong`, but `has the thing that computes it moved since`.

    THE RULE.  A committed transcript is OVERTAKEN when its producer's source at
    the commit that last wrote the transcript DIFFERS from that producer's
    source at AS_OF.  It needs no instrument execution and no dirty tree -- one
    `git log --name-only` walk and two `git show` per candidate -- so every
    figure on this page is a function of ONE COMMIT and out_overtaken.txt
    reproduces BYTE-IDENTICALLY, which is worklist.py's, exemplars.py's,
    semantic.py's and liveindex.py's arrangement on a sixth subject.

    IT IS ONE-DIRECTIONAL, AND THAT IS THE ONLY REASON IT IS WORTH HAVING.
    OVERTAKEN is a PROOF ABOUT THE PRODUCER and NOT about the transcript: the
    producer that would run today is not the producer that ran.  It is NOT a
    proof that the transcript is wrong -- the edit may not reach the printed
    figure, and section 4 measures how often it visibly does.  NOT OVERTAKEN
    PROVES NOTHING AT ALL, and that is the silent direction: a transcript goes
    stale when its CORPUS moves with no producer edit whatsoever, which is
    exactly how out_consumers.txt has shipped stale at its own commit in 5 of
    its 8 versions, and no rule here can see it.  N35 asserts that.

    THE PAIRING IS IMPORTED AND NOT RE-SPELLED (mg-d2c2, mg-1344's P5).
    pathlist.pairs_at is the estate's `out_X.txt <-> X.py|X.sh` convention, and
    a re-statement of it here could disagree with out_pathlist.txt about what a
    pair is while both pages claimed to be about the same 855.

    AND THE STRICT RULE CANNOT SEE THE FILE THIS ARM WAS FILED FROM, WHICH IS
    THE FUNNEL'S OWN SUBJECT ARRIVING IN IT.  `out_pinnable_3b51.txt` is
    produced by `pinnable.py` WITH AN ARGUMENT, so `pinnable_3b51.py` does not
    exist and the pair is in pathlist.py's 270 UNREACHED rather than in its 855.
    So the widening is not an enhancement, it is the difference between an
    instrument that answers the ticket and one that reports a number about
    somebody else.  It strips trailing `_`-separated segments until a producer
    of that name exists in the SAME directory, which recovers 30 of the 270 --
    and those 30 are ADJUDICATED BY HAND in section 3, because a mechanical
    widening is a claim and a table a person checked is evidence.  ONE OF THE 30
    IS FALSE and it is excluded BY THE TABLE and not by the matcher, which is
    the arrangement mg-9d9e's arm shipped: a matcher tightened until its output
    is clean proves nothing, and what carries the exclusion is the reading.

    THE WIDENING ALSO REACHES A CLASS WHERE OVERTAKEN IS BY DESIGN, and it would
    be a false accusation to leave it unnamed: this estate preserves transcripts
    of a PAST state on purpose -- `_PREREPAIR`, `_FIRSTFORM`, `_FIRSTRUN`,
    `_before` -- and those are OVERTAKEN the moment the repair they precede
    lands.  Section 2 separates them and P55 measures the separation in BOTH
    directions, because a marker wide enough to eat the live rows would make
    this page's headline an artifact of the marker.

    NOTHING IS REPAIRED HERE AND SECTION 5 IS WHY, MEASURED RATHER THAN
    ASSERTED.  Each of this directory's own three flagged transcripts was
    re-taken BY HAND during this tranche and each failed for a DIFFERENT reason,
    none of which is `nobody got round to it`.  Those three runs need a dirty
    tree and a subject suite, so they cannot be on a build path and are recorded
    as a dated hand-table -- out_ground_truth.txt's arrangement, and the same
    declared blind spot.  The table REFUSES if it does not name exactly the
    transcripts the scan flags in this directory.

    IT IS IN run_all.sh, unlike pinnable.py and pathlist.py, and for
    exemplars.py's reason exactly: it executes no instrument code and needs no
    dirty tree.  Its figures are a function of AS_OF and NOT of when it ran.

    python3 code/asof_census_20ee/overtaken.py         # at AS_OF
    python3 code/asof_census_20ee/overtaken.py <rev>   # anywhere else

    THE TWO HAND TABLES ARE PINNED TO AS_OF AND THE <rev> MODE DOES NOT MOVE
    THEM.  Both REFUSE with exit 2 rather than answering when the matcher and
    the table stop agreeing, which is the honest failure for a judgement
    somebody wrote down at one commit: a table that quietly kept answering at a
    revision it was never checked against would be the defect this page is
    about, one artefact along.
"""

import ast
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import pathlist  # noqa: E402  -- the pairing, imported rather than re-spelled
import pinnable  # noqa: E402  -- code_only, the prose/code separator

# The commit every figure on this page is a function of.  An ancestor of
# origin/main -- mg-20ee's condition 1 -- and it was the tip of origin/main when
# this measurement was TAKEN rather than when it LANDS.  A PIN AGES AND SAYS SO
# (pathlist.py's declaration, kept because it is true again here): main moved
# while this branch sat in the merge queue, and the alternative to a pin that
# ages is the live figure this whole directory exists to complain about.
AS_OF = "9d6bbfa"

# THE ARCHIVAL MARKER.  A transcript this estate PRESERVES rather than re-takes,
# said in its own filename.  Deliberately a fixed token list and not a pattern:
# the tokens are conventions this estate already writes, and a pattern loose
# enough to guess at new ones would decide the headline by guessing.  Matched on
# a `_`-separated segment so `_before` does not match `before_repair`, and
# UPPERCASE-or-exact so an ordinary word cannot enter by accident.
ARCHIVAL_TOKENS = ("PREREPAIR", "FIRSTFORM", "FIRSTRUN", "BEFOREMAIL",
                   "PRE5f7c", "before")

# THE WIDENED PAIRS, ADJUDICATED BY HAND -- one row per candidate the widening
# produces at AS_OF, and the arm REFUSES if this table is incomplete or names a
# pair the matcher did not find.  A rule and a judgement in one column are
# indistinguishable to a reader, so they are in two: the matcher produces the
# candidate, this table says whether it is a pair.
#
# THE ONE `FALSE` IS THE REASON THE TABLE EXISTS.  `out_run_all_a74f_PRE5f7c.txt`
# lives in code/state_suppression_repair_5f7c and the widening pairs it to that
# directory's own run_all.sh; its README says in so many words that it is
# `code/state_delegation_repair_a74f/out_run_all.txt` AS IT STOOD BEFORE THIS
# REPAIR -- a FOREIGN directory's transcript, copied in.  No spelling rule over
# basenames can see that, because the evidence is a sentence.
WIDENED_VERDICT = {
    "code/anchor_population_audit_0ba7/out_a4_labels_FIRSTFORM_miss3.txt": True,
    "code/asof_census_20ee/out_pinnable_3b51.txt": True,
    "code/asof_census_20ee/out_pinnable_a4ef.txt": True,
    "code/asof_census_20ee/out_pinnable_b0ae.txt": True,
    "code/asof_census_20ee/out_worklist_rerun.txt": True,
    "code/branching_bound_audit_aaf4/out_a3_criticism_FIRSTFORM_exit1.txt": True,
    "code/branching_bound_audit_aaf4/out_selftest_aaf4_FIRSTFORM_exit1.txt": True,
    "code/branching_bound_d075/out_s3_bound_FIRSTFORM_exit1.txt": True,
    "code/branching_bound_d075/out_s5_own_criticism_FIRSTRUN_exit1.txt": True,
    "code/control_audit_9876/out_a1_census_PREREPAIR.txt": True,
    "code/control_audit_9876/out_a2_discriminate_PREREPAIR.txt": True,
    "code/control_audit_9876/out_a3_auditor_selftest_PREREPAIR.txt": True,
    "code/control_audit_9876/out_a4_sweep_PREREPAIR.txt": True,
    "code/corpus_universe_1d6c/out_p4_selfcheck_FIRSTFORM_exit1.txt": True,
    "code/corpus_universe_1d6c/out_selftest1d6c_FIRSTFORM_exit1.txt": True,
    "code/dual_certificate_audit_eaa1/out_a3_n6_deep.txt": True,
    "code/eps0_threshold_3969/out_a1_vacuity_n7.txt": True,
    "code/eps0_threshold_3969/out_a2_uniform_n7.txt": True,
    "code/hash_population_6e58/out_p3_unrestricted_FIRSTFORM_selferr.txt": True,
    "code/hash_population_6e58/out_selftest_6e58_FIRSTFORM_exit1.txt": True,
    "code/pairbias_audit_a832f/out_a2_realizable_n7.txt": True,
    "code/pairbias_audit_a832f/out_a4_boundary_structure_n7.txt": True,
    "code/sibling_sweep_7085/out_r1_sweep_FIRSTRUN_2FAIL.txt": True,
    "code/species_gate_audit_d53d/out_run_all_d53d.txt": True,
    "code/species_remainder_f8fa/out_w3_scope_before.txt": True,
    "code/state_claims_repair_0120/out_anchors0120_HEAD.txt": True,
    "code/state_suppression_repair_5f7c/out_run_all_a74f_PRE5f7c.txt": False,
    "code/state_visibility_audit_65eb/out_anchor65eb_bd24efc.txt": True,
    "code/verdict_delivery_bf3f/out_d4_live_BEFOREMAIL_DROPPED.txt": True,
    "code/verdict_path_repair_1d26/out_run_all_1d26.txt": True,
}

# THE HAND-RUNS THIS TRANCHE TOOK, and the reason each one is NOT committed as
# a refresh.
#
# THIS TABLE REFUSED ON ITS OWN AUTHOR AND THAT IS WHY IT HAS FIVE ROWS AND NOT
# THREE.  It was written against 637b046 with the three out_pinnable_* rows, and
# the branch was then rebased onto 9d6bbfa -- mg-3ebf's landing, which EDITS
# worklist.py and does not move out_worklist.txt.  Re-pinning AS_OF made the
# scan flag two rows the table did not name, and section 5 exited 2 rather than
# printing a table that had stopped covering its subject.  The first revision
# this arm was asked about that was not the one it was written at is the one
# that caught it, which is the strongest thing a refusal can do and is worth
# more than the three rows it was built for.  Every entry is a DATED MEASUREMENT taken on a dirty
# tree during mg-6b2d, which is a state no build path may be in -- so this
# table cannot be recomputed here and says so, which is out_ground_truth.txt's
# arrangement and the same declared blind spot.  Section 5 REFUSES if it does
# not name exactly the transcripts the scan flags in this directory.
HAND_RETAKE = {
    "code/asof_census_20ee/out_pinnable_3b51.txt": (
        "CANNOT BE RE-TAKEN AT ALL",
        "`sh code/landscape_repair_audit_3b51/run_all.sh` ran to exit 0 in 63 s "
        "and left `git status` EMPTY, so pinnable.py refused with `is EMPTY, and "
        "this instrument classifies a drift it is given rather than one it "
        "produces` (exit 1).  The subject stopped drifting because THE PIN "
        "TRANCHE 4 LANDED ON IT WORKED.  The instrument's own recommendation "
        "destroyed its subject, so this transcript is not stale-and-refreshable, "
        "it is a record of a state the repository no longer has."),
    "code/asof_census_20ee/out_pinnable_a4ef.txt": (
        "RE-TAKEABLE, AND THE INPUT IS NOT REPO STATE",
        "The a4ef suite's whole drift is `__pycache__` residue -- files git is "
        "configured never to track, which R1 exists to name.  MEASURED BY "
        "CONSTRUCTION rather than argued: on a clean checkout its s1_extent "
        "transcript declines 6 entries, and creating THREE EMPTY DIRECTORIES by "
        "hand (`code/species_7d75/__pycache__`, `code/species_repair_6f61/"
        "__pycache__`, `code/species_remainder_f8fa/__pycache__`) makes it "
        "BYTE-IDENTICAL to the committed one at 9.  So this suite has NO "
        "repository-caused drift at AS_OF, and re-taking the page would publish "
        "one operator's execution history in place of another's."),
    "code/asof_census_20ee/out_worklist.txt": (
        "RE-TAKEN BY THE SUITE ON THIS BRANCH, AND IT DID NOT MOVE",
        "THE DEMONSTRATION THAT `OVERTAKEN` IS NOT `WRONG`, and it is here "
        "because the REFUSAL ABOVE PUT IT HERE.  mg-3ebf edited worklist.py at "
        "AS_OF and did not move out_worklist.txt, whose last commit is tranche "
        "10's 0cb0fa4 -- so the rule flags it, CODE, correctly.  It is also on "
        "run_all.sh and PINNED at 07a2fd0, so this branch re-took it by running "
        "the suite and it reproduced BYTE-IDENTICALLY.  A row can be OVERTAKEN "
        "and demonstrably current at once; its witness is 0, which is the only "
        "signal section 4 could have given and is not evidence of anything."),
    "code/asof_census_20ee/out_worklist_rerun.txt": (
        "NOT RE-TAKEN, AND THE REASON IS ITS INPUT",
        "The fourth transcript in this directory that no suite re-takes, and "
        "the one whose reason is neither a pin nor a dirty tree: worklist.py's "
        "--rerun mode is fed by ground_truth.sh, which takes about 70 minutes, "
        "executes every candidate instrument and writes-then-restores "
        "directories under code/.  run_all.sh's own header declares that as the "
        "reason it is off every build path.  So this row is OVERTAKEN, CODE, "
        "and re-taking it is a 70-minute hand-run this tranche did not do -- "
        "reported at the low water mark rather than left out."),
    "code/asof_census_20ee/out_pinnable_b0ae.txt": (
        "RE-TAKEABLE, INPUT IS REPO STATE, AND STILL DECLINED",
        "`bash code/state_relocation_audit_b0ae/run_all.sh` ran to exit 0 in 25 s "
        "and moved out_b8_findability.txt, whose B8.2 is `about the repo as it "
        "stands` BY DECLARATION -- so this is the one of the three whose drift "
        "really is repo state.  Its value is a function of HEAD, and HEAD moves "
        "under the refinery's rebase AFTER the last moment anything on this "
        "branch can run.  Committing it would be mg-ede8's `stale at its own "
        "commit` mechanism, chosen deliberately, in the directory that measures "
        "it."),
}

# WHAT ALL THREE RE-TAKES AGREE ON, and it is the sharpest single fact this
# tranche has: every committed pinnable transcript in this directory describes a
# TWO-RULE instrument.  pinnable.py has had THREE rules since tranche 6 (mg-e5f3
# added R3), and both re-takes that could be taken print `THIS INSTRUMENT
# ANSWERS ITS OWN THREE RULES` and a whole `R3 UNORDERED WALKS` section that no
# committed transcript contains -- 26 diff lines each.  Section 4's witness sees
# that from the SOURCE ALONE, without running anything, and this is the ground
# truth it was checked against.
_RETAKE_MOVED = {"code/asof_census_20ee/out_pinnable_a4ef.txt": 26,
                 "code/asof_census_20ee/out_pinnable_b0ae.txt": 26}

# A PRINTABLE STRING LITERAL, for section 4's witness.  Deliberately over-wide
# in the direction that WEAKENS the witness: a regex, a dict key and an
# unreachable branch's message all count, so a positive is EVIDENCE and never a
# proof, and a ZERO is not evidence of freshness at all.
_LIT_MIN = 12
_SEG = re.compile(r"[^A-Za-z0-9]+")


def git(*args):
    got = subprocess.run(["git", "-C", ROOT, *args], capture_output=True)
    if got.returncode != 0:
        raise SystemExit("overtaken: git %s failed: %s"
                         % (" ".join(args),
                            got.stderr.decode("utf-8", "replace").strip()))
    return got.stdout.decode("utf-8", "surrogateescape")


def blob(rev, path):
    """The bytes of `path` at `rev`, or None when it is not in that tree."""
    got = subprocess.run(["git", "-C", ROOT, "show", "%s:%s" % (rev, path)],
                         capture_output=True)
    if got.returncode != 0:
        return None
    return got.stdout.decode("utf-8", "surrogateescape")


def last_touch(rev):
    """path -> how many commits back from `rev` it was last written.

    ONE `git log` WALK AND NOT ONE PER PATH.  884 pairs is 1768 `git log -1`
    calls the obvious way; this is one call and a dict, and it is also the
    honest spelling -- every path's answer comes out of the same walk, so no
    two figures on this page can be taken against different histories.

    LOWER IS NEWER.  The index is a position in the walk and NOT a timestamp:
    a rebase rewrites dates, and this estate's refinery rebases every branch.
    """
    out, idx = {}, -1
    for line in git("log", "--format=%H", "--name-only", rev).splitlines():
        if not line:
            continue
        if len(line) == 40 and all(c in "0123456789abcdef" for c in line):
            idx += 1
            continue
        out.setdefault(line, idx)
    return out


def widen(missed, tracked):
    """(transcript, producer) for transcripts the strict convention misses.

    `code/D/out_X_Y.txt` is offered to `code/D/X_Y.py|sh`, then to `code/D/X.py`
    and so on, stripping ONE trailing `_`-separated segment at a time and
    stopping at the first producer that exists.  SAME DIRECTORY ONLY, which is
    the guard the one false pair defeats anyway -- a foreign transcript copied
    in carries no mark a basename rule can read.
    """
    got = []
    for path in sorted(missed):
        here = os.path.dirname(path)
        stem = os.path.basename(path)[4:-4]
        hit = None
        while "_" in stem and hit is None:
            stem = stem.rsplit("_", 1)[0]
            for ext in (".py", ".sh"):
                cand = os.path.join(here, stem + ext)
                if cand in tracked:
                    hit = cand
                    break
        if hit:
            got.append((path, hit))
    return got


def is_archival(transcript):
    """True when the FILENAME says this transcript preserves a past state."""
    segs = _SEG.split(os.path.basename(transcript)[4:-4])
    return any(tok in segs for tok in ARCHIVAL_TOKENS)


def code_signature(src, path):
    """`src` with its prose gone, as a comparable sequence of code lines.

    pinnable.code_only BLANKS prose and PRESERVES COLUMNS, so its output still
    differs when a comment merely changes length; the sequence of non-blank
    stripped lines is what survives a prose-only edit and nothing else.  The
    separator is imported: this arm cannot disagree with permuted.py section 4
    about what prose is.
    """
    blanked, separated = pinnable.code_only(src, path)
    return (tuple(l.strip() for l in blanked.splitlines() if l.strip()),
            separated)


def literals(src):
    """Every long single-line string literal in `src`; EMPTY if it will not parse.

    An unparseable producer therefore contributes NO witness rather than a
    misleading one, which is the weakening direction section 4 declares.
    """
    try:
        tree = ast.parse(src)
    except (SyntaxError, ValueError):
        return set()
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            val = node.value.strip()
            if len(val) >= _LIT_MIN and "\n" not in val:
                out.add(val)
    return out


def grade(transcript, producer, before, after, text):
    """The WHOLE decision for one pair, given nothing but four strings.

    IT TAKES ITS INPUTS RATHER THAN FETCHING THEM, and that is not tidiness:
    every control in selftest_20ee.py fires THIS function on a planted pair, so
    what the suite exercises is the rule the page publishes and not a
    re-statement of it (P34's discipline, three instruments along).

    Returns None when the producer did not move -- which includes the
    changed-and-changed-back case, where the transcript is NOT stale and saying
    so would be a false accusation.
    """
    if before is None or after is None or before == after:
        return None
    sig_before, sep_before = code_signature(before, producer)
    sig_after, sep_after = code_signature(after, producer)
    new = sorted(v for v in literals(after) - literals(before)
                 if v not in text) if producer.endswith(".py") else []
    return {"transcript": transcript, "producer": producer, "wide": False,
            "grade": "CODE" if sig_before != sig_after else "PROSE-ONLY",
            "separated": sep_before and sep_after,
            "archival": is_archival(transcript),
            "witness": new}


def scan(rev=AS_OF):
    """Every figure this file publishes, from one commit and nothing else."""
    tracked = set(git("ls-tree", "-r", "--name-only", rev).splitlines())
    strict, missed = pathlist.pairs_at(rev, tracked)
    wide_all = widen(missed, tracked)
    wide = [(t, p) for t, p in wide_all if WIDENED_VERDICT.get(t)]
    order = last_touch(rev)
    rows, unresolved = [], []
    for transcript, producer in sorted(strict) + sorted(wide):
        if transcript not in order or producer not in order:
            unresolved.append(transcript)
            continue
        if order[producer] >= order[transcript]:
            continue                      # the producer has not moved since
        at_transcript = git("log", "--format=%H", "-1", rev, "--",
                            transcript).strip()
        row = grade(transcript, producer, blob(at_transcript, producer),
                    blob(rev, producer), blob(rev, transcript) or "")
        if row is None:
            continue                      # changed and changed back, or absent
        row["wide"] = (transcript, producer) in wide
        rows.append(row)
    return {"rev": rev, "tracked": len(tracked), "strict": strict,
            "missed": missed, "wide_all": wide_all, "wide": wide,
            "rows": rows, "unresolved": unresolved}


def banner(title):
    print()
    print("-" * 78)
    print(title)
    print("-" * 78)
    print()


def main(argv):
    rev = argv[1] if len(argv) > 1 else AS_OF
    full = git("rev-parse", rev).strip()
    got = scan(rev)
    rows = got["rows"]
    live = [r for r in rows if not r["archival"]]
    arch = [r for r in rows if r["archival"]]
    code = [r for r in live if r["grade"] == "CODE"]
    prose = [r for r in live if r["grade"] == "PROSE-ONLY"]

    print("=" * 78)
    print("mg-6b2d -- HAS THE PRODUCER MOVED SINCE THE TRANSCRIPT WAS TAKEN?")
    print("=" * 78)
    print()
    print("  AS_OF = %s (%s)" % (rev, full[:12]))
    print()
    print("  OVERTAKEN is a proof ABOUT THE PRODUCER: the thing that would run")
    print("  today is not the thing that ran.  It is NOT a proof that the")
    print("  transcript is wrong, and NOT OVERTAKEN proves NOTHING AT ALL -- a")
    print("  transcript goes stale when its CORPUS moves with no producer edit,")
    print("  and no rule on this page can see that (N35).  Read section 6.")

    banner("1  THE FUNNEL -- every loss counted where it happens")
    print("      %5d  tracked path(s) at AS_OF" % got["tracked"])
    print("      %5d  committed transcript(s) under code/ -- `out_*.txt`"
          % (len(got["strict"]) + len(got["missed"])))
    print("      %5d  paired to a producer by pathlist.py's convention,"
          % len(got["strict"]))
    print("             IMPORTED from pathlist.pairs_at and not re-spelled")
    print("      %5d  transcript(s) that convention does NOT reach" % len(got["missed"]))
    print("      %5d  of those recovered by the trailing-segment widening"
          % len(got["wide_all"]))
    print("      %5d  of the recovered ones adjudicated TRUE by hand (section 3)"
          % len(got["wide"]))
    print("      %5d  pairs examined" % (len(got["strict"]) + len(got["wide"])))
    print()
    print("      %5d  OVERTAKEN -- the producer's source at AS_OF differs from"
          % len(rows))
    print("             its source at the commit that last wrote the transcript")
    print("      %5d  of those ARCHIVAL BY NAME -- preserved on purpose, and"
          % len(arch))
    print("             OVERTAKEN the moment the repair they precede lands")
    print("      %5d  LIVE -- %d where the producer's CODE moved, %d PROSE-ONLY"
          % (len(live), len(code), len(prose)))
    if got["unresolved"]:
        print()
        print("      %5d  pair(s) whose paths are in no commit of this walk --"
              % len(got["unresolved"]))
        print("             REPORTED rather than dropped")
        for t in got["unresolved"]:
            print("             %s" % t)

    banner("2  THE LIVE ROWS -- the producer's CODE moved")
    print("  PROSE-ONLY IS A SEPARATE COLUMN AND NOT A FILTER.  The split is")
    print("  pinnable.code_only's, imported, so this arm cannot disagree with")
    print("  permuted.py section 4 about what prose is.  A prose-only edit")
    print("  cannot change what the producer prints; that it is only %d of %d"
          % (len(prose), len(live)))
    print("  is the measurement, and a page that filtered them out silently")
    print("  would be publishing the same number with no way to check it.")
    print()
    for r in sorted(code, key=lambda r: r["transcript"]):
        print("      %-4s %s" % ("WIDE" if r["wide"] else "", r["transcript"]))
        print("           <- %s%s" % (r["producer"],
                                      "" if r["separated"]
                                      else "   [PROSE NOT SEPARABLE]"))
    print()
    print("  PROSE-ONLY -- the producer moved and its code did not:")
    print()
    for r in sorted(prose, key=lambda r: r["transcript"]):
        print("      %-4s %s" % ("WIDE" if r["wide"] else "", r["transcript"]))
        print("           <- %s" % r["producer"])
    print()
    print("  ARCHIVAL BY NAME -- OVERTAKEN AND NOT A FINDING.  These preserve a")
    print("  PAST state on purpose and their producers were repaired afterwards,")
    print("  which is what OVERTAKEN says about them and is exactly right.  They")
    print("  are PRINTED rather than dropped, because a class removed silently")
    print("  and a class that was never found look the same on the page:")
    print()
    for r in sorted(arch, key=lambda r: r["transcript"]):
        print("      %-4s %-11s %s" % ("WIDE" if r["wide"] else "",
                                       r["grade"], r["transcript"]))
        print("           <- %s" % r["producer"])

    banner("3  THE WIDENING, AND THE ONE PAIR A PERSON HAD TO REFUSE")
    print("  The strict convention cannot see a transcript whose producer takes")
    print("  an ARGUMENT, which is every file this arm was filed about:")
    print("  out_pinnable_3b51.txt is `pinnable.py code/landscape_repair_audit_3b51`")
    print("  and there is no pinnable_3b51.py.  So the widening is the")
    print("  difference between answering the ticket and reporting a number")
    print("  about somebody else.")
    print()
    print("      %5d  candidate(s) produced by the matcher" % len(got["wide_all"]))
    print("      %5d  adjudicated TRUE" % len(got["wide"]))
    print("      %5d  adjudicated FALSE -- excluded BY THE TABLE, not by the"
          % (len(got["wide_all"]) - len(got["wide"])))
    print("             matcher, which still finds them (P53)")
    print()
    missing = [t for t, _ in got["wide_all"] if t not in WIDENED_VERDICT]
    extra = [t for t in WIDENED_VERDICT if t not in {t for t, _ in got["wide_all"]}]
    if missing or extra:
        print("  REFUSED.  The hand table does not match the matcher at this")
        print("  revision, and a table that has drifted from its own subject is")
        print("  worse than no table:")
        for t in missing:
            print("      NOT IN THE TABLE:  %s" % t)
        for t in extra:
            print("      IN THE TABLE ONLY: %s" % t)
        raise SystemExit(2)
    for t, p in got["wide_all"]:
        print("      %-5s %s" % ("TRUE" if WIDENED_VERDICT[t] else "FALSE", t))
        print("            <- %s" % p)

    banner("4  THE WITNESS -- what a reader can check WITHOUT running anything")
    print("  For each OVERTAKEN row whose producer is Python: how many long")
    print("  single-line string literals exist in the producer at AS_OF, did")
    print("  NOT exist at the transcript's own commit, and do NOT appear")
    print("  anywhere in the committed transcript.")
    print()
    print("  IT IS A WITNESS AND NOT A PROOF, IN BOTH DIRECTIONS.  A regex, a")
    print("  dict key and an unreachable branch's message all count, so a")
    print("  positive number OVER-states; and a ZERO is not evidence of")
    print("  freshness, because a producer can change what it prints without")
    print("  adding a literal at all.  It is here because it is the only half")
    print("  of `is this transcript actually stale` that costs nothing.")
    print()
    pos = [r for r in rows if r["witness"]]
    print("      %5d  OVERTAKEN row(s) with a Python producer"
          % len([r for r in rows if r["producer"].endswith(".py")]))
    print("      %5d  with at least one new literal absent from the transcript"
          % len(pos))
    print()
    for r in sorted(rows, key=lambda r: (-len(r["witness"]), r["transcript"])):
        if not r["witness"]:
            continue
        print("      %4d  %s" % (len(r["witness"]), r["transcript"]))
        for v in r["witness"][:2]:
            print("            %r" % v[:66])

    banner("5  THIS DIRECTORY'S OWN, RE-TAKEN BY HAND AND NOT REFRESHED")
    mine = sorted(r["transcript"] for r in rows
                  if os.path.dirname(r["transcript"]) == "code/asof_census_20ee")
    if sorted(HAND_RETAKE) != mine:
        print("  REFUSED.  The hand table names %s" % sorted(HAND_RETAKE))
        print("  and the scan flags %s.  A dated table that has stopped" % mine)
        print("  covering its own subject is the defect this directory is about.")
        raise SystemExit(2)
    print("  %d transcripts, %d DIFFERENT reasons, and not one of them is"
          % (len(mine), len(mine)))
    print("  `nobody got round to it`.  Each is a DATED MEASUREMENT taken by")
    print("  hand during mg-6b2d, most of them on a dirty tree, which is a")
    print("  state no build path may be in -- so this file cannot recompute")
    print("  them, which is out_ground_truth.txt's arrangement and the same")
    print("  declared blind spot.")
    print()
    print("  THIS TABLE REFUSED ON ITS OWN AUTHOR, WHICH IS WHY IT HAS FIVE")
    print("  ROWS AND NOT THREE.  It was written at 637b046 naming the three")
    print("  out_pinnable_* transcripts; this branch was then rebased onto")
    print("  mg-3ebf's landing, which EDITS worklist.py and does not move")
    print("  out_worklist.txt, and re-pinning AS_OF made the scan flag two rows")
    print("  the table did not name.  Section 5 exited 2 rather than print a")
    print("  table that had stopped covering its subject.  The first revision")
    print("  this arm was asked about that was not the one it was written at is")
    print("  the one that caught it.")
    print()
    for t in mine:
        verdict, why = HAND_RETAKE[t]
        print("      %s" % t)
        print("          %s" % verdict)
        for line in _wrap(why, 66):
            print("              %s" % line)
        print()
    print("  AND ALL THREE PINNABLE ROWS AGREE ON ONE THING.  Every committed")
    print("  pinnable transcript here describes a TWO-RULE instrument.")
    print("  pinnable.py has had THREE since tranche 6, and both re-takes that")
    print("  COULD be taken print a whole `R3 UNORDERED WALKS` section no")
    print("  committed transcript contains -- %d diff lines each, measured."
          % _RETAKE_MOVED["code/asof_census_20ee/out_pinnable_a4ef.txt"])
    print("  Section 4's witness sees that from the SOURCE ALONE, and those two")
    print("  files are the ground truth it was checked against.")

    banner("6  WHAT THIS RULE CANNOT DO")
    print("  1.  NOT OVERTAKEN PROVES NOTHING.  A transcript goes stale when")
    print("      its CORPUS moves and its producer does not, which is how")
    print("      out_consumers.txt shipped stale at its own commit in 5 of 8")
    print("      versions.  This rule is blind to every one of those.  N35.")
    print()
    print("  2.  OVERTAKEN IS NOT `WRONG`.  The producer's code moved; whether")
    print("      it reaches the printed figure is a question about the figure,")
    print("      and section 4 is a witness rather than an answer.")
    print()
    print("  3.  THE PAIRING IS A CONVENTION.  %d transcript(s) are outside it"
          % (len(got["missed"]) - len(got["wide_all"])))
    print("      even after the widening, and they are counted rather than")
    print("      dropped -- a census that reports a number because it never")
    print("      looked is this directory's oldest named defect.")
    print()
    print("  4.  OVERTAKEN DOES NOT MEAN RE-TAKEABLE.  Section 5's first row is")
    print("      a transcript with a positive witness that CANNOT be re-taken")
    print("      at any revision, because the pin it recommended landed and its")
    print("      subject stopped drifting.  A rule that reported it as work to")
    print("      do would be sending its reader to a run that refuses.")
    print()
    print("  5.  THIS FILE IS OUTSIDE ITS OWN POPULATION, BY ARITHMETIC AND NOT")
    print("      BY RULE.  AS_OF is older than overtaken.py, so out_overtaken.txt")
    print("      is not tracked at the commit it reports on and cannot appear in")
    print("      the %d.  Graded by hand it is NOT OVERTAKEN and cannot become"
          % (len(got["strict"]) + len(got["wide"])))
    print("      so: it is in run_all.sh, which is the whole difference between")
    print("      this page and the five in section 5.")
    print()
    print("  6.  ITS OWN WITNESS IS A WHOLE-OUTPUT MEMBERSHIP TEST, which is")
    print("      mg-9876 section 1's smell, found with a4_sweep.py's OWN")
    print("      detector over this file rather than by eye: `if v not in text`")
    print("      in grade().  IT IS KEPT, and the reason is not that it is")
    print("      harmless -- a literal that appears anywhere in the transcript")
    print("      for an unrelated reason suppresses a real witness.  There is no")
    print("      line-structured alternative that is correct, because a literal")
    print("      is printed INSIDE a longer line; the error direction is the one")
    print("      already declared above (the witness UNDER-states); and renaming")
    print("      the variable to miss the detector while keeping the semantics")
    print("      is exactly what a census that gates teaches its subjects to do.")
    print()
    print("=" * 78)
    print("OVERTAKEN: %d of %d paired transcript(s) at AS_OF %s -- %d LIVE "
          "(%d CODE, %d PROSE-ONLY) and %d ARCHIVAL BY DESIGN."
          % (len(rows), len(got["strict"]) + len(got["wide"]), rev,
             len(live), len(code), len(prose), len(arch)))
    return 0


def _wrap(text, width):
    out, line = [], ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        out.append(line)
    return out


if __name__ == "__main__":
    sys.exit(main(sys.argv))
