#!/bin/bash
# mg-a2bd -- verification of the JOIN-SUPPRESSION theorem (ledger row J).
#
# What this is FOR.  mg-a2bd strikes ledger row G'' from
# docs/OneThird-Hodge-Side-Leverage.md as FALSE (mg-d39d finding A1) and records
# the MECHANISM in its place: Theorem L makes links JOINS, and a join SUPPRESSES
# lambda_2 -- a factor eigenvalue survives scaled by p_j/D < 1.  That mechanism
# is a THEOREM, proved in the deliverable's §6.1; this script CHECKS the proof,
# in the same relation to it that theorems_output.txt §G bears to Theorem G.
# It is not a control battery and contains no mutation: every line here is a
# confirmation, and it is labelled as one.
#
# Pure Python 3, no third-party packages.  The LINK side is measured with
# code/hodge_leverage/links.link_skeleton (brute force from the facet list, no
# use of Theorem L); the FACTOR side is assembled from the factor complexes
# F(P|_B) alone.  The two agree only if J holds.
#
# ~21 seconds on an M-series Mac (measured, not estimated).
# Run from this directory:  bash run_all.sh
#
# Output (committed, and regenerated byte-for-byte by this script -- it carries
# no wall-clock line):
#   out_verify_join.txt
#     J1  the full-spectrum join identity on all 48 846 genuine-join links n<=6
#     J2  the strike: 55 (poset, level) counterexamples to G'', smallest n = 5
#     J3  the smallest counterexample, predicted by J and measured by the
#         deliverable's own local_to_global.gammas
#     J4  row G': gamma_i(A_n) = lambda_2(F(A_{n-i-1})), the max attained
#         EXACTLY at Theorem G's one-big-block face, to A_9
set -e
cd "$(dirname "$0")"

echo "[1/1] Theorem J: join spectra, the G'' strike, and row G' to A_9 ..."
python3 -u verify_join.py > out_verify_join.txt

echo "done."
