"""Independent kernel for the mg-6ad0 audit of mg-af28 / 358beff.

Deliberately disjoint from `code/branching_af28/core_af28.py`:

  * a poset here is `(n, down)` where `down` is a tuple of FROZENSETS of the
    elements strictly below each point -- af28 carries tuples of UP-set bitmasks;
  * order ideals are generated by downward closure of subsets held as
    frozensets, not by bitmask filtering;
  * linear extensions are generated by a queue-based topological search over
    frozensets;
  * f^lambda is computed by the BRANCHING RECURSION f^lam = sum over removable
    corners, never by the hook length formula (af28 uses the hook length formula,
    so the two routes to the same number share nothing);
  * partitions, sub-shapes and skew shapes are rebuilt from scratch.

Pure Python 3, exact integer / Fraction arithmetic only, no dependencies.
"""

from fractions import Fraction
from functools import lru_cache
from itertools import permutations, combinations

# ------------------------------------------------------------------ posets --
# poset = (n, down) with down[i] a frozenset of the elements STRICTLY below i.


def mk_poset(n, strict_pairs):
    """Build a poset from a set of strict pairs (a, b) meaning a < b.
    Transitive closure is taken here; antisymmetry is asserted."""
    below = [set() for _ in range(n)]
    for a, b in strict_pairs:
        below[b].add(a)
    changed = True
    while changed:
        changed = False
        for i in range(n):
            new = set(below[i])
            for j in list(below[i]):
                new |= below[j]
            if new != below[i]:
                below[i] = new
                changed = True
    for i in range(n):
        assert i not in below[i], "not antisymmetric"
        for j in below[i]:
            assert i not in below[j], "not antisymmetric"
    return (n, tuple(frozenset(s) for s in below))


def above(P):
    n, down = P
    up = [set() for _ in range(n)]
    for i in range(n):
        for j in down[i]:
            up[j].add(i)
    return tuple(frozenset(s) for s in up)


def leq(P, a, b):
    return a == b or a in P[1][b]


def ideals(P):
    """All order ideals, as frozensets.  Built by downward closure of every
    subset -- a different route from af28's per-subset bitmask filter."""
    n, down = P
    out = set()
    for k in range(n + 1):
        for S in combinations(range(n), k):
            cl = set(S)
            for i in S:
                cl |= down[i]
            out.add(frozenset(cl))
    return sorted(out, key=lambda s: (len(s), sorted(s)))


def linear_extensions(P):
    """All linear extensions as tuples, by queue-based topological search."""
    n, down = P
    res = []

    def rec(placed, seq):
        if len(seq) == n:
            res.append(tuple(seq))
            return
        for i in range(n):
            if i in placed:
                continue
            if down[i] <= placed:
                rec(placed | {i}, seq + [i])
    rec(frozenset(), [])
    return res


def n_linear_extensions(P):
    """Count linear extensions by memoised counting over ideals -- fast, and a
    different algorithm from enumerating them."""
    n, down = P
    from functools import lru_cache as _lc
    memo = {}

    def cnt(I):
        if len(I) == n:
            return 1
        if I in memo:
            return memo[I]
        t = 0
        for i in range(n):
            if i not in I and down[i] <= I:
                t += cnt(I | {i})
        memo[I] = t
        return t
    return cnt(frozenset())


def _invariant(P):
    """A relabelling-invariant colour for each element, refined to a fixed
    point.  Used only to cut the permutation search in `canon`; correctness of
    `canon` does not depend on it being a strong invariant, only on it being
    invariant."""
    n, down = P
    up = above(P)
    col = [(len(down[i]), len(up[i])) for i in range(n)]
    for _ in range(n):
        new = [(col[i],
                tuple(sorted(col[j] for j in down[i])),
                tuple(sorted(col[j] for j in up[i]))) for i in range(n)]
        keys = {k: r for r, k in enumerate(sorted(set(new)))}
        new = [keys[x] for x in new]
        if new == col:
            break
        col = new
    return col


def canon(P):
    """Canonical form under relabelling: the lexicographically least
    adjacency-matrix bitstring over all relabellings that respect the invariant
    colouring.  A different encoding from af28's canonical form (which minimises
    a tuple of up-set bitmasks), so the two agree only if both are right."""
    n, down = P
    col = _invariant(P)
    # buckets of old labels by colour; a relabelling must send colour class to
    # colour class, and within the canonical string the classes appear in
    # colour order.
    order = sorted(range(n), key=lambda i: col[i])
    groups = []
    k = 0
    while k < n:
        m = k
        while m < n and col[order[m]] == col[order[k]]:
            m += 1
        groups.append(order[k:m])
        k = m
    best = None

    def rec(gi, assign):
        nonlocal best
        if gi == len(groups):
            inv = assign          # inv[newlabel] = oldlabel
            s = "".join("1" if (inv[i] in down[inv[j]]) else "0"
                        for i in range(n) for j in range(n))
            if best is None or s < best:
                best = s
            return
        for p in permutations(groups[gi]):
            rec(gi + 1, assign + list(p))
    rec(0, [])
    return (n, best)


def all_posets(n):
    """Every isomorphism class of poset on n elements.

    Route: enumerate NATURALLY LABELLED posets -- choose, for i = 0, 1, ..., n-1
    in turn, the strict down-set D_i of i inside {0, ..., i-1}, subject to
    D_i being down-closed (j in D_i implies D_j subset D_i).  Every finite poset
    admits a natural labelling, so every isomorphism class is produced; the
    result is deduplicated by `canon`.

    This is a different enumeration route from af28's `poset_classes`, which
    adjoins a new MAXIMAL element above an order ideal of a poset on n-1
    elements.  Both are certified against A000112 in selftest6ad0.py.
    """
    if n == 0:
        return [(0, ())]
    out = {}

    def rec(i, downs):
        if i == n:
            P = (n, tuple(frozenset(s) for s in downs))
            out.setdefault(canon(P), P)
            return
        prev = list(range(i))
        for mask in range(1 << i):
            D = {t for t in prev if mask >> t & 1}
            if all(downs[j] <= D for j in D):
                rec(i + 1, downs + [D])
    rec(0, [])
    return sorted(out.values(), key=lambda P: sorted(sorted(s) for s in P[1]))


# ------------------------------------------------------------------- moves --
# A move is a tuple of disjoint nonempty frozensets covering [n], in block
# order, with i < j in P implying block(i) <= block(j).


def moves(P):
    """P-compatible ordered set partitions, generated block by block by
    peeling off an ideal-difference.  (Equivalent to chains in J(P); generated
    here directly from the compatibility condition on the remaining elements.)"""
    n, down = P
    res = []

    def rec(done, blocks):
        if len(done) == n:
            res.append(tuple(blocks))
            return
        rest = [i for i in range(n) if i not in done]
        # the next block B must be an antichain-free... no: B may be any
        # nonempty subset of `rest` all of whose P-predecessors are in done|B.
        m = len(rest)
        for mask in range(1, 1 << m):
            B = frozenset(rest[t] for t in range(m) if mask >> t & 1)
            ok = all(down[i] <= (done | B) for i in B)
            if ok:
                rec(done | B, blocks + [B])
    rec(frozenset(), [])
    return res


def mprod(x, y):
    out = []
    for B in x:
        for C in y:
            D = B & C
            if D:
                out.append(D)
    return tuple(out)


def supp(x):
    return frozenset(x)


def act(x, c):
    out = []
    for B in x:
        for e in c:
            if e in B:
                out.append(e)
    return tuple(out)


# ------------------------------------------------------------- Young side ---


def partitions(n):
    if n == 0:
        return [()]
    out = []

    def rec(left, cap, cur):
        if left == 0:
            out.append(tuple(cur))
            return
        for p in range(min(cap, left), 0, -1):
            cur.append(p)
            rec(left - p, p, cur)
            cur.pop()
    rec(n, n, [])
    return out


def contains(mu, lam):
    """mu subset of lam as Young diagrams."""
    if len(mu) > len(lam):
        return False
    return all(mu[k] <= lam[k] for k in range(len(mu)))


def cells(lam):
    return [(i, j) for i, p in enumerate(lam) for j in range(p)]


def straight_poset(lam):
    """D_lambda as a (n, down) poset; cells ordered componentwise."""
    cs = cells(lam)
    n = len(cs)
    pairs = []
    for a in range(n):
        for b in range(n):
            if a == b:
                continue
            (ia, ja), (ib, jb) = cs[a], cs[b]
            if ia <= ib and ja <= jb:
                pairs.append((a, b))
    return mk_poset(n, pairs), cs


def skew_poset(lam, mu):
    """The cell poset of the skew shape lam/mu (mu contained in lam)."""
    assert contains(mu, lam)
    mm = list(mu) + [0] * (len(lam) - len(mu))
    cs = [(i, j) for i, p in enumerate(lam) for j in range(mm[i], p)]
    n = len(cs)
    pairs = []
    for a in range(n):
        for b in range(n):
            if a == b:
                continue
            (ia, ja), (ib, jb) = cs[a], cs[b]
            if ia <= ib and ja <= jb:
                pairs.append((a, b))
    return mk_poset(n, pairs), cs


@lru_cache(maxsize=None)
def f_lambda(lam):
    """f^lambda by the BRANCHING RECURSION: f^lam = sum over removable corners
    of f^(lam minus that corner).  Never the hook length formula."""
    if sum(lam) == 0:
        return 1
    tot = 0
    for i in range(len(lam)):
        if i + 1 == len(lam) or lam[i] > lam[i + 1]:
            nu = list(lam)
            nu[i] -= 1
            while nu and nu[-1] == 0:
                nu.pop()
            tot += f_lambda(tuple(nu))
    return tot


# ---------------------------------------------------------- lattice checks --


def is_lattice_and_distributive(elems, le):
    """(is_lattice, is_distributive, witness) for a finite poset given by a
    <= predicate.  Uses meet/join tables built by minimal-upper-bound search."""
    n = len(elems)
    L = [[le(a, b) for b in elems] for a in elems]
    join = [[None] * n for _ in range(n)]
    meet = [[None] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            ub = [k for k in range(n) if L[i][k] and L[j][k]]
            lb = [k for k in range(n) if L[k][i] and L[k][j]]
            mins = [k for k in ub if all(m == k or not L[m][k] for m in ub)]
            maxs = [k for k in lb if all(m == k or not L[k][m] for m in lb)]
            if len(mins) != 1 or len(maxs) != 1:
                return (False, None, None)
            join[i][j] = mins[0]
            meet[i][j] = maxs[0]
    for a in range(n):
        for b in range(n):
            for c in range(n):
                if meet[a][join[b][c]] != join[meet[a][b]][meet[a][c]]:
                    return (True, False, (elems[a], elems[b], elems[c]))
    return (True, True, None)


def poset_of_ideals(P):
    """J(P) as an abstract poset in this file's representation."""
    ids = ideals(P)
    idx = {I: k for k, I in enumerate(ids)}
    pairs = [(idx[A], idx[B]) for A in ids for B in ids if A < B]
    return mk_poset(len(ids), pairs), ids


def rank_exact(M):
    A = [[Fraction(x) for x in row] for row in M]
    rows = len(A)
    cols = len(A[0]) if A else 0
    r = 0
    for c in range(cols):
        piv = next((i for i in range(r, rows) if A[i][c] != 0), None)
        if piv is None:
            continue
        A[r], A[piv] = A[piv], A[r]
        pv = A[r][c]
        for i in range(rows):
            if i != r and A[i][c] != 0:
                f = A[i][c] / pv
                for j in range(c, cols):
                    A[i][j] -= f * A[r][j]
        r += 1
        if r == rows:
            break
    return r
