#!/bin/sh
# mg-5f9a: closing mg-1c80's F1 -- regenerate this landing's transcript.
#
# Pure Python 3, no third-party packages.  Measured runtime 2026-07-30 on a 2024
# laptop: 38 s total -- d1 0.6 s, d2 17 s (six full control batteries, two of
# them built from `main`'s sources), d3 20 s (two more, plus two runs of
# mg-da45's landing verifier over the whole 86-poset population).
#
# WHAT IT IS FOR.  mg-da45 printed a gate name as the reason its rows answered
# as they did.  mg-1c80 deleted that gate from the predicate and the artifact
# regenerated BYTE-IDENTICALLY, which is the proof that the name was not what
# the code was doing.  This landing does not write a third reason: the predicate
# now RETURNS the gate it returned at and the number of signs it read, so the
# printed reason is produced by the code path.
#
# d2 is the test that has to pass, and it runs on BOTH sides of the repair --
# mg-1c80's deletion re-run at `main` (predicted: byte-identical) and the
# corresponding deletion here (predicted: the artifact CHANGES, with no scored
# row moving).  Every prediction in d2 and d3 was registered before the runs and
# is printed above the results.
#
# Nothing under ../face_geometry is written by any of these: every mutation is
# applied to a copy in a temporary directory and every battery run captures
# stdout instead of tee-ing it.
#
# NOT `python3 x.py | tee out.txt`, and that is deliberate.  A pipeline's exit
# status in POSIX sh is the LAST command's, so `tee` succeeding would mask a
# verifier exiting 1 -- a committed transcript saying BROKEN under a run_all.sh
# that exited 0.  mg-f922 found exactly that shape in this repository.  Here the
# status is captured and re-raised, so `set -e` below is the whole failure
# protocol: if any part prints a false claim, this script fails.
set -e
cd "$(dirname "$0")"

run() {
    out=$1
    shift
    set +e
    python3 "$@" > "$out" 2>&1
    status=$?
    set -e
    cat "$out"
    return $status
}

echo "== d1: the gate label is returned BY the predicate =="
run out_d1_trace.txt d1_trace.py 5

echo
echo "== d2: THE DELETION TEST, before and after =="
run out_d2_deletion.txt d2_deletion.py

echo
echo "== d3: reintroduction, and whether anything sees it =="
run out_d3_reintroduction.txt d3_reintroduction.py
