#!/bin/sh
# mg-5f9a: closing mg-1c80's F1 -- regenerate this landing's transcript.
#
# Pure Python 3, no third-party packages.  Measured runtime 2026-07-30 on a 2024
# laptop: 112 s total -- d1 0.6 s, d2 40 s (fourteen full control batteries: ten
# on this tree and on the PRE-REPAIR commit's sources, four more on the
# TWO-RETURN commit for the per-return section), d3 15 s (two more, plus two runs
# of mg-da45's landing verifier over the whole 86-poset population), d4 55 s
# (mg-d0e2's own e1, e2 and e3 and mg-e7bc's g1, g2 and g3, all run unmodified as
# subprocesses, two of them against a pinned commit materialised with
# `git archive`).  72 claims, 0 BROKEN: d1 17, d2 33, d3 6, d4 16.
#
# mg-04a8 added d4 and rewrote d2's label check.  d2's BEFORE half now reads a
# PINNED COMMIT rather than `main`: once mg-5f9a merged, "main's artifact
# regenerates from main's sources" was a statement about this tree, and the
# deletion it then attempted did not even apply -- the shipped file stopped at
# `anchor occurs 0 times`.  A check pinned to a branch asks about whatever that
# branch holds today.
#
# mg-9220 made the deletion test PER RETURN.  mg-e7bc found that d2 deleted the
# `shape` gate's TWO return statements together and its "the artifact CHANGES"
# was read as a statement about each -- and deleting the FIRST alone left the
# artifact byte-identical.  Every mutation now declares the unit it removes, the
# returns it takes out are counted from its own patch text, d1 checks the table
# against the SOURCE (every rejecting return deleted by exactly one mutation),
# and the inert return is GONE: it was merged into the second's condition rather
# than covered by a new row.  Two independent instruments were anchored to the
# text it removed; d4 runs each against this tree AND against the pinned commit
# it was written for, and scores both.
#
# WHAT IT IS FOR.  mg-da45 printed a gate name as the reason its rows answered
# as they did.  mg-1c80 deleted that gate from the predicate and the artifact
# regenerated BYTE-IDENTICALLY, which is the proof that the name was not what
# the code was doing.  This landing does not write a third reason: the predicate
# now RETURNS the gate it returned at and the number of signs it read, so the
# printed reason is produced by the code path.
#
# d2 is the test that has to pass, and it runs on BOTH sides of the repair --
# mg-1c80's deletion re-run at `main` (predicted: byte-identical) and the
# corresponding deletion here (predicted: the artifact CHANGES, with no scored
# row moving).  Every prediction in d2 and d3 was registered before the runs and
# is printed above the results.
#
# Nothing under ../face_geometry is written by any of these: every mutation is
# applied to a copy in a temporary directory and every battery run captures
# stdout instead of tee-ing it.
#
# NOT `python3 x.py | tee out.txt`, and that is deliberate.  A pipeline's exit
# status in POSIX sh is the LAST command's, so `tee` succeeding would mask a
# verifier exiting 1 -- a committed transcript saying BROKEN under a run_all.sh
# that exited 0.  mg-f922 found exactly that shape in this repository.  Here the
# status is captured and re-raised, so `set -e` below is the whole failure
# protocol: if any part prints a false claim, this script fails.
set -e
cd "$(dirname "$0")"

run() {
    out=$1
    shift
    set +e
    python3 "$@" > "$out" 2>&1
    status=$?
    set -e
    cat "$out"
    return $status
}

echo "== d1: the gate label is returned BY the predicate =="
run out_d1_trace.txt d1_trace.py 5

echo
echo "== d2: THE DELETION TEST, before and after =="
run out_d2_deletion.txt d2_deletion.py

echo
echo "== d3: reintroduction, and whether anything sees it =="
run out_d3_reintroduction.txt d3_reintroduction.py

echo
echo "== d4: mg-d0e2's OWN deletion test, unmodified, against the repair =="
run out_d4_auditor_rerun.txt d4_auditor_rerun.py
