#!/usr/bin/env python3
"""mg-16eb — the eight new mutations, plus the RECOVERY demonstration.

Section 1 runs the eight rows of `mutations16eb.py`, each carrying the exit code predicted
before the run.

Section 2 is a two-phase construction rather than a row, because the claim it tests is not
about one exit code but about a DOCUMENTED RECOVERY PATH.  `delta_control.py` publishes
exit 2 as *"re-baseline this instrument, record the new figure, and say which commit moved
it"* and exit 1 as damage.  Section 2 takes C1 — an ordinary code example added to a cited
section — follows that recovery path to the letter with the instrument's own
`--emit-baseline`, and runs the control again.
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import harness16eb as H              # noqa: E402
import mutations16eb as M            # noqa: E402


def _splice(control_src, name, new_block):
    """Replace the `name = {...}` literal in delta_control.py's source with `new_block`.

    Matched from the assignment line to the first line that is exactly `}` — the file's own
    formatting, which `--emit-baseline` reproduces, so this is a substitution of like for
    like and not a reformat."""
    start = control_src.index(f"\n{name} = {{\n") + 1
    end = control_src.index("\n}\n", start) + 3
    return control_src[:start] + new_block.rstrip("\n") + "\n" + control_src[end:]


def _emit_baseline(repo):
    """The instrument's own documented recovery command, run against the working tree."""
    proc = subprocess.run(
        [sys.executable, H.path(H.CONTROL), "--emit-baseline"],
        cwd=repo, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"--emit-baseline exited {proc.returncode}:\n{proc.stdout}"
                         f"\n{proc.stderr}")
    out = proc.stdout
    blocks = {}
    for name in ("DELEGATED", "DELEGATED_PRESENTATION"):
        m = re.search(r"^%s = \{$" % name, out, re.M)
        if not m:
            raise SystemExit(f"--emit-baseline printed no {name} table")
        end = out.index("\n}\n", m.start()) + 3
        blocks[name] = out[m.start():end]
    # The DELEGATED regex above also matches the DELEGATED_PRESENTATION line's prefix if the
    # anchors were sloppy; they are not (`^NAME = {$`), and this asserts it.
    if blocks["DELEGATED"].startswith("DELEGATED_PRESENTATION"):
        raise SystemExit("baseline extraction matched the wrong table")
    return blocks


def recovery_demonstration(tree):
    """C1, then the documented recovery, then the control again."""
    print("=" * 96)
    print("2.  THE DOCUMENTED RECOVERY PATH, FOLLOWED TO THE LETTER, ON C1")
    print("=" * 96)
    print("  delta_control.py's header: exit 2 means 'Re-baseline this instrument, record")
    print("  the new figure, and say which commit moved it'; exit 1 means a region is NO")
    print("  LONGER PRESENTED TO A READER.  C1 adds a closed, fully visible code example to")
    print("  cited section H3.  What follows is the repo's own recovery command applied to")
    print("  it, with no hand edits, and the control re-run on the result.")
    print()
    mutated = M.c1_code_example_inside_a_cited_section(tree.orig[M.ATTEMPT])
    control0 = tree.orig[M.CONTROL]
    try:
        H.write(M.ATTEMPT, mutated)
        before = subprocess.run([sys.executable, H.path(H.CONTROL)], cwd=H.REPO,
                                capture_output=True, text=True)
        print(f"  before re-baselining        exit {before.returncode}")
        blocks = _emit_baseline(H.REPO)
        rebaselined = control0
        for name in ("DELEGATED", "DELEGATED_PRESENTATION"):
            rebaselined = _splice(rebaselined, name, blocks[name])
        if rebaselined == control0:
            raise SystemExit("re-baselining changed nothing — the demonstration is inert")
        H.write(M.CONTROL, rebaselined)
        after = subprocess.run([sys.executable, H.path(H.CONTROL)], cwd=H.REPO,
                               capture_output=True, text=True)
        print(f"  after  re-baselining        exit {after.returncode}   "
              f"(PREDICTED BEFORE THE RUN: exit 1)")
        print()
        lines = [ln for ln in after.stdout.splitlines()
                 if "PRESENTED to a reader" in ln or "SHOWN NOTHING" in ln
                 or "state " in ln and "fenced" in ln]
        for ln in lines:
            print("     " + ln.strip())
        print()
        if after.returncode == 1:
            print("  THE RECOVERY PATH DOES NOT RECOVER.  Every digest the instrument asked")
            print("  for has been regenerated by the instrument itself and pasted back, and")
            print("  the control still reports the section as one a reader is shown nothing")
            print("  of — while both renderers show every line of it (render16eb.py).")
        else:
            print("  The recovery path recovers; this audit predicted it would not.")
        print()
        return after.returncode
    finally:
        H.write(M.ATTEMPT, tree.orig[M.ATTEMPT])
        H.write(M.CONTROL, control0)
        for rel in (M.ATTEMPT, M.CONTROL):
            if H.sha(H.read(rel)) != tree.sha0[rel]:
                raise SystemExit(f"HARD ABORT: {rel} did not restore.  "
                                 f"git -C {H.REPO} checkout -- {rel}")


def main():
    tree = H.Tree([M.ATTEMPT, M.CONTROL])
    rows = [(rid, surface, what, want,
             (lambda rel, fn: lambda orig: {rel: fn(orig[rel])})(rel, fn))
            for rid, surface, what, want, rel, fn in M.ROWS]
    print("1.  EIGHT MUTATIONS mg-0049's AUTHOR NEVER SAW")
    got = tree.battery(
        rows,
        "mg-16eb — EIGHT NEW ROWS ON THE SURFACE mg-0049's REPAIR CREATED",
        "A1 A2 A3 A5 mutate the INSTRUMENT (delta_control.py); B1 B2 B3 C1 mutate\n"
        f"{M.ATTEMPT}, the file the certified cell points at.\n"
        "Nothing here mutates STATE.md or the state-history README.")
    rec = recovery_demonstration(tree)

    print("=" * 96)
    print("WHAT THESE ROWS SAY")
    print("=" * 96)
    surprises = [rid for rid, _s, _w, want, _r, _f in M.ROWS if got[rid] != want]
    print(f"  {len(M.ROWS) - len(surprises)} of {len(M.ROWS)} behaved as predicted; "
          f"{len(surprises)} did not.  Recovery demonstration: exit {rec}.")
    print()
    print(f"  A1 exit {got['A1']}, A2 exit {got['A2']}, against A3 exit {got['A3']} and A5"
          f" exit {got['A5']}.")
    print("     delta_control.py's comment over DELEGATED_PRESENTATION says the two tables")
    print("     'cannot drift apart quietly in EITHER direction'.  One direction is real")
    print("     (A3).  The other is not: nothing iterates the new table, so a row in it and")
    print("     in nothing else — or a whole target file — is never visited.  A5 shows the")
    print("     table mg-bee1 added does NOT have this hole: its keys are cross-checked")
    print("     against the sections the certified text actually cites.  The repair added a")
    print("     second pinned table without the cross-check the first one has.")
    print()
    print(f"  B1 exit {got['B1']}, against B2 exit {got['B2']}.")
    print("     Two cited sections exchanged, no byte of either changed, both still prose,")
    print("     both under the certified heading path — and a reader is shown them in the")
    print("     other order.  On the two files the instrument READS, a certified region's")
    print("     ordinal among the blocks of its section IS certified.  On the file it POINTS")
    print("     AT, `position` is inert by construction.  B2 is the control: the record is")
    print("     read, and it is `position` specifically that carries nothing here.")
    print()
    print(f"  B3 exit {got['B3']}.")
    print("     Exit 2 is DRIFT — 're-baseline and record the new figure'.  Both renderers")
    print("     put all five cited sections inside an unclosed <details> with no `open`")
    print("     attribute, so a reader is shown a closed widget and no cited section at all.")
    print("     That is R1's and R8's outcome, which the repair classifies exit 1 as damage.")
    print()
    print(f"  C1 exit {got['C1']}, recovery exit {rec}.")
    print("     A code example inside a cited section is reported as a section the reader is")
    print("     SHOWN NOTHING OF, and the instrument's own re-baseline does not clear it.")
    print("=" * 96)
    return 0


if __name__ == "__main__":
    sys.exit(main())
