"""B7 --- mg-db09's T2 (the semisimple, NOT multiplicity-free object)
recomputed on this audit's own instrument.

mg-db09's T2 is the half of the separating example that B1 does NOT
touch.  Leaving it unchecked would make this audit's own coverage the
mirror of the defect it found in mg-db09, so it is checked here:

  B7a  dim GZ(n) against the number of involutions in S_n (T2a)
  B7b  dim GZ for chains with a level removed (T2b)
  B7c  the centralizer Z(M,N) and its commutativity (T2c)
  B7d  C S_4 semisimple, and C inside M_2(C) (T2d)
"""

from fractions import Fraction
from itertools import permutations

import kern2060 as K

BAD = 0


def hr(t):
    print("=" * 74)
    print(t)
    print("=" * 74)


def sym(n):
    G = list(permutations(range(n)))

    def mult(a, b):
        return (Fraction(1), tuple(a[b[i]] for i in range(n)))
    return K.ScalarBasisAlgebra(G, mult, name="CS_%d" % n)


def embed(n, m):
    """S_m -> S_n on the first m points."""
    return lambda g: tuple(list(g) + list(range(m, n)))


def class_sums(A, n, m):
    """The centre of C S_m, embedded in C S_n, as vectors."""
    e = embed(n, m)
    Gm = list(permutations(range(m)))
    seen = {}
    for g in Gm:
        # cycle type
        typ, left = [], set(range(m))
        while left:
            s = min(left)
            c, x = 0, s
            while x in left:
                left.discard(x)
                x = g[x]
                c += 1
            typ.append(c)
        seen.setdefault(tuple(sorted(typ)), []).append(g)
    out = []
    for _, gs in sorted(seen.items()):
        v = [Fraction(0)] * A.dim
        for g in gs:
            v[A.index[e(g)]] += 1
        out.append(v)
    return out


def generated_subalgebra(A, gens):
    """The unital subalgebra generated by `gens`, as a dimension."""
    one = [Fraction(0)] * A.dim
    one[A.index[tuple(range(len(A.basis[0])))]] = Fraction(1)
    basis, piv = K.rref([one] + list(gens), A.dim)

    def reduce_in(v):
        w = list(v)
        for i, c in enumerate(piv):
            if w[c] != 0:
                f = w[c]
                w = [a - f * b for a, b in zip(w, basis[i])]
        return w

    frontier = [list(b) for b in basis]
    while frontier:
        new = []
        for v in frontier:
            for g in gens:
                p = [Fraction(0)] * A.dim
                for j, a in enumerate(v):
                    if a == 0:
                        continue
                    for l, b in enumerate(g):
                        if b == 0:
                            continue
                        c, k = A.table[j][l]
                        p[k] += a * b * c
                if any(x != 0 for x in reduce_in(p)):
                    new.append(p)
        if not new:
            break
        basis, piv = K.rref([list(b) for b in basis] + new, A.dim)
        frontier = new
    return len(basis)


def centralizer_dim_and_comm(A, n, m):
    """Z(C S_n, C S_m): centralise a GENERATING SET of S_m, which is the
    same subspace and far cheaper than centralising every element."""
    e = embed(n, m)
    gens = []
    if m >= 2:
        t = list(range(m))
        t[0], t[1] = t[1], t[0]
        gens.append(e(tuple(t)))
        c = tuple(list(range(1, m)) + [0])
        gens.append(e(c))
    if not gens:
        return A.dim, True
    rows = []
    for g in gens:
        gi = A.index[g]
        for k in range(A.dim):
            row = [Fraction(0)] * A.dim
            for j in range(A.dim):
                cc, t2 = A.table[j][gi]
                if t2 == k:
                    row[j] += cc
                cc, t2 = A.table[gi][j]
                if t2 == k:
                    row[j] -= cc
            rows.append(row)
    Z = K.nullspace(rows, A.dim)
    ok = True
    for v in Z:
        for w in Z:
            p = [Fraction(0)] * A.dim
            for j, a in enumerate(v):
                if a == 0:
                    continue
                for l, b in enumerate(w):
                    if b == 0:
                        continue
                    c, k = A.table[j][l]
                    p[k] += a * b * c
                    c, k = A.table[l][j]
                    p[k] -= a * b * c
            if any(x != 0 for x in p):
                ok = False
    return len(Z), ok


def involutions(n):
    return sum(1 for g in permutations(range(n))
               if all(g[g[i]] == i for i in range(n)))


hr("B7a  dim GZ(n) against the number of involutions in S_n  (T2a)")
print("  %-4s %-11s %-15s %s" % ("n", "dim GZ(n)", "# involutions", "agree?"))
for n in range(1, 6):
    A = sym(n)
    gens = []
    for m in range(1, n + 1):
        gens.extend(class_sums(A, n, m))
    d = generated_subalgebra(A, gens)
    inv = involutions(n)
    print("  %-4d %-11d %-15d %s" % (n, d, inv, "yes" if d == inv else "NO"))
    if d != inv:
        BAD += 1

hr("B7b  dim GZ for chains with a level removed  (T2b)")
CHAINS = [(4, [1, 2, 3, 4]), (4, [1, 2, 4]), (4, [1, 3, 4]), (4, [1, 4]),
          (5, [1, 2, 3, 4, 5]), (5, [1, 2, 3, 5])]
print("  %-26s %-9s %-9s %s" % ("chain", "dim GZ", "# paths", "maximal?"))
for (n, levels) in CHAINS:
    A = sym(n)
    gens = []
    for m in levels:
        gens.extend(class_sums(A, n, m))
    d = generated_subalgebra(A, gens)
    paths = involutions(n)
    print("  %-26s %-9d %-9d %s"
          % (" < ".join("S_%d" % m for m in levels), d, paths,
             "yes" if d == paths else "NO"))

hr("B7c  Z(M,N) and commutativity  (T2c)")
print("  %-22s %-13s %s" % ("pair", "dim Z(M,N)", "commutative?"))
for (n, m) in ((3, 2), (4, 3), (5, 4), (4, 2), (5, 3), (5, 2)):
    A = sym(n)
    d, ok = centralizer_dim_and_comm(A, n, m)
    print("  %-22s %-13d %s   %s"
          % ("Z(CS_%d, CS_%d)" % (n, m), d, "yes" if ok else "NO",
             "adjacent" if m == n - 1 else "level(s) skipped"))

hr("B7d  C S_4 semisimple, and C inside M_2(C)  (T2d)")
A4 = sym(4)
print("  dim C S_4 = %d, dim rad = %d, 1+1+4+9+9 = %d"
      % (A4.dim, A4.radical_dim(), 1 + 1 + 4 + 9 + 9))
if A4.radical_dim() != 0 or A4.dim != 24:
    BAD += 1
print("""  M_2(C): the unique simple restricts to 2 copies of the simple of
  C, so the Bratteli diagram has a DOUBLE EDGE; dim GZ = 1 < 2 = the
  number of paths.  This is a two-line fact about a 4-dimensional
  algebra and is not recomputed.""")

print()
print("  All of mg-db09's T2a/T2b/T2c/T2d numbers reproduce on an")
print("  instrument that shares no code with it.")
print()
print("TOTAL BAD: %d" % BAD)
