#!/bin/bash
# mg-d39d -- independent audit instrument for the mg-a806 landing.
#
# Pure Python 3, no third-party packages.  No code is shared with
# code/hodge_leverage/ or code/hodge_leverage_audit_86a3/: the poset
# enumeration, the compatible face complex, the links, the induced weights, the
# eigenvalue routine, the linear extensions, the semigroup action and the
# Brown-walk witnesses are all rebuilt here from their definitions.
#
# Total ~18 seconds on an M-series Mac (measured, not estimated).
# Run from this directory:  bash run_all.sh
#
# Outputs (committed, and regenerated byte-for-byte by this script -- there are
# no wall-clock lines in any of them):
#   out_gpp.txt             -- ledger row G'' is FALSE (finding A1)
#   out_vk_infinite.txt     -- V_k is a Brown walk for EVERY k (finding A3)
#   out_antichain_scope.txt -- "all antichains n >= 3" is a theorem, A_6 checked (A6)
#   out_n6_complete.txt     -- the n = 6 level completed: NOT 305 / vacuous 1 / undecided 12
set -e
cd "$(dirname "$0")"

echo "[1/4] G'' -- every poset n <= 6, every level, every face ..."
python3 -u audit_gpp.py 6 > out_gpp.txt

echo "[2/4] V_k, exact rational witness, k = 1..8 ..."
python3 -u audit_vk_infinite.py > out_vk_infinite.txt

echo "[3/4] the antichain clause: proof core n = 3..7, full test on A_6 ..."
python3 -u audit_antichain_scope.py > out_antichain_scope.txt

echo "[4/4] the §9.4 sufficient test on ALL 318 posets at n = 6 ..."
python3 -u audit_n6_complete.py 6 > out_n6_complete.txt

echo "done."
