"""p2 -- alpha RESTRICTED TO THE PRIMITIVE CLASS.  Ticket steps 3 and 4.

Daniel's objection: mg-409a's attainment witness Z_n is an ORDINAL SUM, hence decomposable,
while counterexamples to (1/3)-(2/3) are PRIMITIVE.  So:

  * is alpha = 1 attained by any PRIMITIVE poset at all?           -- EXACT test, p2.2
  * if not, what IS the primitive supremum?                        -- measured + certified

"Primitive" is ambiguous and PREDICTIONS.md E2 says so, so all three notions are carried:
  PRIME                    -- no module of size 2..n-1 (modular/substitution decomposition)
  ORDINAL-INDECOMPOSABLE   -- no proper down-set lying entirely below its complement
  CONNECTED                -- comparability graph connected
PRIME is the strongest and is the one Daniel's word most plausibly means.  Z_n fails all
three tests (p0.3 and p2.0), which is the objection's premise and is checked, not assumed.

POPULATIONS.  n <= 6: EVERY iso class (1,2,5,16,63,318 -- p0.1 is the warrant).
n = 7: every PRIMITIVE iso class (234), generated by the same complete augmentation and
then filtered, so the primitive sub-population is exhaustive even though the full n = 7
population is not enumerated here.
"""

import os
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import libf5be as F  # noqa: E402
import lib409a as L  # noqa: E402

ok = True


def fmt(n, lt):
    return "{" + ", ".join(f"{a}<{b}" for (a, b) in sorted(lt)) + "}" if lt else "{}(antichain)"


def cover(n, lt):
    """Cover relations only -- a readable presentation of the poset."""
    cov = [(a, b) for (a, b) in lt
           if not any((a, c) in lt and (c, b) in lt for c in range(n))]
    return "{" + ", ".join(f"{a}<{b}" for (a, b) in sorted(cov)) + "}" if cov else "{} (antichain)"


# --------------------------------------------------------------------------------------
F.banner("p2.0  THE OBJECTION'S PREMISE -- Z_n really is decomposable, on all three notions")

for n in (4, 6, 8):
    z = L.two_block_ordinal_sum(n)
    c = F.classify(n, z)
    ok &= F.verdict(not c["prime"] and not c["ordinal_indecomposable"],
                    f"Z_{n}: prime={c['prime']} ordinal-indecomposable={c['ordinal_indecomposable']} "
                    f"connected={c['connected']}")
print("""
      So Daniel is right about the witness: mg-409a's attainment example is outside the
      class counterexamples live in, on every reading of "primitive".  Everything below is
      about whether that matters.""")

# --------------------------------------------------------------------------------------
F.banner("p2.1  THE CENSUS -- every iso class to n = 6, plus every PRIMITIVE class at n = 7")

POPS = []
for n in (2, 3, 4, 5, 6):
    POPS.append((n, "ALL iso classes", F.posets_up_to_iso(n), False))

# n = 7 primitives, by complete augmentation from the 318 n=6 classes then filtering
cands, seen, prim7 = [], set(), []
for lt in F.posets_up_to_iso(6):
    for S in F.down_sets(6, lt):
        rel = frozenset(set(lt) | {(v, 6) for v in S})
        if not F.is_prime(7, rel):
            continue
        k = F.canonical(7, rel)
        if k in seen:
            continue
        seen.add(k)
        prim7.append(rel)
POPS.append((7, "PRIMITIVE iso classes only", prim7, True))

rows = []
for n, label, posets, prim_only in POPS:
    for lt in posets:
        LEs = L.linear_extensions(n, lt)
        if len(LEs) < 2:
            continue                      # a chain: |L(P)| = 1, outside mg-409a's theorem
        c = F.classify(n, lt)
        st = F.all_pair_stats(n, lt, LEs)
        one_exact, wit = F.alpha_is_one_exact(LEs, n)
        rows.append({
            "n": n, "lt": lt, "N": len(LEs), "prim_only": prim_only,
            "prime": F.is_primitive_proper(n, lt),
            "prime_literal": c["prime"], "ordind": c["ordinal_indecomposable"],
            "conn": c["connected"],
            "alpha": F.alpha_power(LEs, n),
            "alpha_is_one": one_exact,
            "delta": F.delta_of(st) if st else None,
            "mu": F.mu_of(st) if st else None,
            "t1": F.chain_bound(st)[0] if st else None,
            "t2": F.chain_bound(st)[1] if st else None,
        })

print(f"  {'n':>2}  {'population':<28} {'posets':>7} {'PRIMITIVE':>10} {'prime-lit':>10} "
      f"{'ord-ind':>8} {'conn':>6}")
for n, label, posets, prim_only in POPS:
    R = [r for r in rows if r["n"] == n]
    print(f"  {n:>2}  {label:<28} {len(R):>7} {sum(r['prime'] for r in R):>10} "
          f"{sum(r['prime_literal'] for r in R):>10} "
          f"{sum(r['ordind'] for r in R):>8} {sum(r['conn'] for r in R):>6}")
print("""      (posets with |L(P)| = 1 -- the chains -- are excluded throughout: mg-409a's
       theorem is stated for |L(P)| >= 2 and a chain has no incomparable pair at all.
       PRIMITIVE = prime AND n >= 4; prime-lit = the literal no-nontrivial-module test,
       which n <= 2 passes vacuously.  The two columns differ in exactly one place and
       p2.2 is about that place.)""")

# --------------------------------------------------------------------------------------
F.banner("p2.2  IS alpha = 1 ATTAINED BY ANY PRIMITIVE POSET?  (ticket step 4) -- EXACT")

print(f"  {'n':>2}  {'attain alpha=1':>14}  {'of which PRIMITIVE':>19}  {'prime-lit':>10}  "
      f"{'ord-indec':>10}  {'connected':>10}")
any_prime_one = []
any_literal_one = []
for n, label, posets, prim_only in POPS:
    R = [r for r in rows if r["n"] == n]
    ones = [r for r in R if r["alpha_is_one"]]
    pones = [r for r in ones if r["prime"]]
    lones = [r for r in ones if r["prime_literal"]]
    any_prime_one += pones
    any_literal_one += lones
    print(f"  {n:>2}  {len(ones):>14}  {len(pones):>19}  {len(lones):>10}  "
          f"{sum(r['ordind'] for r in ones):>10}  {sum(r['conn'] for r in ones):>10}")

ok &= F.verdict(len(any_prime_one) == 0,
                "NO PRIMITIVE POSET ATTAINS alpha = 1, at any n in range",
                f"({len(any_prime_one)} found)")
for r in any_prime_one[:5]:
    print("      PRIMITIVE WITH alpha=1:", r["n"], cover(r["n"], r["lt"]))

print(f"""
      KEPT, BECAUSE IT IS THE ONE PLACE THE TWO DEFINITIONS DISAGREE AND MY FIRST RUN
      REPORTED IT AS A REFUTATION.  Under the LITERAL no-nontrivial-module test there is
      exactly {len(any_literal_one)} attaining poset, and it is""")
for r in any_literal_one:
    print(f"          n = {r['n']}:  {cover(r['n'], r['lt'])}   |L| = {r['N']}")
print("""      -- the 2-element ANTICHAIN, prime only because a module of size 2..n-1 cannot
      exist when n = 2.  It is not primitive in any sense the objection is about, and it is
      not an independent witness either: it is precisely the BLOCK that Z_n is the ordinal
      sum OF.  So the literal reading's single attainer is the atom of the decomposable
      attainer, which is the opposite of a counterexample to the finding.""")
ok &= F.verdict(all(r["n"] <= 2 for r in any_literal_one),
                "every literal-prime attainer has n <= 2, i.e. is vacuously prime",
                f"max n = {max((r['n'] for r in any_literal_one), default=0)}")

# What DOES attain it?  Report the shapes, since the ticket asks whether Z_n was merely
# the convenient witness.
F.banner("p2.2b  WHAT ATTAINS alpha = 1 -- the shape of the whole attaining set")
for n, label, posets, prim_only in POPS:
    if prim_only:
        continue
    ones = [r for r in rows if r["n"] == n and r["alpha_is_one"]]
    if not ones:
        continue
    print(f"  n = {n}:")
    for r in ones:
        print(f"      {cover(n, r['lt']):<52} |L|={r['N']:>4}  ord-ind={r['ordind']}  conn={r['conn']}")

# --------------------------------------------------------------------------------------
F.banner("p2.2c  THE ATTAINING SET IS EXACTLY THE ORDINAL SUMS OF 1- AND 2-ELEMENT BLOCKS")

# mg-409a section 3 Case 2 shows this family is SUFFICIENT for alpha = 1.  In range it is
# also NECESSARY, and the count is a clean check: compositions of n into parts 1 and 2
# number Fib(n+1), and exactly one of them -- all parts 1, the chain -- has |L(P)| = 1.
def fib(k):
    a, b = 0, 1
    for _ in range(k):
        a, b = b, a + b
    return a

def is_ordinal_sum_of_small_blocks(n, lt):
    """P is an ordinal sum B_1 (+) ... (+) B_k with every |B_i| in {1,2}."""
    rest, blocks = set(range(n)), []
    while rest:
        # the minimal elements of what is left must form the next block
        m = {v for v in rest if not any((u, v) in lt for u in rest)}
        if len(m) > 2:
            return False
        if not all((a, b) in lt for a in m for b in rest - m):
            return False
        blocks.append(m)
        rest -= m
    return all(len(b) <= 2 for b in blocks)

print(f"  {'n':>2}  {'attain alpha=1':>14}  {'Fib(n+1)-1':>11}  {'all are 1/2-block ordinal sums':>32}")
for n, label, posets, prim_only in POPS:
    if prim_only:
        continue
    ones = [r for r in rows if r["n"] == n and r["alpha_is_one"]]
    fam = all(is_ordinal_sum_of_small_blocks(n, r["lt"]) for r in ones)
    pred = fib(n + 1) - 1
    ok &= F.verdict(len(ones) == pred and fam,
                    f"n={n}: {len(ones)} attainers, predicted {pred}, family-membership {fam}")

# the converse direction: every such poset with |L| >= 2 must attain
missing = 0
for n, label, posets, prim_only in POPS:
    if prim_only:
        continue
    for r in [x for x in rows if x["n"] == n]:
        if is_ordinal_sum_of_small_blocks(n, r["lt"]) and not r["alpha_is_one"]:
            missing += 1
ok &= F.verdict(missing == 0, "and every 1/2-block ordinal sum with |L|>=2 DOES attain",
                f"{missing} exceptions")
print("""
      So Daniel's read of the witness is exactly right, and stronger than he put it: it is
      not merely that mg-409a CHOSE a decomposable witness, it is that in range EVERY
      witness is decomposable, and decomposable in the same narrow way -- an ordinal sum
      of blocks of size at most 2.  Z_n is the all-blocks-size-2 member of that family and
      nothing outside it attains.  P9 is REFUTED: there is no attainer that is not an
      ordinal sum.""")

# --------------------------------------------------------------------------------------
F.banner("p2.3  THE MAXIMA, CLASS BY CLASS -- the number the ticket asks for")

print(f"  {'n':>2}  {'max alpha ALL':>14}  {'max alpha PRIMITIVE':>20}  {'max NON-primitive':>18}  "
      f"{'max ORD-INDEC':>14}")
for n, label, posets, prim_only in POPS:
    R = [r for r in rows if r["n"] == n]
    allm = max((r["alpha"] for r in R), default=None)
    prm = [r["alpha"] for r in R if r["prime"]]
    npr = [r["alpha"] for r in R if not r["prime"]]
    oi = [r["alpha"] for r in R if r["ordind"]]
    def s(v):
        return f"{v:.9f}" if v is not None else "     -- (empty)"
    tag = "  [PRIMITIVE-ONLY POPULATION]" if prim_only else ""
    print(f"  {n:>2}  {s(allm):>14}  {s(max(prm) if prm else None):>20}  "
          f"{s(max(npr) if npr else None):>18}  {s(max(oi) if oi else None):>14}{tag}")

PRIME_ROWS = [r for r in rows if r["prime"]]
best = max(PRIME_ROWS, key=lambda r: r["alpha"])
print(f"""
      THE PRIMITIVE MAXIMUM over every population above is

          alpha = {best['alpha']:.12f}   at n = {best['n']},  {cover(best['n'], best['lt'])}
          |L(P)| = {best['N']},  delta = {best['delta']},  mu = {best['mu']}
""")

# certify it EXACTLY: an exhibited rational test vector whose Rayleigh quotient is an upper
# bound on alpha at that poset -- no float on the verdict path.
LEb = L.linear_extensions(best["n"], best["lt"])
ub, which = F.alpha_exact_upper(LEb, best["n"], F.all_pair_stats(best["n"], best["lt"], LEb))
ok &= F.verdict(ub < 1, f"EXACT witness at the primitive argmax: alpha <= {ub} = {F.frac(ub)}",
                f"witness = {which[0]}")

# and the strong form: EVERY prime poset in range carries an exact witness strictly below 1
worst_ub = None
worst_row = None
for r in PRIME_ROWS:
    LEs = L.linear_extensions(r["n"], r["lt"])
    st = F.all_pair_stats(r["n"], r["lt"], LEs)
    u, _w = F.alpha_exact_upper(LEs, r["n"], st)
    if u is None:
        continue
    if worst_ub is None or u > worst_ub:
        worst_ub, worst_row = u, r
ok &= F.verdict(worst_ub < 1,
                f"EVERY prime poset in range has an EXACT witness with R_M < 1",
                f"worst = {worst_ub} = {F.frac(worst_ub)} at n={worst_row['n']} "
                f"{cover(worst_row['n'], worst_row['lt'])}")

# --------------------------------------------------------------------------------------
F.banner("p2.4  DOES THE PRIMITIVE CEILING FALL BELOW 3/4?  (P5)")

for n, label, posets, prim_only in POPS:
    R = [r for r in rows if r["n"] == n and r["prime"]]
    if not R:
        print(f"  n = {n}: no prime poset with |L| >= 2")
        continue
    m = max(r["alpha"] for r in R)
    print(f"  n = {n}: max alpha over primes = {m:.9f}   "
          f"{'ABOVE 3/4' if m > 0.75 else 'below 3/4'}")

above = [r for r in PRIME_ROWS if r["alpha"] > 0.75]
ok &= F.verdict(len(above) == 0,
                f"NO primitive poset in range reaches 3/4 -- the primitive ceiling is FAR "
                f"below pm-onethird's frozen bound",
                f"max over all primitives = {max(r['alpha'] for r in PRIME_ROWS):.9f}")
print("""
      P5 LOSES, and it loses in the direction that helps the closure.  I predicted the
      primitive maximum would exceed 3/4 on the reasoning that PRIMITIVE and FROZEN are
      logically independent restrictions -- a primitive poset may have every pair
      perfectly balanced, and nothing about having no nontrivial module forces any pair to
      be unbalanced.  That reasoning is sound and the conclusion is still false: the
      measured primitive maximum is about 0.39 at n = 4 and DECREASING in n.  Primitivity
      does not IMPLY the frozen bound, but it delivers a stronger one anyway, empirically.""")

F.banner("p2.4b  THE TREND -- the primitive maximum as a function of n")
prev = None
mono = True
for n, label, posets, prim_only in POPS:
    R = [r for r in rows if r["n"] == n and r["prime"]]
    if not R:
        continue
    m = max(r["alpha"] for r in R)
    arrow = ""
    if prev is not None:
        arrow = "  DOWN" if m < prev else "  UP  <-- NOT MONOTONE"
        if m >= prev:
            mono = False
    prev = m
    b = max(r["alpha"] for r in rows if r["n"] == n)
    print(f"  n = {n}:  max alpha PRIMITIVE = {m:.9f}   (max over ALL posets = {b:.9f}){arrow}")
ok &= F.verdict(mono, "the primitive maximum is strictly DECREASING in n over n = 4..7",
                "measured, not proved -- see the deliverable's 'what would make this wrong'")

# --------------------------------------------------------------------------------------
F.banner("p2.5  WHY THE RESTRICTION CANNOT RAISE THE CEILING -- the structural point")

print("""  mg-409a section 3 is a PROOF that alpha(P) <= 1 for EVERY poset with |L(P)| >= 2.
  It is not a maximum over a witness set.  Z_n is cited there only to show the bound is
  ATTAINED, i.e. TIGHT -- and tightness is the half of the statement the closure does not
  use.  Restricting the quantifier of a universally quantified upper bound to a subclass
  can only leave it or lower it; it can never raise it.  That is the whole answer to the
  objection, and p2.3 measures how much lower it in fact goes.""")

# The arm that makes that concrete: the ceiling proof's own witness, evaluated on primes.
n_ok = n_bad = 0
for r in PRIME_ROWS:
    LEs = L.linear_extensions(r["n"], r["lt"])
    st = F.all_pair_stats(r["n"], r["lt"], LEs)
    u, _w = F.alpha_exact_upper(LEs, r["n"], st)
    if u is not None and u <= 1:
        n_ok += 1
    else:
        n_bad += 1
ok &= F.verdict(n_bad == 0,
                f"mg-409a's OWN witness families certify alpha <= 1 at all {n_ok} prime posets",
                "the proof is class-blind, as claimed")

print()
print("=" * 88)
print("p2 OVERALL: " + ("PASS" if ok else "FAIL"))
print("=" * 88)
sys.exit(0 if ok else 1)
