#!/bin/bash
# Reproduces every number in docs/OneThird-Hodge-Side-Leverage.md (mg-a3d4).
#
# Pure Python 3, no third-party packages.  Total ~13 minutes on an M-series Mac.
# Run from this directory:   bash run_all.sh
#
# Outputs (committed, and regenerated byte-for-byte by this script -- EXCEPT the
# "[NNN.Ns]" wall-clock lines in sweep_output.txt, which are machine- and
# load-dependent by construction.  Narrowed by mg-a806: the regeneration after
# the mg-86a3 F6/F7 repairs reproduced every number identically and moved only
# those timing lines, so the unqualified claim was false as written):
#   theorems_output.txt  -- Theorems D, L, H, G and the two negatives N1, N2
#   sweep_output.txt     -- the local-to-global bound against the truth
#   lrb_output.txt       -- the face semigroup, Brown's theorem, and its scope
#   controls_output.txt  -- positive and construction-side negative controls
set -e
cd "$(dirname "$0")"

echo "[1/4] structural theorems and negatives ..."
python3 -u run_theorems.py > theorems_output.txt

echo "[2/4] local-to-global bound vs truth, all posets n <= 6 plus families ..."
HL_MAXN=6 python3 -u run_sweep.py > sweep_output.txt

echo "[3/4] face semigroup / Brown's theorem ..."
python3 -u run_lrb.py > lrb_output.txt

echo "[4/4] controls, both directions ..."
python3 -u controls.py > controls_output.txt

echo "done."
