"""witnesses.py (audit mg-ebbe): structural and exact checks of the KSBFT-S witnesses with own code.
(1) T8, T13, T14, N12: e, delta, deltaN, open-window NB failure, prime / indecomposable / range, the Doubling
    mechanism.  (2) Named families (families_dump.txt, generated by the AUTHOR's constructors, then checked here):
    interval order (no induced 2+2), number of non-nested pairs, doubly-trapped pairs; exact laws via ./aud when n<=22.
CONTROL: the 2+2 detector must fire on 2+2, W8 and T8.  Exit 1 on any failed assertion."""
import subprocess, sys
from fractions import Fraction as F
from census import parse, ups, indecomposable, prime, rng

ok = True
def check(c, msg):
    global ok
    print(("OK   " if c else "FAIL ") + msg); ok &= bool(c)

def inc(dn, a, b): return a != b and not dn[a] >> b & 1 and not dn[b] >> a & 1

def has_2p2(dn):
    n = len(dn)
    for a in range(n):
        for x in range(n):
            if not dn[x] >> a & 1: continue
            for c in range(n):
                for y in range(n):
                    if dn[y] >> c & 1 and inc(dn, a, y) and inc(dn, c, x) and inc(dn, a, c) and inc(dn, x, y):
                        return True
    return False

def nonnested(dn):
    up = ups(dn); n = len(dn)
    return sum(1 for a in range(n) for b in range(a + 1, n) if inc(dn, a, b) and
               dn[a] & ~dn[b] and dn[b] & ~dn[a] and up[a] & ~up[b] and up[b] & ~up[a])

def aud(s, v=False):
    out = subprocess.run(["./aud"] + (["-v"] if v else []), input=s + "\n", capture_output=True, text=True).stdout.splitlines()
    kv = dict(t.split("=") for t in out[-1].split(" | ")[1].split())
    pairs = {}
    for l in out[:-1]:
        t = l.split(); pairs[int(t[1]), int(t[2])] = int(t[3][2:])
    return kv, pairs

T3 = F(1, 3)
for tag, s, e, d, dN, pr, r in [
        ("T8", "8 0 0 2 6 3 e 17 5f", 42, F(17, 42), T3, True, 4),
        ("T13", "13 0 1 0 3 5 17 3f b bf 1ff 7f 7ff 47f", 588, F(17, 42), T3, True, 6),
        ("T14", "14 0 0 153 12 2 1b 3 3b 53 15f 11ff 33ff bb 3ff", 1395, F(656, 1395), T3, False, 5),
        ("N12", "12 0 4 0 6 f 885 6 805 aff 5f 8af 5", 1564, F(1, 2), F(1, 3) + F(1, 2346), False, 7)]:
    kv, P = aud(s, True); dn = parse(s); E = int(kv["e"])
    check(E == e and F(int(kv["d"]), E) == d and F(int(kv["dN"]), E) == dN,
          f"{tag}: e={E} delta={F(int(kv['d']), E)} deltaN={F(int(kv['dN']), E)} (doc: {e}, {d}, {dN})")
    check(indecomposable(dn) and prime(dn) == pr and rng(dn) == r, f"{tag}: indecomposable, prime={pr}, range={r}")
    if tag != "N12":
        check(kv["NBopen"] == "0" and kv["Bopen"] == "1", f"{tag}: open-window nested balance FAILS, open-window balance holds")
    check(kv["NB"] == "1" and kv["PNB"] == "1" and kv["DNB"] == "1", f"{tag}: closed NB, PNB and dual-PNB hold")
    check(has_2p2(dn), f"{tag}: contains an induced 2+2 (not an interval order)")
    if tag == "T8":
        check(P[0, 1] * 3 == E and P[0, 2] * 3 == 2 * E and P[5, 6] * 3 == E and P[5, 7] * 3 == 2 * E,
              "T8: P[0<1]=1/3, P[0<2]=2/3, (5,6)=1/3, (5,7)=2/3")
        check(P[3, 4] == 17, "T8: the interior pair is (3,4) at 17/42")
    if tag == "N12":
        check(F(P[0, 2], E) == F(521, 1564) and P[0, 1] == 2 * P[0, 2], "N12: P[0<2]=521/1564, P[0<1]=2*P[0<2]=521/782")

check(has_2p2([0, 1, 0, 4]), "CONTROL: 2+2 detector fires on 2+2")

print("--- named families (constructed by the author's fam.py; checked here) ---")
for line in open("families_dump.txt"):
    name, s = line.split(" ", 1); s = s.strip(); dn = parse(s); n = len(dn)
    io = not has_2p2(dn); nn = nonnested(dn)
    msg = f"{name:22s} n={n:2d} range={rng(dn):2d} interval_order={io} nonnested={nn}"
    if n <= 22:
        kv, _ = aud(s); E = int(kv["e"])
        msg += f" delta={int(kv['d'])/E:.5f} deltaN={int(kv['dN'])/E:.5f} NB={kv['NB']}"
        check(kv["NB"] == "1", msg)
    else:
        print("     " + msg + " (laws not recomputed: n>22)")
sys.exit(0 if ok else 1)
