"""mg-e7bc G1 -- THE PRIMARY MEASUREMENT: run the repaired check ON THE BROKEN
ARTIFACT and report the exit code.

mg-d0e2's F2 was a check that HELD on an artifact in which every scored row read
[FAIL].  mg-04a8 says it repaired that.  The single most informative measurement
available is not a description of why it now would go red; it is running it and
reading the status.  So every verdict below is taken from `checkrun.py` AS A
SUBPROCESS and what is reported is `proc.returncode`.

THREE THINGS ARE ASKED HERE, in this order.

  1. IS THE BROKEN ARTIFACT KEPT AND COMMITTED?  A positive control that lives
     only in an audit's memory is gone next generation -- which is precisely how
     mg-5f9a shipped a vacuous check nobody had watched fail.  So: is the file
     tracked by git, and is it still the flip of the CURRENT artifact rather
     than of some ancestor?  The second half matters more than the first: a
     committed control describing a previous artifact is testing nothing about
     this one, and mg-04a8's own claim about it is checked here against a flip
     generated by THIS file's `retag_rows` rather than by the subject's.

  2. THE EXIT CODES, on that artifact, for both checks -- the shipped one
     (expected: HOLDS, reproducing mg-d0e2's F2 from the code rather than from
     the audit's prose) and the repaired one.

  3. FIVE BROKEN ARTIFACTS OF THIS AUDIT'S OWN, none of them all-[FAIL].  A
     check tuned to the single known-bad example is this lineage's recurring
     failure, so the corruptions below vary the DIRECTION (all-[PASS], not
     all-[FAIL]), the SCALE (one row, not 43), the CHANNEL (a lying summary over
     honest rows) and the KIND (a row deleted outright rather than relabelled).

PREDICTIONS WERE REGISTERED BEFORE THE RUNS and are printed above the results;
the two that missed are kept as misses.
"""

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kerne7bc import (BAR, FINDINGS, HERE, INSTR, ROOT, SCORE, ART,   # noqa: E402
                      baseline_cannot, claim, drop_row, finding, head,
                      lie_in_summary, read, retag_rows, scored_rows,
                      summary_names)

PC_THEIRS = os.path.join(INSTR, "positive_control_all_fail.txt")
PC_MINE = os.path.join(HERE, "pc_all_pass.txt")

# (tag, what the artifact is, predicted shipped exit, predicted repaired exit)
# 0 = the check says yes.  1 = the check goes RED.
PREDICTIONS = [
    ("A-clean", "the committed artifact, untouched", 0, 0),
    ("A-theirs", "positive_control_all_fail.txt -- all 43 rows [FAIL]", 0, 1),
    ("B-allpass", "MINE: all 43 rows [PASS], including the 2 [CANNOT FAIL]",
     0, 1),
    ("B-one-fail", "MINE: exactly ONE [PASS] row flipped to [FAIL]", 0, 1),
    ("B-demote", "MINE: exactly ONE [CANNOT FAIL] row demoted to [PASS]", 0, 1),
    ("B-summary", "MINE: rows untouched, the SUMMARY lies (names a failure)",
     0, 1),
    ("B-drop", "MINE: one scored row LINE deleted outright", 1, 1),
]


def run_check(path, code=0):
    """The repaired check, as a process.  Returns (exit status, first line of
    its verdict)."""
    proc = subprocess.run([sys.executable, "checkrun.py", path, str(code)],
                          cwd=HERE, capture_output=True, text=True)
    verdict = [l for l in proc.stdout.split("\n") if l.startswith("verdict")]
    return proc.returncode, (verdict[0].split(":", 1)[1].strip()
                             if verdict else proc.stderr.strip()[:120])


def shipped_check(base_text, mut_text):
    """mg-5f9a's check, RE-DERIVED HERE from its four lines rather than
    imported, so that "the shipped check holds on this too" is a fact about the
    algorithm and not about the specimen the subject kept.

    Rows are selected by SUBSTRING (so prose bullets quoting a marker count as
    rows) and the label is taken as `a.split(" ")[1]` of a line that begins with
    two spaces -- which is the empty string for every row in either text.
    """
    def rows(t):
        return [l for l in t.split("\n")
                if "[PASS]" in l or "[CANNOT FAIL]" in l or "[FAIL]" in l]
    a, b = rows(base_text), rows(mut_text)
    changes = sum(x.split(" ")[1] != y.split(" ")[1] for x, y in zip(a, b))
    holds = len(a) == len(b) and changes == 0
    return holds, "%d rows, %d label change(s)" % (len(a), changes)


def tmp_artifact(name, text):
    path = os.path.join(HERE, "_tmp_" + name + ".txt")
    with open(path, "w") as fh:
        fh.write(text)
    return path


def main():
    print(BAR)
    print("mg-e7bc G1 -- the repaired check, run on broken artifacts")
    print(BAR)
    print("\nPREDICTIONS, registered before the runs "
          "(0 = the check says yes, 1 = RED):")
    print("   %-12s %-64s %8s %9s"
          % ("tag", "artifact", "shipped", "repaired"))
    for tag, what, ps, pr in PREDICTIONS:
        print("   %-12s %-64s %8d %9d" % (tag, what[:64], ps, pr))

    clean = read(ART)
    rows = scored_rows(clean)
    cannot = baseline_cannot(clean)
    npass = sum(1 for m, _ in rows if m == "[PASS]")
    ncf = sum(1 for m, _ in rows if m == "[CANNOT FAIL]")
    nfail = sum(1 for m, _ in rows if m == "[FAIL]")

    head("THE POPULATION -- named, because a bare total is not a measurement")
    print("  code/face_geometry/controls_output.txt, %d bytes" % len(clean))
    print("  %d scored rows: %d [PASS], %d [CANNOT FAIL], %d [FAIL]"
          % (len(rows), npass, ncf, nfail))
    print("  the bottom line names %d CANNOT FAIL row(s) and %d failure(s)"
          % (len(cannot), len(summary_names(clean, "CONTROLS FAILED:"))))
    claim(len(rows) == 43 and npass == 41 and ncf == 2 and nfail == 0
          and len(cannot) == 2,
          "the artifact this audit measures against carries 43 scored rows "
          "(41 PASS, 2 CANNOT FAIL, 0 FAIL) and a summary naming the same 2",
          "a row being added to or removed from controls.py -- which is what "
          "mg-04a8 itself did (41 -> 43), and the reason every count in this "
          "file is re-derived here rather than quoted from any transcript")

    # ------------------------------------------------------------- item 1
    head("1. IS THE BROKEN ARTIFACT KEPT AND COMMITTED?")
    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch",
         "code/face_geometry_instr_5f9a/positive_control_all_fail.txt"],
        cwd=ROOT, capture_output=True, text=True).returncode == 0
    claim(tracked,
          "positive_control_all_fail.txt is TRACKED BY GIT -- the control "
          "survives into the next generation instead of living in a transcript",
          "the file being generated at run time and never added, which is the "
          "state every control in this lineage was in before mg-04a8 and the "
          "reason mg-d0e2 had to build it from scratch to find the defect",
          "git ls-files --error-unmatch returned %s" % tracked)

    theirs = read(PC_THEIRS)
    mine_flip = retag_rows(clean, "[FAIL]")
    claim(theirs == mine_flip,
          "and it is still the flip of the CURRENT artifact: byte-equal to "
          "this file's own all-[FAIL] retagging of controls_output.txt",
          "controls_output.txt moving without the control being regenerated.  "
          "This is the stale-figure defect (mg-8e30) applied to a control "
          "file, and it is checked here with a flip generated by `kerne7bc."
          "retag_rows` rather than by the subject's own `flip_all_rows`",
          "%d bytes committed, %d bytes re-derived; %d of its %d rows read "
          "[FAIL]" % (len(theirs), len(mine_flip),
                      sum(1 for m, _ in scored_rows(theirs) if m == "[FAIL]"),
                      len(scored_rows(theirs))))
    finding(theirs != mine_flip,
            "the committed positive control is not the flip of the current "
            "artifact")

    # ------------------------------------------------------------- item 2+3
    head("2 AND 3. THE EXIT CODES")
    print("Every 'repaired' column below is `checkrun.py`'s process exit "
          "status:\n0 = the check says yes, 1 = THE CHECK GOES RED.\n")

    one_pass = [i for i, (m, _) in enumerate(rows) if m == "[PASS]"][0]
    one_cf = [i for i, (m, _) in enumerate(rows) if m == "[CANNOT FAIL]"][0]
    allpass = retag_rows(clean, "[PASS]")
    onefail = retag_rows(clean, "[FAIL]", lambda i, m: i == one_pass)
    demote = retag_rows(clean, "[PASS]", lambda i, m: i == one_cf)
    summary_lie = lie_in_summary(clean, rows[one_pass][1])
    dropped_text, dropped_what = drop_row(clean, one_pass)

    cases = [
        ("A-clean", clean),
        ("A-theirs", theirs),
        ("B-allpass", allpass),
        ("B-one-fail", onefail),
        ("B-demote", demote),
        ("B-summary", summary_lie),
        ("B-drop", dropped_text),
    ]
    observed = {}
    print("   %-12s %8s %8s %8s %8s   %s"
          % ("tag", "shipped", "(pred)", "repaired", "(pred)", "match"))
    for tag, text in cases:
        path = tmp_artifact(tag, text)
        try:
            rc, verdict = run_check(path)
        finally:
            os.remove(path)
        held, what = shipped_check(clean, text)
        s_rc = 0 if held else 1
        pred = [p for p in PREDICTIONS if p[0] == tag][0]
        ok = s_rc == pred[2] and rc == pred[3]
        observed[tag] = (s_rc, rc, what, verdict)
        print("   %-12s %8d %8d %8d %8d   %s"
              % (tag, s_rc, pred[2], rc, pred[3], "MATCH" if ok else "*** MISS ***"))
    print()
    for tag, (s_rc, rc, what, verdict) in observed.items():
        print("   %-12s shipped says %r; repaired: %s"
              % (tag, what, verdict))

    print()
    n_match = sum(1 for tag, _w, ps, pr in PREDICTIONS
                  if observed[tag][0] == ps and observed[tag][1] == pr)
    print("PREDICTION SCORE -- %d of %d matched.  Misses, kept as written:"
          % (n_match, len(PREDICTIONS)))
    misses = [(tag, w, ps, pr) for tag, w, ps, pr in PREDICTIONS
              if observed[tag][0] != ps or observed[tag][1] != pr]
    for tag, w, ps, pr in misses:
        print("   MISS %-12s predicted shipped %d / repaired %d, observed %d / %d"
              % (tag, ps, pr, observed[tag][0], observed[tag][1]))
    if not misses:
        print("   none")

    head("WHAT THE EXIT CODES SAY")
    claim(observed["A-theirs"][1] == 1,
          "THE PRIMARY MEASUREMENT: the repaired check, run as a process on "
          "the committed all-[FAIL] artifact, EXITS 1",
          "the repaired check going back to comparing the mutant's labels "
          "against the baseline's own -- section G3 makes that change and "
          "confirms this exit code becomes 0",
          "checkrun.py positive_control_all_fail.txt -> exit %d; %s"
          % (observed["A-theirs"][1], observed["A-theirs"][3]))
    claim(observed["A-theirs"][0] == 0,
          "and the SHIPPED check on the same artifact exits 0 -- mg-d0e2's F2 "
          "reproduced from a re-derivation of its four lines, not quoted",
          "the shipped check's row selection or its `split(' ')[1]` token "
          "changing.  It is re-derived in this file precisely so that this "
          "line is a fact about the algorithm rather than about the specimen "
          "the subject chose to keep",
          "it reports %r" % observed["A-theirs"][2])
    claim(observed["A-clean"][1] == 0,
          "and it is not a check that reddens on everything: on the unmutated "
          "artifact it exits 0",
          "the check acquiring an expectation the clean artifact violates, "
          "which is the failure mode that makes a red-on-everything control "
          "look like a working one")

    mine_red = [t for t in ("B-allpass", "B-one-fail", "B-demote", "B-summary")
                if observed[t][1] == 1]
    claim(len(mine_red) == 4,
          "AND ON FOUR BROKEN ARTIFACTS OF THIS AUDIT'S OWN, none of them "
          "all-[FAIL]: it exits 1 on each -- %s" % ", ".join(mine_red),
          "the check being tuned to the single known-bad example, which is "
          "what these four vary away from: the opposite direction (all-[PASS] "
          "including the two CANNOT FAIL rows), a single row rather than 43, "
          "a demotion rather than a promotion, and a corruption of the SUMMARY "
          "with the rows left honest",
          "; ".join("%s exit %d" % (t, observed[t][1])
                    for t in ("B-allpass", "B-one-fail", "B-demote",
                              "B-summary")))

    finding(observed["B-drop"][1] == 0 and observed["B-drop"][0] == 1,
            "SCOPE OF THE GUARD -- a corruption that DELETES a scored row line "
            "(here %r) leaves the repaired check GREEN (exit %d) while the "
            "SHIPPED check goes RED on it (exit %d, %r).  The repaired check "
            "derives an expectation for each row PRESENT, so a row that is "
            "gone contributes no expectation; the shipped check compared row "
            "COUNTS, which is the one thing it did compare.  This is not a "
            "refutation of the repair -- the label claim it makes is about "
            "labels -- but it is the extent of the guard, and mg-04a8's own "
            "sentence 'an artifact whose rows have been edited -- by a "
            "corruption, a bad merge, or a hand -- disagrees with its own "
            "summary, and the check below is what notices' is wider than what "
            "the code does"
            % (dropped_what[:60], observed["B-drop"][1], observed["B-drop"][0],
               observed["B-drop"][2]))

    # ---------------------------------------------- this audit's own control
    head("AND THIS AUDIT KEEPS ITS OWN, for the same reason mg-04a8 kept theirs")
    claim(os.path.exists(PC_MINE) and read(PC_MINE) == allpass,
          "pc_all_pass.txt is committed beside this file and is exactly the "
          "committed artifact with every scored row's marker replaced by "
          "[PASS] -- the OPPOSITE direction from the subject's control, and "
          "the more dangerous one: it is what a battery that had stopped "
          "checking anything would print",
          "controls_output.txt changing without this file being regenerated.  "
          "Generated by `retag_rows` on every run and compared, so the failure "
          "is loud rather than silent -- a control that has drifted off its "
          "artifact is the thing this audit's own ticket warns about",
          "%d bytes; %d of its %d rows read [PASS]; the 2 CANNOT FAIL rows are "
          "among the ones promoted"
          % (len(allpass),
             sum(1 for m, _ in scored_rows(allpass) if m == "[PASS]"),
             len(scored_rows(allpass))))

    print("\n" + BAR)
    print("%d claim(s) scored; %d BROKEN.  %d FINDING(s)."
          % (len(SCORE), SCORE.count(False), len(FINDINGS)))
    for f in FINDINGS:
        print("  FINDING: %s" % f)
    print(BAR)
    return 1 if not all(SCORE) else 0


if __name__ == "__main__":
    sys.exit(main())
