#!/usr/bin/env python3
"""p1 — WHICH TWO DIRECTORIES, read out of the sweep rather than inferred from the count.

mg-d2c2's first instruction is explicit: "Do not guess; the sweep names them, so read them
out of it rather than inferring from the count."  So this runs `a4_sweep.py` live, parses
its §3 name list, parses the same list out of the COMMITTED transcript (the reading the
gate's baseline was taken from), and diffs the two sets.

The diff is what names the directories.  The count is only used to REFUSE: if the parsed
list and the SWEEP decision line disagree, neither is reported.

The ticket's own guess is recorded in lib_d2c2.TICKET_EXPECTS and CONFIRMED OR CONTRADICTED
at the end.  A ticket that names the answer in the body and an instrument that agrees with
it are two readings of one derivation unless the instrument could have disagreed, so the
comparison is printed either way.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_d2c2 as L  # noqa: E402


def main():
    print("=" * 92)
    print("mg-d2c2 §1 — THE TWO NAMES, READ OUT OF THE SWEEP")
    print("=" * 92)
    print()

    live = L.run_sweep_live()
    now, pop_now, _ = L.parse_bare_list(live, "live run")

    baseline = json.loads(L.read(L.GATE_BASELINE))
    field = None
    for section in baseline.values():
        if isinstance(section, dict) and "audit.sweep_dirs_without_evidence" in section:
            field = section["audit.sweep_dirs_without_evidence"]
    if field is None and "audit.sweep_dirs_without_evidence" in baseline:
        field = baseline["audit.sweep_dirs_without_evidence"]
    if isinstance(field, dict):
        gate_value = field.get("value", field.get("baseline"))
        gate_class = field.get("class", field.get("kind", "?"))
    else:
        gate_value, gate_class = field, "?"
    print(f"  control_gate_724a BASELINE.json declares audit.sweep_dirs_without_evidence")
    print(f"    baseline = {gate_value}   class = {gate_class}")
    print()

    # ---------------------------------------------------------------- the baseline reading
    #
    # THE TRANSCRIPT THIS DIFF IS TAKEN AGAINST IS REGENERATED BY ./build.sh.  The merge gate
    # runs control_audit_9876/run_all.sh, which OVERWRITES out_a4_sweep.txt in place.  Anyone
    # who runs the gate before running this suite finds the "committed" reading already
    # advanced to today's, and the diff below silently comes back EMPTY — the finding erased
    # by the act of checking the tree.  Measured, not anticipated: it happened to this file
    # on its first gate run.  So the declared reading is recovered from git, and the
    # worktree copy is used only when git cannot supply one, with the substitution stated.
    rel = os.path.relpath(L.SWEEP_TRANSCRIPT, L.ROOT)
    source = None
    for rev in ("HEAD", "main"):
        text = L.git_show(rev, rel)
        if text is None:
            continue
        try:
            cand, cand_pop, _ = L.parse_bare_list(text, f"{rev}:{rel}")
        except L.Refused:
            continue
        if cand_pop is not None:
            then, pop_then, source = cand, cand_pop, f"git {rev}:{rel}"
            break
    if source is None:
        then, pop_then, _ = L.parse_bare_list(L.read(L.SWEEP_TRANSCRIPT), f"worktree {rel}")
        source = f"worktree {rel}  (git unavailable — this copy is REGENERATED by ./build.sh)"

    worktree_then, worktree_pop, _ = L.parse_bare_list(
        L.read(L.SWEEP_TRANSCRIPT), f"worktree {rel}")

    print(f"  baseline reading     : {len(then):3d} bare of {pop_then} directories")
    print(f"    read from          : {source}")
    if (worktree_then, worktree_pop) != (then, pop_then):
        print(f"    !! the worktree copy of that file reads {len(worktree_then)} of "
              f"{worktree_pop} — ./build.sh has regenerated it since the baseline was")
        print(f"       declared.  The diff below is against the DECLARED reading.")
    if gate_value != len(then):
        print(f"    !! the gate's baseline ({gate_value}) is not this transcript's count "
              f"({len(then)}) — one of the two has moved and neither is authoritative")
    print(f"  live run, this tree  : {len(now):3d} bare of {pop_now} directories")
    print()

    gone = sorted(set(then) - set(now))
    new = sorted(set(now) - set(then))

    print("-" * 92)
    print(f"  DIRECTORIES THAT ARE BARE NOW AND WERE NOT BARE IN THE COMMITTED READING: "
          f"{len(new)}")
    print("-" * 92)
    for n in new:
        added = L.git_added(n)
        print(f"      code/{n}")
        print(f"          first commit adding it: {added or 'unknown (git unavailable)'}")
    if not new:
        print("      (none)")
    print()
    if gone:
        print(f"  bare then and not bare now: {len(gone)}")
        for n in gone:
            print(f"      code/{n}")
        print()

    # ---------------------------------------------------------------- the reimplementation
    print("-" * 92)
    print("  IS THIS INSTRUMENT READING THE SAME PROBE THE SWEEP RAN?")
    print("-" * 92)
    print("  lib_d2c2.probe() imports a4_sweep's own regexes and re-combines them in three")
    print("  lines.  A reimplementation that agrees on 200 directories and differs on one is")
    print("  the failure this arrangement is exposed to, so it is checked against the list")
    print("  the sweep itself printed rather than trusted.")
    mine = sorted(n for n, p in L.all_dirs() if L.sweep_says_bare(p))
    agree = mine == sorted(now)
    print(f"    sweep printed : {len(now)} names")
    print(f"    this file computes : {len(mine)} names")
    print(f"    [{'PASS' if agree else 'FAIL'}]  the two lists are identical")
    if not agree:
        print(f"      only in the sweep's list : {sorted(set(now) - set(mine))}")
        print(f"      only in this file's list : {sorted(set(mine) - set(now))}")
    print()

    # ---------------------------------------------------------------- the ticket's guess
    print("-" * 92)
    print("  THE TICKET NAMED CANDIDATES IN ITS BODY.  DID THE SWEEP AGREE?")
    print("-" * 92)
    expected = sorted(L.TICKET_EXPECTS)
    others = sorted(n for n in new if n not in expected and n != L.SELF)
    print(f"    ticket body expects : {expected}")
    print(f"    sweep names, minus this directory : "
          f"{sorted(n for n in new if n != L.SELF)}")
    if sorted(n for n in new if n != L.SELF) == expected:
        print("    CONFIRMED — the two sets are identical, and the ticket's guess is")
        print("    therefore a reading of the sweep and not an independent one.")
    else:
        print("    CONTRADICTED — the sweep's answer is not the ticket's guess, and the")
        print("    sweep's answer is the one that was measured.")
        if others:
            print(f"    unaccounted for: {others}")
    print()

    # ---------------------------------------------------------------- the self instance
    print("-" * 92)
    print("  THIS DIRECTORY, MEASURED BY THE PROBE IT IS ABOUT")
    print("-" * 92)
    print("  The first run of this file, before p2 existed, put code/%s in" % L.SELF)
    print("  the bare list as the 28th name: an instrument whose entire subject is")
    print("  falsification evidence, reported as shipping none.  What changed that is not")
    print("  a control.  It is a FILENAME.")
    self_bare, self_why = L.probe(os.path.join(L.CODE, L.SELF))
    print()
    print(f"    bare : {self_bare}")
    print(f"    filename probe fires on : {self_why['filename_probe_hits'] or '(nothing)'}")
    print(f"    token probe fires on    : {self_why['token_probe_hits'] or '(nothing)'}")
    if self_why["filename_probe_hits"]:
        print()
        print("    THE PROBE HAS NOT RUN THAT FILE, READ IT, OR ASKED WHETHER IT ANSWERS")
        print("    BOTH WAYS.  It matched the substring `control` in the name.  p2 supplies")
        print("    the same credit to a constructed directory whose control does nothing.")
    if self_why["token_probe_hits"]:
        print()
        print("    AND THE TOKEN PROBE CREDITS THIS DIRECTORY TOO — on prose that is ABOUT")
        print("    the probe's false positives.  Each hit, with the line it was found on:")
        for fname, tok in self_why["token_probe_hits"]:
            hit = L.find_literal(os.path.join(L.CODE, L.SELF, fname), tok)
            where = f"{fname}:{hit[0]}" if hit else fname
            line = hit[1] if hit else ""
            print(f"      `{tok}` in {where}")
            print(f"          {line[:86]}")
        print()
        print("    Read the last of those. The sentence in which p3 REPORTS that a")
        print("    directory's transcripts contain no red token is itself a transcript")
        print("    containing red tokens, and it credits this directory with evidence of a")
        print("    falsification attempt on that basis.  A detector that scores its own")
        print("    negative report as a positive finding is not measuring the estate.")
    print()

    print("=" * 92)
    ok = agree
    if not ok:
        print("P1 NAMES — REFUSED: this instrument's reading of the probe does not match the "
              "sweep's own printed list, so nothing below it can be cited.")
        print("=" * 92)
        return 2
    print(f"P1 NAMES — {len(new)} newly bare: {', '.join(new) if new else '(none)'}   "
          f"(population {pop_then} -> {pop_now}, bare {len(then)} -> {len(now)})")
    print("=" * 92)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except L.Refused as exc:
        print()
        print("=" * 92)
        print(f"P1 NAMES — REFUSED: {exc}")
        print("=" * 92)
        sys.exit(2)
